### ISSUE TITLE
QUEST intensity scaling should be removed

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1006]
Currently, `data.QuestHandler.__init__()` takes the optional parameter `stepType`, which is later used to transform intensity values, as in:
```python
        startVal = self._intensity2scale(startVal)
        startValSd = self._intensity2scale(startValSd)
```
where `_intensity2scale()` is defined as:
```python
    def _intensity2scale(self, intensity):
        """returns the scaled intensity level based on value of self.stepType"""
        if self.stepType=='db':
            scaled_intensity = numpy.log10(intensity) * 20.0
        elif self.stepType=='log':
            scaled_intensity = numpy.log10(intensity)
        else:
            scaled_intensity = intensity
        return scaled_intensity
```
However, this interferes with the QUEST algorithm, which is implemented in `contrib.quest`, and already fully takes care of the stimulus selection. Jon also [mentioned](https://groups.google.com/d/msg/psychopy-users/5AsGnvLsPpU/wr1EPMnYJIYJ) something similar on the mailing list already.

The `stepType` argument should be removed. If a user wants to specify `startVal` and `startValSd` e.g. in terms of log intensities, they could easily do the calculation manually, i.e.,
```python
QuestHandler(np.log10(startVal), np.log10(startValSd), ...)
```
QUEST will take care of the rest.

Also, currently `stopInterval`, `minVal` and `maxVal` are not transformed, so I assume the current implementation is incorrect for all but linear `stepType`s anyway.

**Comment by peircej** [comment]
Your idea sounds correct to me.

**Comment by peircej** [comment]
Thinking about this some more I wonder what's the right thing to do given people with code that might have specified the stepType arg for the QuestHandler. Right now it's going to fail and they won't understand why. Options:
  - ideally we would deprecate the parameter, give a warning and then provide the original behaviour so that scripts continued to work but gave a warning to change the code. But I think you said this isn't possible?
  - second best option would be that the arg still exists with default of None, but if the user sets it to anything then we Raise an informative warning. At least the user gets told how to fix their code, rather than simply being told by Python that the arg doesn't exist.

**Comment by hoechenberger** [comment]
I will try to take a step back, reconsider the whole issue, and get back to you in a couple of days with some suggestions.
