### ISSUE TITLE
Clean-up coder demos

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#1018]
This is effectively re-opening #248. I'd like to go through all coder demos for style, clarity, consistency. 

I'll create a little script to help with migration assurance. Here's some thoughts I had earlier:
- standardize the top stuff: #!/usr/bin/env python2, encoding (utf-8), and the length and form of comment description
- follow PEP-8 (mostly, some possible exceptions)
- check that all imports are actually needed (remove any unnecessary ones)
- consistent use of variable names, e.g., win vs myWin
- consistent use of event.waitKeys() (or functional equivalent) to end each demo, use a timeout for full-screen demos

And other thoughts are here https://github.com/psychopy/psychopy/commit/ef845909c7668c99abf263bda638e91b54a54b4c

**Comment by hoechenberger** [comment]
This is a great move. I think I have some more suggestions for @ef84590, will get back to this tomorrow.

**Comment by jeremygray** [comment]
@peircej Are you ok with the Coder demos being explicitly public domain, with a line like this at the top of each demo file:

    # The contents of this file are in the public domain.

**Comment by peircej** [comment]
Yes, all good

**Comment by hoechenberger** [comment]
Would that mean they are exempt from the GPL 3+ that covers the rest of the project? What would be the reason for that?

**Comment by peircej** [comment]
People can share/re-use information about the project. They just can't take the project itself

**Comment by hoechenberger** [comment]
I think I still don't understand fully, but maybe inquiry should be taken off the issue tracker :)

**Comment by jeremygray** [comment]
These little demo scripts are basically documentation. We WANT people to
feel free to re-use and re-cycle this code in their own scripts, without
any need to feel like they are doing something wrong. Probably 90% people
see it that way already;  being explicit is just to reassure those who
might overthink it.

**Comment by hoechenberger** [comment]
Ah, okay, I think I get it now. Thanks very much for the clarification.

**Comment by hoechenberger** [comment]
I would like to add suggestions regarding characters per line and how to deal with long lines.

I personally try to limit my lines to 75 characters, as required per the [numpy style guide](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt). Given the availability of wide displays nowadays, one might well raise the question whether this limit is still reasonable. However, pretty much all more or less professional projects I know of limit the number of characters per line to 79 or 80, max. My IDE helps observing these limits by displaying a thin vertical line.

I also believe that, unlike some other rules, a character limit should be a strict rule, i.e. a must, not a should: As cognitive neuroscientists we all know about the fluctuation of decision criteria. Some programmers might be more liberal when to break the rule, some more strict. Or the very same programmer might decide differently from time to time.

While I generally think that some style rules should be flexible and common sense be used, I don't think this is a good idea for line widths, simply for the reason of what I like to call *reading ergonomics*. A good book doesn't have long lines either, because it makes them harder to read and to return to the beginning of the next line, as the eyes might lose track. Also, considering a long line of code where one would have to start scrolling to see the far left/right, this is not what an ergonomic workflow looks like.

Now this does lead to one problem: Long lines need to be broken. How can one do it, and what should be avoided? I very much like the examples presented [here](https://github.com/edx/edx-platform/wiki/Python-Guidelines#breaking-long-lines); I'll just paste them below:
>Breaking long lines
>
> Follow these guidelines:
>
> Try to refactor the code to not need such long lines. This is often the best option, and is often overlooked for some reason. More, shorter lines are good.
If you need to break a function call over more than one line, put a newline after the open paren, and move the arguments to their own line. DO NOT indent everything to where the open paren is. This makes the code too indented, and makes different function calls near each other indented different amounts.

```python
# NO NO NO!:

results = my_object.some_method(arg1,    # this is very
                                arg2,    # very ugly and makes
                                arg3,    # the code squished over on the right.
                                )
# YES:

results = my_object.some_method(
    arg1,
    arg2,
    arg3,
)
# OR:

results = my_object.some_method(
    arg1, arg2, arg3
)
```
>Important points:
> * Don't over-indent to make things line up with punctuation on the first line.
* Closing paren should be on a line by itself, indented the same as the first line.
* The first line ends with the open paren.

Generally, I really like that complete style guide: https://github.com/edx/edx-platform/wiki/Python-Guidelines

Many ideas from here also seem useful: http://deeplearning.net/software/pylearn/v2_planning/API_coding_style.html

**Comment by jeremygray** [comment]
@isolver: Are you ok with the ioHub demos being public domain code?

**Comment by jeremygray** [comment]
I like the deeplearning.net style guidelines. Most of it probably is not so relevant to the demos, but good to know. I especially like `try: .... except Exception: ...` to avoid bare `except`.

**Comment by peircej** [comment]
Sounds good guys. My previous comment about not liking changes that potentially obscure bugs doesn't apply to the demos so knock yourselves out making these perfect examples of code.

The thing with `myWin` versus `win` was that I once thought that myWin was easier for newbies to understand that this was there own instance, and distinct from the class Window. But the reality is that I never use that myself (obviously) so we ended up with a weird mishmash. I'd say just use `win`

**Comment by isolver** [comment]
Yes, of course.

**Comment by jeremygray** [comment]
Ok, I went through many of the demos (but not the more deeply nested ioHub ones) using the migration script as basis for further revision by hand. I went with `win` and tended to shorten long lines but some spill over 80 chars still. I tried to update things, like converting `rgb=x` to `color=x`, and `color=[1,1,1]` to `color='white'`. And most demos can now be stopped by any key, not just `q` or `escape`. I did not change variable names much if at all. The public domain note is at the very bottom, easy to relocate it. The position of the `from __future__ import division` is a little weird; can relocate it if someone prefers. And I don't think that import breaks anything (i.e., anything that depended on integer division). 

Any comments on further style issues?

**Comment by peircej** [comment]
Hmm, the `color='white'` thing is interesting. Although that's really easy to understand I wonder if it leads people to think that they can only have named colors (sounds limiting) and whether they won't learn about more useful color spaces as a result

**Comment by jeremygray** [comment]
> Hmm, the color='white' thing is interesting. Although that's really easy
to understand ...

That's what I was thinking.

> I wonder if it leads people to think that they can only have named colors
(sounds limiting) and whether they won't learn about more useful color
spaces as a result

That's what colors.py is for :-)

**Comment by jeremygray** [comment]
Updated demos are here, squashing commits: https://github.com/jeremygray/psychopy/commit/269abbf9b20694e15887c272d7801c95413ea4cc
