### ISSUE TITLE
Builder should allow raising priority

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1051]
The Builder should offer the option to `rush` through certain operations. I think ideally, there would be a per-routine checkbox which reads e.g. "Routine is time-critical". If enabled, we would execute `core.rush(enable=True)` at the beginning of the routine, and `core.rush(enable=False)` when the routine has finished.

**Comment by EitanHemed** [comment]
Ha, i did knew about rush. 
I'd like to help with getting this into the builder. Can you assign it to me?

**Comment by TEParsons** [comment]
Reopening because this actually would be good to have still - in 2024.1.0 we're introducing a "Piloting mode" with settings (in preferences) for what piloting mode changes. I think it would be good to have a checkbox in Experiment Settings for "enable rush", then one in the piloting section of prefs for "never enable rush in piloting mode"
