### ISSUE TITLE
Move implementations out of __init__.py in ioHub

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1054]
It is often [discouraged](http://stackoverflow.com/questions/15237806/python-modules-hierarchy-naming-convention#comment21484914_15237883) to put "significant" code into `__init__.py` files. As far as I know, this suggestion is followed by all parts of PsychoPy, with the exception of ioHub. We should consider doing the same there, also for the sake of consistency. This means the implementations would be moved out of `__init__.py` into their own modules, and made available at "root level" via an `import` statement.

@isolver, what is your position on this?

**Comment by jeremygray** [comment]
see also `psychopy.app.builder.components.__init__.py`

**Comment by isolver** [comment]
psychopy.iohub __init__.py is almost all just importing commonly used
submodule classes and functions into the iohub namespace so that people do
not need to have a ton of imports from different iohub submodules. I do not
think this is frowned upon, and is done in many of psychopy's modules, i.e.
psychopy.visual. Please correct me if I'm wrong about this.

However, the following func should be deleted from the file, and would take
the psychopy.iohub __init__.py line count from ~135 to under 70:

```
def _start(**kwargs):
    """
    Do not use this method. Incomplete. May go away.
    .....
    :return:
    """
```

This function is not used anywhere or by anyone; it was the beginning of an
attempt to make 'turning on' iohub py psychopy as easy as possible. This
was a while ago and things have changed.

Thanks.

**Comment by hoechenberger** [comment]
Hello Sol, great to hear back from you!
I'm sorry, I should have been more specific. I meant pretty much anything but  `iohub.__init__.py` :) I.e., `client.__init__.py`, `datastore.__init__.py`, `util.__init__.py`, and all the `__init__.py`s in `devices/*`. :)

**Comment by isolver** [comment]
OK, misread, sorry.

So in theory, yes, the contents of a submodule __init__(like
psychopy.iohub.devices.__init__.py) could be moved to another file (say
psychopy.iohub.devices._devices.py). However, then
 psychopy.iohub.devices.__init__.py would need to import everything from
psychopy.iohub.devices._devices.py. So I am not sure what is gained by
doing this. If anything it just adds a level of forwarding that is not
needed but adds complexity. Maybe I am missing what the actual benefit of
doing this is.

Reading through the stackoverflow post that was referenced, is the detly
<http://stackoverflow.com/users/188535/detly> comment what you are
referring to when stating "discourage putting significant code in
mymodule/__init__.py"? If so, I'm not sure I agree, since detly
<http://stackoverflow.com/users/188535/detly> states him(her)self in that
same comment:

though, eg. Alex Martelli <http://stackoverflow.com/a/2361278/188535>,
> which seems to be at odds with this.


Also, the top voted reply to the question from Blckknght
<http://stackoverflow.com/users/1405065/blckknght> also seems to disagree
with detly <http://stackoverflow.com/users/188535/detly> comment, with
Blckknght <http://stackoverflow.com/users/1405065/blckknght> stating, in
part:

So, for your situation, here's the appropriate filesystem layout:
> toplevel/
> mymodule/
>     __init__.py # *put code here for mymodule*
>     submodule.py # put code here for mymodule.submodule


I agree with this structure as well, and it is how iohub module __init__.py
files are written.

Anyhow, if it was stated to be an expected psychopy standard, yes it could
be done for all the iohub submodule __init__.py files. IMO though, It would
not even be close to the top of any iohub code refactor TODO list I would
spend time on. ;)

**Comment by jeremygray** [comment]
I'm with Sol on this one.

**Comment by hoechenberger** [comment]
Thanks for looking into this some more, Sol. So this thing really appears to be a matter of taste. The only reason to refactor would be for the sake of consistency with the rest of the PsychoPy code base. I'll leave this issue open for the time being, but don't see any need for immediate action anymore.

**Comment by jeremygray** [comment]
Actually, I rather expect we will refactor other parts of PychoPy to be more like ioHub in this regard. 

`psychopy.visual` already does this now. When refactoring `data.py`, this will probably become a directory that has an `__init__.py` file that has actual code. builder is a directory, and its `__init__.py` file is just a place-holder that imports * from builder.py. `builder/__init__.py` will very likely get some real code.

**Comment by hoechenberger** [comment]
> `psychopy.visual` already does this now.

No, as far as I can see, its `__init__.py` handles importing of the required sub-modules, but does not include any real implementations of classes or functions. I personally very much prefer this style over the ioHub approach, because it clearly separates implementations (in sub-modules) from the importing behavior of the package.

> When refactoring data.py, this will probably become a directory that has an `__init__.py` file that has actual code. builder is a directory, and its `__init__.py` file is just a place-holder that imports * from builder.py. `builder/__init__.py` will very likely get some real code.

I actually do not see a reason why. For `data.py`, we don't need anything but imports for the new, yet-to-be-created sub-modules. Why put anything more than that into `__init__.py`? it's just going to make things messier, breaking down the wall between how and what a package imports, and how these tings are actually implemented.

**Comment by jeremygray** [comment]
Ah, ok, I see more clearly now what you are saying.

**Comment by hoechenberger** [comment]
But maybe I am mistaken, please continue sharing your thoughts on this :)

**Comment by hoechenberger** [comment]
For ioHub, the current approach might actually be sensible; for the rest of PsychoPy, and esp. data.py, I would think it should better be avoided. But that's just my 2 ct.

**Comment by hoechenberger** [comment]
Moving much stuff into `__init__.py` will probably also antagonize (??) the idea of moving to lazy imports.

**Comment by mdcutone** [comment]
@isolver Is this still an issue? We should close it otherwise.
