### ISSUE TITLE
Missing openpyxl requirement

### ISSUE THREAD

**Issue by fnielsen** [psychopy/psychopy#1057]
I get `raise ImportError('openpyxl is required for saving files in Exel (xlsx) format, but was not found.')`

`sudo pip install openpyxl` fixes it.

I do not see openpyxl mentioned in the `setup.py`or any requirements.

This is for version 1.83.02 and installed via git clone and `python setup.py install`

**Comment by hoechenberger** [comment]
I think we should probably want to switch to using pandas entirely...

**Comment by peircej** [comment]
Recently it **has** been listed as a dependency here:
 http://psychopy.org/installation.html#dependencies
There are some lines of `pip install ......` there including openpyxl. If you have your own python installation you might have other dependencies missing so you might want to run those lines now?

Switching to Pandas is the approach of the newer TrialHander2 (I haven't actually written the xlsx output from that but it can be done). But using pandas doesn't solve the problem above because pandas does not itself write xlsx files; it depends on either openpyxl (again) or XlsxWriter (I think it doesn't care which is installed)

**Comment by hoechenberger** [comment]
I see openpyxl is also listed in [`requirements.txt`](https://github.com/psychopy/psychopy/blob/3d29a7550c123fc79dcfd4222aa663ad13114d46/requirements.txt). But shouldn't many of these deps not also be listed in [`setup.py`](https://github.com/psychopy/psychopy/blob/3d29a7550c123fc79dcfd4222aa663ad13114d46/setup.py#L52)'s call to `setup()` (via the `install_requires` argument)? Otherwise, when installing PsychoPy via pip, you may end up with a broken installation due to missing dependencies...

**Comment by peircej** [comment]
Yes, until recently the options of `pip install` gave such a broken set of dependencies that I didn't bother with it. ie. specifying the contents of requirements was so far from a proper install that it wasn't worth doing.
Increasingly that isn't true. Now only pyqt, pyo and wxpython need installers as far as I know (pyqt5 with py3 is available by pip and wxpython Phoenix release will be available by pip but it's still too buggy at the moment)
Switching to use `requirements.txt` from setup.py is OK except that there are different use cases with different requirements (do you need eyetracker, button box etc) and pip requriements is pretty inflexible with that stuff.
I'm happy for the pip installer to be updated though.

**Comment by hoechenberger** [comment]
Maybe we could provide different sets of `requirements.txt` files for different levels of (hardware) support? And update `setup.py` to install all deps necessary to
* run a visual study
* have sound via PyGame, and 
* be able to save data.

**Comment by peircej** [comment]
Yes, I'm happy for all this
Actually, for sound, I'm hoping we can move to sounddevice or pysoundcard which wil hopefuly beat pygame in latency
