### ISSUE TITLE
refactor to support python 3

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#1061]
This issue is to coordinate concerns and progress in moving towards python 3 support. The more complete the test coverage we have, the easier it will be to know what is working. `2to3` can handle some things, `six` and `modernize` are also useful tools.

Easier:
- [ ] replace `xrange` -> `range`. Probably no effective performance issues in python2 when using `range` (because the ranges in question are small), with the possible exception of ioHub. Watch for: xrange used as a variable name in visual/filters.py, line 49.
- [x] add `from __future__ import absolute_import` to all files (so that implicit relative can't sneak back in without someone noticing). Mostly done in fec18323128f
- [x] add `from __future__ import print_function` to all files, and migrate all print statements to print(). eg #942 
- [ ] add `from __future__ import division` to all files. First add only to those files that have good test coverage. Second, add to those without good coverage, and review carefully. 
- [ ] Unclear if needed, might cause issues: add `from __future__ import unicode_literals`. Seems most useful when converting python3 code to python2, less useful in our case and might cause problems inside packages that PsychoPy depends on.

Possibly more difficult:
- [ ] deal with strings / bytes. Some image-related operations are affected: pillow 3.0.x is now supported in PsychoPy. numpy arrays seem to support both `.tostring` and `.tobytes`

Dependencies, packaging, etc:
- [x] review all needed packages for p3 compatibility
- [x] change shebang to `#!/usr/bin/env python` (not `python2`) if / when both python2 and python3 are supported. Note that this can impact downstream, see #974 discussion.

**Comment by peircej** [comment]
`from __future__ import division` should be trivial. It's already being done at the start of every builder script and isn't apparently damaging anything (I don't think I've ever written a line of code that expected 1/3=0)

I spent a while working on print statements already in d313f011. There I added new format on all files and added the future import to a few files where it was required (without that the simple `print(x)` works but `print(x,y,z)` doesn't)

String/unicode is the annoying one in a way. For this we have to decide whether to support py2 and py3 at the same time. I think it would be nice if we can but it means testing in the code (or in a dedicated function) which version we have because `basestring` and `unicode` don't exist in PY3. So to test if something's a string we have to do something like this (untested):

      if PY3 and type(myVal) == str:
         print("It's a string")
      elif not PY3 and isinstance(myVal, basestring): #could be unicode or str
         print("It's a string in py2")

**Comment by jeremygray** [comment]
One consequence of importing division can mean that the resulting type
becomes float rather than int, causing some things to fail (like array
slices), even if the numerical value is the same.

**Comment by peircej** [comment]
Yes, but I don't think anything in PsychoPy itself is susceptible to that or we would have heard about it from people running Builder experiments

**Comment by jeremygray** [comment]
The library parts of PsychoPy (visual, sound, hardware, ...) have been
effectively tested by people when running Builder experiments (that import
division). Or there are subtle bugs that no one has reported :-P The
Builder and to some extent Coder could have issues. I expect they'll be
easy enough to catch and fix, and generally should not impact data obtained
from running an experiment. Maybe this is what you meant by "trivial" --
agreed

**Comment by cbrnr** [comment]
I think this should receive highest priority. I'm willing to help, so I thought I'd start by asking about the current status of this effort. Was Python 2 compatibility discussed? If not, I'll start by suggesting to support 3.5 and only 2.7 (i.e., drop support for 2.6, 2.5, ...). Thoughts?

**Comment by peircej** [comment]
A long-term issue here has been the (lack of) availability of dependencies and the fact that they could be installed easily by pip. Very few libs now suffer from this problem, which means it's much easier to get a python3 installation going and see what is falling over (previously I wasn't willing to bother because it was too much effort to get the installation working).

Now you can install python3 and then do the following (depending on what is needed):
```
pip3 install numpy scipy matplotlib pandas pyopengl pyglet pillow moviepy lxml openpyxl configobj pyyaml gevent greenlet msgpack-python psutil tables requests[security] pyosf cffi pysoundcard pysoundfile seaborn psychopy_ext python-bidi psychopy
pip3 install pyserial pyparallel egi iolabs
pip3 install pytest coverage sphinx
pip3 install pypiwin32
pip3 install pyobjc
```

That will give you some idea of where the work will be

**Comment by peircej** [comment]
pyo does not support py3 last I knew, so that's a(nother) reason to look into using something like pysoundcard or sounddevice for audio in/output

**Comment by peircej** [comment]
Dropping support for py2.6 is fine by me (that hasn't been tested in a long time anyway) and only 3.5 seems fair too

**Comment by peircej** [comment]
The only missing dependencies are now:
  pyo (but we could use PySoundCard while waiting)
  wxPython (although Phoenix does support python3 so I guess it's time to start testing that)

**Comment by peircej** [comment]
I've just run stage1 of the conversion using 
  http://python-future.org/automatic_conversion.html
(stage 1 converts print functions, absolute imports and exceptions). Out test suite still passes after these changes.

created a new branch at:
  https://github.com/peircej/psychopy/tree/refactor-py3

When I run stage2 of the automated conversion I get test suite errors coming from
psychopy/visual/helpers.val2array()
It looks like it's trying and failing to convert strings into arrays

**Comment by TheChymera** [comment]
Any update on this?

I would like to use psychopy under python 3 - but I notice that one of the dependencies (wxpython) is still known not to work under python 3.

* Has anyone tested psychopy with phoenix instead of wxpython?
* How much of psychopy can I expect to break if I just don't provide wxpython/phoenix?
* Does psychopy's own code work on python 3?

**Comment by peircej** [comment]
When I tried wxphoenix on my mac the application simply didn't run (I think it was an uninformative segfault). Really hard to predict whether that will turn out to be a simple fix or something complicated. I *think* it will be easy but just haven't tried.

We've now got a souddevice option (py3 compatible whereas pyo isn't) so that's one problem solved.

For PsychoPy's own code we've made some of the necessary changes. The tricky things like the above issue with `val2array` are likely to come from the altered string model - we need to remove any mentions of `unicode()`.

After that there will be many places where we might find bugs where something works differently under py3 but not so differently that it caused a visible (catastrophic) failure. Those are the ones that are a bit scary and I would personally not use PsychoPy3 (my preferred name for this branch) for a while for anything that mattered.

Basically the question doesn't have an answer. It's something where you go on removing roadblocks but you can't know whether there's another one behind it. Then suddenly there aren't any left and the car just runs!

**Comment by cbrnr** [comment]
Is there a PR or branch in a fork so that others can track the progress and contribute?

**Comment by hoechenberger** [comment]
Nope, not yet. However, contributions are highly welcome! Like Jon said, 
> It's something where you go on removing roadblocks but you can't know whether there's another one behind it.
I think we just have to get started. It's on my agenda as well, because PsychoPy is the only package preventing me from fully switching to Python 3. I believe the idea is to try and support both Python 2 and 3 simultaneously for now.

**Comment by peircej** [comment]
The first hurdle I think is to make psychopy work with wxPython 4.0 which is the first official release (this month!) of wxPython that runs on Py3. Hopefully we can make PsychoPy compatible with that *at the same time* as wxPython 3.0.2 which is what we currently use. If someone wanted to create a branch and have a stab at that it would be great.
Once that's done (which would mean all the strict dependencies exist in Py3) we start the second stage of updating our own code. That probably needs to be done in a rush not a trickle, or the Py3 branch and the master will be vulnerable to some nasty merge conflicts.

**Comment by cbrnr** [comment]
So you mean first we try to use wxPython 4 with the current master in Python 2? However, why would we want to support both wxPython 3.0.2 _and_ 4.0.0 when the latter runs on both Python 2 and 3?

**Comment by peircej** [comment]
Ideally we support both because many users will have 3.0.2 installed (e.g. on a personal installation of Python) and it's nicer not to force them to update. If it isn't possible then we can live with it but it becomes a deterrent to people upgrading if they have to upgrade the rest of their system at the same time

**Comment by cbrnr** [comment]
I agree. However, if it really isn't possible it won't be that bad because installing wxPython 3 didn't work with pip, whereas version 4 can simply be installed via pip (which means we'd force people to upgrade, but at a mild cost). I'll give this a shot and will create a new PR to discuss any issues we might encounter.

**Comment by peircej** [comment]
Agreed. Great! :-)

**Comment by cbrnr** [comment]
Oh wow, wxPython 4 introduced a lot of changes. Unfortunately, I have never used wxPython before, so I'm probably not the right person to migrate the code from 3 to 4. Here's the error I'm stuck with right now:

```
Traceback (most recent call last):
  File "/Users/clemens/Repositories/psychopy/psychopy/app/psychopyApp.py", line 62, in <module>
    app = PsychoPyApp(0, showSplash=showSplash)
  File "/Users/clemens/Repositories/psychopy/psychopy/app/_psychopyApp.py", line 118, in __init__
    self.onInit(**kwargs)
  File "/Users/clemens/Repositories/psychopy/psychopy/app/_psychopyApp.py", line 264, in onInit
    self.showCoder(fileList=scripts)
  File "/Users/clemens/Repositories/psychopy/psychopy/app/_psychopyApp.py", line 426, in showCoder
    files=fileList, app=self)
  File "/Users/clemens/Repositories/psychopy/psychopy/app/coder/coder.py", line 1366, in __init__
    self.makeMenus()
  File "/Users/clemens/Repositories/psychopy/psychopy/app/coder/coder.py", line 1540, in makeMenus
    text=msg % keyCodes['preferences'])
TypeError: Menu.Append(): arguments did not match any overloaded call:
  overload 1: 'text' is not a valid keyword argument
  overload 2: 'text' is not a valid keyword argument
  overload 3: argument 1 has unexpected type 'StandardID'
```

**Comment by hoechenberger** [comment]
> Oh wow, wxPython 4 introduced a lot of changes.

There's a migration guide at https://wxpython.org/Phoenix/docs/html/MigrationGuide.html

**Comment by mwaskom** [comment]
When trying to determine if psychopy officially supports Python 3.6 yet, google brought me here but #1407 looks to supercede this issue and is closed ... should this be closed too?

**Comment by peircej** [comment]
Yes I think we can! 😁

Repository version does now support python 3 although bugs are expected
