### ISSUE TITLE
relocate some files

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#1062]
It seems like the pyglet code in hardware.joystick.pyglet_input/ should migrate over into contrib/ 

So unless there's a reason not to, I'll move it over.

**Comment by jeremygray** [comment]
Proposed to relocate:
filters.py, makeMovies.py, and gamma.py -> visual

**Comment by jeremygray** [comment]
The proposed relocations would come along with their own deprecation notices, and still work functionally for some time to come.

**Comment by peircej** [comment]
Yes, similarly for @hoechenberger's refactoring of data, we need the original import method still to work, providing pointers to the new locations in the same way that visual still imports classes from the folder. I'd also recommend the same lazy importing method so that things are only fetched when needed.

For makeMovies I'm not sure. The code in there is inferior to other methods; the animated GIFs it made were rubbish compared with saving the files and getting GIMP to make them, and the movies were based on pymedia, which is defunct. Either we fix this one to use moviepy to outputs or we replace the file with:

```
Raise DeprecatedWarning, "PsychoPy is no longer providing (crumby) facilities for making movies. Please use moviepy instead, or output your movie as individual frames and knit them together with ffmpeg or GIMP"

**Comment by jeremygray** [comment]
Sounds good. I'm not personally up to fixing makeMovies to use moviepy, so I'll just leave it alone for now.

How do you test out whether lazy importing is being lazy? I seem to be getting non-lazy behavior with dir():

    >>> from psychopy import visual
    >>> dir(visual)
    ['Aperture', 'BaseShapeStim', 'BaseVisualStim', 'BufferImageStim', 'Circle', 'CustomMouse', 'DotStim', 'ElementArrayStim', 'EnvelopeGrating', 'FINISHED', 'FOREVER', 'GratingStim', 'ImageStim', 'Line', 'MovieStim', 'MovieStim2', 'MovieStim3', 'NOT_STARTED', 'PAUSED', 'PLAYING', 'PRESSED', 'PSYCHOPY_USERAGENT', 'PatchStim', 'Polygon', 'RELEASED', 'RadialStim', 'RatingScale', 'Rect', 'STARTED', 'STOPPED', 'ShapeStim', 'SimpleImageStim', 'TextBox', 'TextStim', 'Window', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'basevisual', 'getMsPerFrame', 'glob_vars', 'grating', 'helpers', 'image', 'lazyImports', 'lazy_import', 'logging', 'openWindows', 'pointInPolygon', 'polygonsOverlap', 'text', 'window']

**Comment by jeremygray** [comment]
Actually, it looks easy for someone to rewrite using moviepy. 

    import moviepy.editor as mp
    desired_fps = 32
    output_path = 'movie_out.mp4'
    images = [some list of file names]
    
    clip = mp.ImageSequenceClip(images, fps=desired_fps)
    clip.to_videofile(output_path)

**Comment by peircej** [comment]
dir() should indeed return everything. The system is working by faking 
the globals (otherwise you'll get an error when you try to use the 
object) and therefore it shows up in dir

With visual I was simply testing how long the import statement took 
(easy because visual takes ages to import the movie stimuli if not being 
lazy)
I guess you could put a print statement in the top of the file being 
imported and see whether it was printed during import or during use.

-- 
Jonathan Peirce
University of Nottingham

http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.

**Comment by jeremygray** [comment]
Importing visual imports visual.window, which in turn imports gamma. I will leave it as a lazy import but its basically not saving any load time. filters are used only in demos (two) and in tests, so that should be lazy-able.

Closing this issue with commit a10cce9818d9abe6e
