### ISSUE TITLE
does hardware/joystick need pyglet_input?

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#1066]
I don't have a joystick to try things out. Would it work to use 

    import pyglet.input as pyglet_input

in `hardware/ joystick/.__init__.py` line ~41,and remove the directory `pyglet_input`?

That is, pyglet already comes with PsychoPy, and provides pyglet.input. Is there something special about this particular version inside `pyglet_input` that it needs to be kept for `joystick`?

**Comment by peircej** [comment]
The pulling in, and slight adaptation of that joystick module was because joysticks only got added to pyglet 1.2. I fetched this to make it available to our 1.1.4 version before updating. I haven't looked at it again recently. Last I knew joysticks were broken for us under 1.2 as well though because the event handling seems to have changed:
  - pyglet now expects you to create a pyglet app that controls the event loop. We don't want to do thatl.
  - I haven't found the way under the new system for us to pump the event loop (which is needed to get events from the joystick polling) directly from our own commands

So, ultimately, yes we should probably kill that file now that we're using pyglet 1.2 (although I don't know if that will break any current code) but we still need to to work out how to do polling.

**Comment by jeremygray** [comment]
I moved pyglet_input/ input contrib/ (instead of hardware/).

**Comment by peircej** [comment]
Someone on the forum reported that the regular pyglet joystick from 1.2 was working fine. I suggest we delete this file completely and point our references to pyglet.joystick instead

**Comment by jeremygray** [comment]
This should have been closed automatically with ff223ecac
