### ISSUE TITLE
WARNING 	pyo audio lib was requested but not loaded: 

### ISSUE THREAD

**Issue by stanmulik** [psychopy/psychopy#1107]
Hi, 
I'm trying to run an experiment in the version 1.83.04 apparently, everything runs smoothly. However, I get this WARNING message: 
```python
1.3478 	WARNING 	pyo audio lib was requested but not loaded: dlopen(/Users/TECAAL3/Desktop/PsychoPy/PsychoPy2.app/Contents/Resources/lib/python2.7/lib-dynload/_pyo.so, 2): Library not loaded: @executable_path/../Frameworks/liblo.7.dylib

Reason: Incompatible library version: _pyo.so requires version 10.0.0 or later, but liblo.7.dylib provides version 9.0.0
```
How do I solve this? And more importantly, how do I know whether it's affecting my experiment? Because it doesn't seem to. All audios run fine. 

Thanks a lot, 
Stan

**Comment by tahabi** [comment]
It doesn't really make a difference because psychopy.sound selects between pygame and pyo behind the scenes and offers the sound.Sound API, but since liblo hasn't been updated in line with pyo in the latest standalone, I manually linked the latest liblo for OS X into the PsychoPy binary, because I wanted to use pyo features. It shouldn't affect your experiments, although there are differences between how pygame and pyo handle audio.

**Comment by stanmulik** [comment]
Thank you very much! It doesn't seem to affect them at all.
