### ISSUE TITLE
proposed new exp setting: useVersion

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#1130]
It would give more control to let an experimenter specify the version of PsychoPy to be used with a given experiment. Then during script generation, just write out into the top of the script: import useVersion, useVersion(whatever).

Issues to work out:
- If the requested version is a good version but not available and cannot be obtained right now (e.g., no internet connection, no write permission, etc), what to do then?
- If left unspecified, what should the effective default be? Maybe "whatever version is currently running", seems most like current behavior.
- It seems like there is a little more work needed to handle bad version choices. e.g.:

```python
    >>> useVersion('1.80.04')
    Cloning Psychopy Library from Github - this may take a while
    git clone -o github https://github.com/psychopy/versions versions
    Cloning into 'versions'...
    remote: Counting objects: 2156, done.
    remote: Compressing objects: 100% (692/692), done.
    remote: Total 2156 (delta 1340), reused 2156 (delta 1340), pack-reused 0
    Receiving objects: 100% (2156/2156), 3.21 MiB | 635.00 KiB/s, done.
    Resolving deltas: 100% (1340/1340), done.
    Checking connectivity... done.
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/jgray/code/psychopy/psychopy/tools/versionchooser.py", line 60, in useVersion
        requestedPath = _setupRequested(requestedVersion)
      File "/Users/jgray/code/psychopy/psychopy/tools/versionchooser.py", line 93, in _setupRequested
        _cloneRequested(requestedVersion)
      File "/Users/jgray/code/psychopy/psychopy/tools/versionchooser.py", line 153, in _cloneRequested
        cwd=VERSIONSDIR)
      File "/Users/jgray/anaconda/lib/python2.7/subprocess.py", line 573, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['git', 'checkout', '1.80.04']' returned non-zero exit status 1

    >>> useVersion('1.80.08')
    fatal: Not a git repository (or any of the parent directories): .git
    ('Now using PsychoPy library version: ', '1.80.05')
    True

    >>> useVersion('1.80.03')
    ('Now using PsychoPy library version: ', '1.80.03')
    True
```

**Comment by peircej** [comment]
The issues you raise below are, I think, true for builder and for code.

> If the requested version is a good version but not available and cannot be obtained right now (e.g., no internet connection, no write permission, etc), what to do then?

All this is handled by git locally. For a version to be accessible this user needs to have done useVersion at least once requesting that version (or more recent). useVersion tests locally in the git repo of versions first, then does a git fetch from online if it wasn't found. 

We could populate an option list with only the options that are available to the current user rather than allowing the to type. tools.versionchooser should have a getVersions() function that uses `git tag` to determine valid versions.

> If left unspecified, what should the effective default be? Maybe "whatever version is currently running", seems most like current behavior.

Yes, default is that the current installed version is used. The code in site-packages isn't being changed when useVersion is run. The git repo is in user space (users can't typically alter prog files) and useVersion is updating the user space git repository and then making that the version to use by adding to the python path ahead of the site-packages.

> It seems like there is a little more work needed to handle bad version choices. e.g.:

Yes indeed. As with most of PsychoPy we don't do much to handle user-errors. :-(


**For Builder integration there's an additional issue though.** useVersion needs to be called before too much importing has been done, although we can do a bit of updating afterwards using `reload`. So I don't know whether we can use it to output the builder-generated scripts. If we change the builder script generation between versions (e.g. to reflect changes in library) then the library will respect the new version but the script itself will be written for an earlier version.

This aspect will be hard to get right, but providing a selection option (Exp Settings) that forces the lib to use a particular version should be easy enough.

**Comment by jeremygray** [comment]
It sounds like a basic feature like this is worth adding, although there will be some unresolved issues.

> We could populate an option list with only the options that are available to the current user rather
> than allowing the to type. tools.versionchooser should have a getVersions() function that uses git 
> tag to determine valid versions.

I like this. How about options for any valid tag (on github), not only those that are currently available (locally). If the user has never used useVersion(), presumably no versions will be available

**Comment by peircej** [comment]
On 07/03/2016 14:29, Jeremy R. Gray wrote:
>
> It sounds like a basic feature like this is worth adding, although 
> there will be some unresolved issues.
>
>     We could populate an option list with only the options that are
>     available to the current user rather
>     than allowing the to type. tools.versionchooser should have a
>     getVersions() function that uses git
>     tag to determine valid versions.
>
> I like this. How about options for any valid tag (on github), not only 
> those that are currently available (locally). If the user has never 
> used useVersion(), presumably no versions will be available
>
>
Yes, could try doing a git fetch first (but ignore a fail) and then 
fetch the tags. If there is no internet then the previous state will be 
retrieved but otherwise the current best set will be used and stored for 
future.

**Comment by jeremygray** [comment]
Cool. For discovering available versions to display them in a dialog GUI, I think `git ls-remote --tags https://github.com/psychopy/versions` is better than fetching, because fetch can take a long time if there's a lot to download.

**Comment by peircej** [comment]
OK sure

**Comment by peircej** [comment]
OK, the problem of Builder not writing the script in the same version as the target psychopy version is raising itself currently in the github version. The current repos version (1.84) wants to do `from psychopy import setup_locale` but selecting version as "latest" (which is older than this) means that sub-module doesn't exist and the experiment fails to start. I think we should set the default to be <blank> rather than "latest" until we get things debugged a bit.
