### ISSUE TITLE
better testing of conditions file

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#1147]
Problems with conditions files can reveal themselves in non-obvious ways. A header with empty column or row of empty cells has caused problems recently. Testing when loading would be useful in order to provide more helpful error messages.

**Comment by m-macaskill** [comment]
This issue is specific to .csv files, so might be related to the switch to pandas csv importing? i.e. blank values in a csv file lead to `nan` values in that column. When the .psyexp file is re-opened subsequently, visible structure is lost in the flow panel (e.g. routines and loops disappear, and might not be able to added again).

Meanwhile, an equivalent .xlsx file will generate `None` values and not cause the same issues.

**Comment by m-macaskill** [comment]
Sure enough, `pandas` has some options for dealing with `nan` values which we should probably specify explicitly: http://stackoverflow.com/questions/10867028/get-pandas-read-csv-to-read-empty-values-as-empty-string-instead-of-nan

I'll try to look into it to see if this is the issue.

**Comment by peircej** [comment]
In this commit Jon Roberts changed the import to convert `numpy.nan` to `None` (in keeping with the xlsx imports): 
bb0c496c50
and in this commit we made a subsequent change to that to handle string cells:
4b03da875b

Hopefully this issue is now resolved?
