### ISSUE TITLE
DLG.show() Returns none

### ISSUE THREAD

**Issue by OliJimbo** [psychopy/psychopy#1175]
Hi,

This issue came up on the board and I can replicate it in coder.

dlg.show() is not returning the list of dlg values.  The how-to mentions that the method has been deprecated and to use .display() instead - but I couldn't find this in the dir() output.  Is support for this in the pipeline?

BW

Oli

**Comment by peircej** [comment]
There was a clash of developers and between code and docs. The demo in 
coder view should have been working for both wx and qt backends but the 
documentation was only correct for the qt backend.

I've fixed this now so that:
     - qt doesn't (incorrectly) claim that show() will be deprecated
     - wx.Dlg now returns a copy of the data (as does qtgui.Dlg) whereas 
previously you had to access it using Dlg.data (as shown in the demo)
     - the demo shows the newer usage and also shows how to specify the 
gui backend rather than rely on the default

cheers
Jon

On 17/05/2016 10:39, OliJimbo wrote:
>
> Hi,
>
> This issue came up on the board and I can replicate it in coder.
>
> dlg.show() is not returning the list of dlg values. The how-to 
> mentions that the method has been deprecated and to use .display() 
> instead - but I couldn't find this in the dir() output. Is support for 
> this in the pipeline?
>
> BW
>
> Oli
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/1175>
>

-- 
Jonathan Peirce
Nottingham Visual Neuroscience

http://www.peirce.org.uk





This message and any attachment are intended solely for the addressee
and may contain confidential information. If you have received this
message in error, please send it back to me, and immediately delete it. 

Please do not use, copy or disclose the information contained in this
message or in any attachment.  Any views or opinions expressed by the
author of this email do not necessarily reflect the views of the
University of Nottingham.

This message has been checked for viruses but the contents of an
attachment may still contain software viruses which could damage your
computer system, you are advised to perform your own checks. Email
communications with the University of Nottingham may be monitored as
permitted by UK legislation.
