### ISSUE TITLE
DotStim: coherence should define individual probability rather than (rounded) proportion

### ISSUE THREAD

**Issue by cherepaha** [psychopy/psychopy#1238]
The coherence attribute of DotStim is currently rounded based on nDots, which effectively makes this parameter discrete. This is incorrect behavoir, especially for small nDots. Particularly, coherence levels less than 1/nDots are rounded to zero. As a result, e.g., for nDots = 6, coherence level of 0.1 (which is above perceptual thresholds reported by Scase et al) is rounded to zero, so there is no coherent motion when DotStim is presented.

The algorithm should be modified in a way that the coherence parameter defines individual probability for each dot to move in the stimulus direction at each frame. It is then possible that more or fewer than round(coherence/nDots) are moving coherently at any given frame, but the overall proportion of coherently moving dots over many frames will be exactly the coherence value.

**Comment by peircej** [comment]
I'm not sure about this. If you have a small number of things then you can't have *exactly* the right proportion **ever**. Switching to have individual dots choose probabilistically on every frame whether they should be signal or noise simply moves the problem to a different one. Now if your number of frames is small then you have the problem instead. No?

At least with the current solution you can determine what the rounding is going to be. With your proposal you'd have a continuous moving average coherence, which is more painful to understand for the experimenter.

So I think your solution, while it might be good for your particular experiment, is not the right solution for the general user

**Comment by cherepaha** [comment]
Hi Jonathan, 

I understand your concern about not having the defined proportion of the dots moving coherently for 'probabilistic' version of the algorithm when number of frames is small. However, I would argue that the problem I have for the 'proportion' version is more serious than the one you outlined. Moreover, it extends beyond my particular study and affects any experiment using DotStim with arguments noiseDots='position', signalDots = 'different'. Probably, this issue doesn't apply to other argument combinations, so I won't touch on them here.

Side note: The algorithm Scase et al (1996) describe as noiseDots='position', signalDots = 'different' is sometimes referred to as 'white noise' algorithm , so I'll make use of the WN abbreviation for this case.

**First**, I'll argue that the problem with current version of WN implementation is rather serious, and affects many potential users.

In the experiments using the WN algorithm, the number of dots per frame is usually kept small. For instance, consider Scase et al. 1996 study, where they use 3 deg square aperture on a monitor refreshed at 75Hz. Their dot density varies from 16.5 to 66, which yields 3*3*16.5/75 = 2 to  3*3*66/75 = 8 dots displayed on each frame. For this setup, regardless the number of frames, using the 'proportion' version of the algorithm a priori won't allow one to distinguish between 0 and 0.1 coherence, which Scase et al. do manage to achieve in the end (their resulting coherence thresholds are around 0.06). Same considerations apply to the experimental setups reported in the papers of Movshon, Newsome, Britten cited by Scase et al, as well as other papers using the WN algorithm.

**Second**, I'll try to address your concern about possible issues of the proposed WN implementation

Considering that human visual system is quite sluggish, it perceives more than one frame at a time. Thus, the 'probabilistic' version of the algorithm ensures that at any given time the proportion of the _perceived_ dots moving coherently is very close to the coherence value, even if you just have several frames. Newsome & Pare 1988 paper (cited by Scase et al among other sources of WN algorithm) goes along the same lines:

> "Since dots are plotted singly at 150 μsec intervals with a 20-30 μsec survival time, dot density in the display is usually 0. However, because of the persistence of images in the visual system, an observer in fact perceives numerous dots at any instant in time. If one assumes a rough figure of 100 msec for visual persistence, the dot density at a given point in time is about 1.7 dots/deg^2. In our standard viewing aperture (10” diameter), therefore, about 130 dots are visible at any point in time."

Please let me know your thoughts on this.

**Comment by peircej** [comment]
For Scase et al, as I read it the dots were presented in a "3 deg square window" (so presumably an area of 9 deg^2) and the smaller dot density of 16.5 /deg^2 means a total of 16.5*9 = 148 dots. (I may have missed something though - I don't know where your `3316.5/75` comes from - why is the 75 Hz frame rate in the calculation?) If I'm right then already they can use fixed numbers of dots as signal and noise and get a coherence resolution of 1/148. Scase et al did have only 9 frames though (8 displacements on which a dot could be signal or noise) so I think they would suffer from a probabilistic coherence varying on each frame. Basically, with a small number of frames and large number of dots, the current solution is optimal.

I haven't gone back to the Newsome & Pare paper to check, but by your quote "130 dots were visible at any point in time". So they also don't have a problem getting a decent resolution of coherence. 

I've never seen, and I'd be quite unsure about, an RDK stimulus with very few numbers of dots per frame. It might cease to be a "global motion" stimulus. With only a few dots visible a single one could grab participants' attention and they would be tempted to make a decision based on that rather than global stats. Both the studies above were conducted at a time when computers were slow and it was technically challenging. On modern machines the reason to use small numbers of dots is even less clear.

**Comment by peircej** [comment]
In fact, if the signal selection rule (in Scase terminology) is "same" then the choice of which dots are signal has to be fixed so we **couldn't** (and they couldn't) use your probabilistic approach for those rules.
