### ISSUE TITLE
response.corr not properly set when collecting 'all keys'

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1275]
Reported by John [on the forum](http://discourse.psychopy.org/t/possible-bug-on-response-corr-if-logging-all-keys/1287):

> When I ran a trial loop with logging set for 'all keys' then the response.corr value was incorrectly 0/false for all trials , even when only a single key was pressed for each trial however if I changed the setting to log only the 'last key' then the response.corr is values are then accurate.
> 
> This seems to be independent of whether 'discard previous' is set.
> 
> I can't think of why this should be so I thought I should flag it. Sorry haven't got time to load up an MVP demo.

**Comment by peircej** [comment]
The issue here is what "correct" should be if you're allowing participants to respond multiple times. It means you need to provide a correct sequence rather than a single key. I think the current solution will allow a set of keys to be tested (input as a list) but you have to get them all correct o be considered correct. So you might be able to set "correct" to be ["a"] and the subject will then be correct if they only press "a" but not if they press "a" as well as other keys.

The case of testing correct based on the first or last (or any) single key of a multi-key sequence seems like a bad idea because everyone will want the "other" option whichever one we use. The options/rules start getting many and complex and this should be done with a simple code component to test correctness yourself with any arbitrary rule.
