### ISSUE TITLE
moviestim3, OS X 10.11.6, miniconda installation avoiding pyo error in silent movies

### ISSUE THREAD

**Issue by ofgulban** [psychopy/psychopy#1305]
Hi, I was having the following error when using moviestim3 in Mac Os X 10.11.6 through miniconda installation (psychopy release version 1.84.2):

```
1.2897  ERROR  No audio API found. Try installing pyo 0.6.8+, or pygame 1.8+
```

However I do not have sound in any of my movie clips so I had a look into the source code (psychopy/visual/movie3.py) and realized that all I need to do is to comment out this line:

```from psychopy import sound```

moviestim3 works fine afterwards with no errors.

I wanted to let you know about this specific case. Maybe you can handle it differently when there is no sound, like only importing the sound module if noAudio is True.

**Comment by peircej** [comment]
I don't fancy pursuing this one myself but happy to take a pull request if someone else wants to do it. I'd rather get sounds to work on anaconda!

As a side issue, the reason to use anaconda used to be that it was easier to install things than python, but since python wheels have become common I think it might be easier just to use regular python. PsychoPy's installation docs show how easy it is to get everything that way now:
http://psychopy.org/installation.html#manual-install

**Comment by ofgulban** [comment]
Thanks for the response. Moviestim3 works without a problem in windows and linux (with conda installation) but unfortunately in mac this was not the case. I have created a [pull request](https://github.com/psychopy/psychopy/pull/1306). It is more of a workaround for silent movies.

**Comment by hoechenberger** [comment]
Is this issue closed by #1306?

**Comment by ofgulban** [comment]
@hoechenberger yes, I think so.

**Comment by hoechenberger** [comment]
Thanks!
