### ISSUE TITLE
psychopyApp won't start with Matplotlib 1.5 installed

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1315]
See http://discourse.psychopy.org/t/mac-specific-help/1540/3

We need to figure out
- whether this problem is Anaconda-specific (and would require fixing upstream)
- whether this problem is Mac-specific

**Comment by peircej** [comment]
I'm pretty sure this occurs anytime that wx has been imported before matplotlib. I haven't found out what changed in matplotlib, but I  imagine it has a different os more restrictive expectation of valid language encodings. I think the fix will be either a) change to matplotlib upstream to detect the current lang setting from wx or b) change to wx so that the default it sets is matplotlib-compatible

I definitely don't think it's a psychopy problem though, but a dependency clash

**Comment by hoechenberger** [comment]
I wonder if this could be related: https://github.com/matplotlib/matplotlib/issues/5737

**Comment by peircej** [comment]
No, I think that issue was due to a matplotlib user trying to get two different gui clients (wx and QT) to run in Python at one time. We do occasionally see that problem too, but that's unrelated to this issue with language encoding.
