### ISSUE TITLE
Change importConditions to use pandas

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1321]
`data.importConditions` would benefit from a switch to pandas as this would make the code more maintainable and get rid of problems e.g. when trying to import data from documents saved in a right-to-left manner, as reported in this posting:

http://discourse.psychopy.org/t/error-moving-to-psychopy-veriosn-1-84-2/1635/

**Comment by peircej** [comment]
for csv imports this is already in use. It's **possible** that all we need to change is about 3 lines where we do `if filename.endswith(".csv"):` and make it `if filename.endswith([".csv",".xlsx"]):` then change the `read_csv` line as well.
BUT I'm not certain that this will fix the particular problem noted above which may have been related to the presence of empty cells rather than the loading of the file per se.

**Comment by hoechenberger** [comment]
> BUT I'm not certain that this will fix the particular problem noted above which may have been related to the presence of empty cells rather than the loading of the file per se.

In the specific example from the forum, it does indeed fix the problem:

![pandas](https://cloud.githubusercontent.com/assets/2046265/21236962/55fbbd98-c2fd-11e6-82fd-a0acecf58ee7.png)

**Comment by peircej** [comment]
I'll have a look at changing it now

**Comment by peircej** [comment]
This was done in d1a77d2c2cd310eab76f8693c2a6b458c99b5d8a I think

**Comment by hoechenberger** [comment]
This is great!!!!
