### ISSUE TITLE
Coder tutorial 2 does not work as expected

### ISSUE THREAD

**Issue by m2march** [psychopy/psychopy#1342]
The code for the second tutorial of the coder does not work as expected given that the number of trials set in the StairHandler is 1. 

See: https://github.com/psychopy/psychopy/blob/master/docs/source/coder/tutorial2.py#L28

**Comment by peircej** [comment]
The surprise is caused by the fact that multiple things control the termination of a staircase. We need to exceed both the nTrials and the number of reversals. In this example there are 7 step sizes so we'd need to get to at least 7 reversals in order to terminate.

It's a tricky one to know what to do. Personally I would usually only set up a staircase with few (minimum) reversals and 50 trials so 50 would be the genuine limit, but I know a lot of other scientists use the reversals as the limit and don't care that they have diffferent lenghs for each run.

I guess we try to make more clear in the demo why this is the case (in less text than I've just written!?) ;-)

Thanks again for pointing it out

**Comment by hoechenberger** [comment]
This is actually a bug.

In `__init__()`, we do:
```python
        if nReversals is not None and len(self.stepSizes) > nReversals:
            logging.warn(
                "Increasing number of minimum required reversals to "
                "the number of step sizes (%i)." % len(self.stepSizes)
            )
            self.nReversals = len(self.stepSizes)
        else:
            self.nReversals = nReversals
```
https://github.com/psychopy/psychopy/blob/a6549c0fa3230386cecad0a2d6bb7481b1152c0f/psychopy/data.py#L2939

By default, `nReversals` is `None`. So when we execute the tutorial code, we will do
```python
        if (len(self.reversalIntensities) >= self.nReversals and
                len(self.intensities) >= self.nTrials):
            self.finished = True
```
after adding a response. (https://github.com/psychopy/psychopy/blob/a6549c0fa3230386cecad0a2d6bb7481b1152c0f/psychopy/data.py#L3091)

And we'll assume to be "finished", in error:
```python
len(self.reversalIntensities)
Out[6]: 
0
print(len(self.reversalIntensities))
0
print(self.nReversals)
None
len(self.reversalIntensities) >= self.nReversals
Out[9]: 
True
```
