### ISSUE TITLE
TextStim does not show if height is above some threshold (psychopy >= 1.85.0, Windows 10, Windows8, Windows 7, Linux Mint 18.1)

### ISSUE THREAD

**Issue by mmagnuski** [psychopy/psychopy#1385]
TextStim with size 0.24 (in norm units) is shown but TextStim with size 0.25 (or any above) is invisible.
see example:

```python
from psychopy import visual, event

window = visual.Window(monitor='testMonitor')
text1 = visual.TextStim(window, height=0.24, text='1')
text2 = visual.TextStim(window, height=0.25, text='2')

for txt in [text1, text2]:
    txt.draw()
    window.flip()
    event.waitKeys()
```

first text is shown on the screen, the second is not. Looks like a bug to me, unless I am unaware of some limit on height or something else?

**Comment by mmagnuski** [comment]
If window units are in pixels I can draw TextStim up to 100 pixels in height. Anything above that does not get shown.

**Comment by piotx** [comment]
Similar problem applies to psychopy 1.85.1

OS: Windows 7 and Windows 8

The text stimulus is not displayed, if height is set to 0.2 or 0.15 in fullscreen mode; The text is diplayed properly, if height is set to 0.1

minimal example:

```python
from psychopy import visual, core, event

win = visual.Window(fullscr=True)
// same problem with: win = visual.Window(size=(1920, 1080), fullscr=False)

o = visual.TextStim(win, text='o', pos=(0,0), height=0.2)

while True:
    if event.getKeys(keyList=["escape"]):
        core.quit()
    o.draw()
    win.flip()
```

is there any workaround to increase text size?

**Comment by gitfortat** [comment]
Having the same problem on Win7 with 1.85.1. I thought of using TextBox instead, but this does not work either because of the FreeType fonts. No problems with the height in version 1.84.2, so I'll stick with this one.

**Comment by peircej** [comment]
Could we just confirm that the problem is in the PsychoPy code, rather than the dependencies: could you run the code with the additional lines at the top of your script:
```
import psychopy
psychopy.useVersion('1.84.2')
```
That will switch to using a different version of psychopy but using the same dependencies (pyglet etc). I'm not finding the problem on a mac at the moment but I have seen it on a windows machine with a high-res (retina) display.

**Comment by gitfortat** [comment]
For me useVersion('1.84.2') still does not draw the stimulus (with a fresh install of version 1.85.2), so it must be the dependencies. Windows is running in virtualbox and I am not using a high-res retina display. Problem occurs on another normal windows machine as well.

**Comment by D3njo** [comment]
When I updated from version 1.83.04 to 1.85.2 the same problem occurred to me (on Windows 10).

I fixed the bug by updating the pyglet version from 1.2.4 to 1.3.0b1 with PyCharm.

I hope updating pyglet works for you guys too. ;-)

**Comment by peircej** [comment]
Thanks for the info Dennis. Nice to hear a solution (I did have a suspicion that this was a pyglet issue not ours because we haven't changed the relevant code recently). Also nice to learn that pyCharm can recommend/update installed packages. It's so clever that pycharm! :-)

**Comment by D3njo** [comment]
I just installed the new 1.85.3 release (Windows standalone version) and unfortunately the pyglet version is still 1.2.4 and not 1.3.0b1 as described in the release informations. Could you please fix this Jon?

**Comment by peircej** [comment]
Ach, dang! You're right. Not sure how that happened (maybe pyglet update hadn't finished installing before I started the build). Rebuilding the release now.

**Comment by peircej** [comment]
OK, I've uploaded a new one:
https://github.com/psychopy/psychopy/releases/download/1.85.3/StandalonePsychoPy-1.85.3b-win32.exe

Could you try that? cheers

**Comment by D3njo** [comment]
Thanks for fixing this so quickly! I've just tried the new version and everything works perfectly ;-)

**Comment by minaesfandiary** [comment]
hi
Im using psychopy for a self paced experiment in multilinguals…because i use Persian language i should reshape it and enter it in excell app…but because the sentences are not equal in determiners…the psychopy show an default text…i want to dont show this part.
foe example:4 determiners in persian language and 5 determiners in english language…then we have question…between persian language and question…psychopy show a defualt text…what should i do to solve this problem?
if anybody van help me…
im waiting for ur answer
thank u

the boy buy the key do boy buy the key?
خرید پسر کلید را do boy buy the key?

**Comment by mmagnuski** [comment]
If this is fixed, the issue could be closed. :)
