### ISSUE TITLE
attributeSetter for non-visual and non-time-critical operations, example: event.Mouse

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1401]
For accessing and setting attributes of visual stimuli, @lindeloev implemented the `attributeSetter`, which, if I recall correctly, functions much faster than `@property` / `@x.setter`. I was wondering if the `attributeSetter` should be used for _all_ properties throughout the code base, or whether it's okay to limit its use to time-critical events (e.g. setting attributes of visual stimuli, as the user may want to change properties of dozens of stimuli between display refreshs). I'm asking because using the `attributeSetter` feels a bit more awkward / complicated than simply using an "ordinary" property.

Specifically, I would like to add some properties to `event.Mouse`:
- `Mouse.pos` (get & set; currently: `Mouse.getPos()`, `Mouse.setPos()`)
- `Mouse.moveTime` (get only; currently: `Mouse.mouseMoveTime()`)
- `Mouse.relPos` (get only; currently: `Mouse.getRel()`)
- `Mouse.relWheel` (get only; currently: `Mouse.getWheelRel()`)
- `Mouse.visible` (get & set; currently: `Mouse.getVisible()`, `Mouse.setVisible()`)
- `Mouse.exclusive` (get & set; currently only `Mouse.setExclusive()`)

I think it's safe to assume that these operations are not as time-critical as manipulations of stimulus material, so using "ordinary" properties should be fine?

Note also that the proposed property names do not always perfectly correspond to their current respective getter / setter method names (e.g. `Mouse.moveTime` vs `Mouse.mouseMoveTime()`) to make this part of the API more consistent; do you think this is a feasible approach, as the methods will not go away, so backward-compat will be ensured?

There's 2 methods I am currently a bit unsure about:
`mouseMoved(self, distance=None, reset=False)` and `getPressed(self, getTime=False)`. We _could_ expose respective properties for these methods with their default arguments -- IMHO this would make perfect sense; then again, it might be confusing since there would be more than one way to get the same result, which kind of violates the Zen of Python. What do you think?

**Comment by lindeloev** [comment]
First of all, it should come as no surprise that I am extremely sympathetical to the addition to the API you propose here ;-) I originally wanted to bring the attributeSetter change to the full psychopy package, but just stopped for time when finishing the `visual` module and wondering whether it made sense for the `sound` module which was also undergoing heavy changes due to just transitioning to `pyo`. So there's no particular reason that it's visual-only.

It's not uncommon (for me at least) to poll the mouse for presses or position in a tight loop whereas I wouldn't do that for visual stimuli. So I think that comparatively, the performance case for using `@property` for mouse could be worse. But in a more absolute frame of reference, the performance hit is extremely small anyway, so it wouldn't make a practical difference. My personal preference of evading the getter was probably more a sense of cleanness (also the automatic logging) while others were more convinced about performance. I'm not too familiar with @property, but I could probably be convinced if it's much more readable to the outside programmer than the `@attributeSetter`.

Similarly, I want to raise a question that you more python-envolved people could have a better grasp on than I do: isn't it confusing that an attribute/property like `mouse.pos` changes "by itself"? Again: if it's common to see that in python, I'm convinced. Until now, the "does it change by itself" criterion is what I've used to distinguish between exposing things as methods or attributes.

**Comment by peircej** [comment]
I'm fine with it, with the proviso that the `getPos()` attributes are not removed. The performance hit is indeed tiny and I like the elegance of the code in most cases. The issue I have with it is just that other args (e.g. log=True, units='deg') can't be controlled within the call. So any set/get with more than one arg is less powerful with the new syntax.
(Also this is not something that users care about; they'd rather we improve timing and work on bug fixes)
