### ISSUE TITLE
QuestPlus staircase

### ISSUE THREAD

**Issue by janfreyberg** [psychopy/psychopy#1404]
This was first proposed on isse #1005 

I thought it would be a good idea to open an issue so we can add some resources we find online, and to discuss the proposed new class.

**Comment by janfreyberg** [comment]
The paper:

http://jov.arvojournals.org/article.aspx?articleid=2611972#156961837

**Comment by janfreyberg** [comment]
An implementation in MATLAB:

http://www.ucl.ac.uk/~smgxprj/misc/QuestPlus.m

**Comment by janfreyberg** [comment]
@hoechenberger do you want to make a branch on this repository, or work in a fork for this?

**Comment by hoechenberger** [comment]
@janfreyberg doesn't really matter to me, as I will be creating several branches of my own during the development anyway ;) If you want to start with a new branch, go aead and I'll submit PRs. -- But I'd like to discuss some implementation details before we actually get started, didn't have the time to do that so far. Probably won't happen until tomorrow evening... Would be great if you could wait until then? :)

**Comment by janfreyberg** [comment]
Yep, that sounds good!

Also, thanks for splitting up `data.py` - very helpful ;)

**Comment by hoechenberger** [comment]
> Also, thanks for splitting up data.py - very helpful ;)

Haha yes, makes navigation a lot easier eh ;)

**Comment by mmagnuski** [comment]
hi, I needed quest plus for the experiment I am running - I've implemented it yesterday in python and so far it is running very well. I've only tested with simulated weibull but I used the matlab code posted in this issue and looked into trial by trial diagnostic plots of posterior distribution and expected entropy for my python implementation - so I'm quite confident it works as expected. My current implementation is [here](https://github.com/mmagnuski/exp_CircStim/blob/master/weibull.py#L162) but if you like I can turn it into psychopy handler compatible PR.

**Comment by mmagnuski** [comment]
(btw - my implementation does not include prior and simplifies stimulus parameters etc. - but can be extended easily)

**Comment by hoechenberger** [comment]
Thanks @mmagnuski. Haven't tried your code so far, but may certainly use it as a reference.
However, I've started to work on a more "general" approach, which includes support for different psychometric functions and output parameters, see
https://github.com/psychopy/psychopy/compare/master...hoechenberger:quest+?expand=1

Still in an early stage and the algorithm itself hasn't been implemented so far ;) Priors also still missing. But I believe this could be a viable approach. @janfreyberg, could you take a look and let me know what you think? We should maybe meet up in gitter and discuss how to best proceed / coordinate our efforts! I'll be available most of Saturday and Sunday. Let's get in touch via email? :)

Working example:
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import division, print_function

import numpy as np
from psychopy.data.quest_plus import QuestPlus

qp = QuestPlus(func='Weibull',
               func_params=dict(threshold=np.linspace(-10, 10, num=10),
                                slope=[3],
                                guess=[0.5],
                                lapse=np.linspace(0.1, 0.2, num=2)),
               stim_params=dict(c=np.linspace(0, 20, num=21)),
               output_params=dict(success=[0, 1]))

print(qp)
print(repr(qp))

print(qp
      ._likelihood
      .sel(slope=3, success=1, lapse=0.2, c=1, guess=0.5))
```
Output:
```python
/Users/hoechenberger/anaconda3/envs/psychopy-dev/bin/pythonw /Users/hoechenberger/Development/psychopy/psychopy/data/qp_test.py
<QuestPlus : Estimating 4 parameters of a Weibull function.>
<QuestPlus : 
	Psychometric function: Weibull

	Function parameter space:
		slope: 1 values
		threshold: 10 values
		lapse: 2 values
		guess: 1 values

	Stimulus parameter space:
		c: 21 values

	Output parameter space:
		success: 2 values
>
<xarray.DataArray (threshold: 10)>
array([ 0.5     ,  0.5     ,  0.50002 ,  0.503445,  0.53773 ,  0.614598,
        0.691924,  0.743825,  0.772475,  0.786894])
Coordinates:
    slope      int64 3
  * threshold  (threshold) float64 -10.0 -7.778 -5.556 -3.333 -1.111 1.111 ...
    lapse      float64 0.2
    guess      float64 0.5
    c          float64 1.0
    success    int64 1

Process finished with exit code 0
```
I'm using [xarray](http://xarray.pydata.org/en/stable/) to allow for fast handling of multidimensional data with labeled dimensions. This will make the code much more readable. New psychometric functions can easily be added at the class level, e.g
```python
    _func_mapping.add(
        'Weibull', func=_weibull,
        stim_params=('c',),
        func_params=('threshold', 'slope', 'guess', 'lapse'),
        output_params=('success',))
```
The names of those parameter spaces will then be used to label the dimensions of the data grid; specification of individual values / ranges for each parameter will be enforced when trying to use `QuestPlus` with the respective psychometric function:
```python
In[4]: qp = QuestPlus(func='Weibull',
  ...:                func_params=dict(threshold=np.linspace(-10, 10, num=10),
  ...:                                 lapse=np.linspace(0.1, 0.2, num=2)),
  ...:                stim_params=dict(c=np.linspace(0, 20, num=21)),
  ...:                output_params=dict(success=[0, 1]))
Traceback (most recent call last):
  File "/Users/hoechenberger/anaconda3/envs/psychopy-dev/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-269ca0530557>", line 5, in <module>
    output_params=dict(success=[0, 1]))
  File "/Users/hoechenberger/Development/psychopy/psychopy/data/quest_plus.py", line 70, in __init__
    self._check_args(func, func_params, stim_params, output_params)
  File "/Users/hoechenberger/Development/psychopy/psychopy/data/quest_plus.py", line 135, in _check_args
    raise ValueError(msg)
ValueError: The Weibull psychometric function requires the following arguments: ('threshold', 'slope', 'guess', 'lapse')
```
Next step would be, obviously, to implement the actual algorithm and tests, and to eventually package this into a `StairHandler`.

**Comment by hoechenberger** [comment]
btw IMHO the Weibull function definition in the paper is incorrect, and I fixed that in my code.

**Comment by mmagnuski** [comment]
Ok, good you're working on this. :) To get the general quest plus you'd need to change only about 2-3 lines in the code I posted, I didn't bother to change it myself because I don't need more than one stim param and two responses. But I understand by what you mean by general here (providing multiple ready psychometric functions etc.). 
I like xarray but I'm not sure if making it a hard dependency for psychopy (or even just psychopy's implementation of questplus) is a good idea.

**Comment by hoechenberger** [comment]
Hi @mmagnuski, thanks for sharing your thoughts! Do you have any comments on the "API draft" in general? :)

> I like xarray but I'm not sure if making it a hard dependency for psychopy (or even just psychopy's implementation of questplus) is a good idea.

Mh, do you think that would be such a big problem? After all, PsychoPy already depends on pandas, which is a core requirement of xarray (additionally to that netCDF stuff, which is rather small). Since we're dealing with more or less arbitrary shaped data here, I believe labeled dimensions are vital at least during development to make understanding of the code easier. I always had big trouble keeping track of which dimensions corresponds to which values in NumPy arrays (aside from the requirement the sometimes insert "fake" dimensions to execute certain operations)... But maybe that's just me? ;)

**Comment by mmagnuski** [comment]
It's just that I don't see much added value to internally store posterior probabilities and likelihoods as xarrays. 
The easiest way to have the general quest plus that works irrespective of number of stim params, number of function params and number of possible responses is to have each of these as a single dimension. This way likelihoods are in `stim_params x model_params x responses` array and posterior probability is just one vector. Therefore each of the dimensions in likelihoods array is a combination of all "lower" dimensions it holds - that is for model parameters it is as if you unrolled the full model parameters matrix via `.ravel()` (in my case I am using a simple function `reformat_params` that combines all model parametes dimensions - it is [here](https://github.com/mmagnuski/exp_CircStim/blob/master/utils.py#L90)). To have an easy acess to what parameter combination each element in the unrolled array corresponds to you can for example store `n_combinations x n_params` array. This way it all works smoothly irrespective of number of params and thus you don't need N-dimensional arrays and all the labels. This is at least what I found easy and the matlab code also follows that logic. I can't really tell about the mathematica code in the original publication - I have no experience with mathematica and the code in the quest plus paper looks pretty criptic...
You could of course expose a method that puts these unrolled dimensions back to its original shape (I hold original shape of stimulus params in `_stim_orig_shape` for example) and returns as an xarray. But that forces the user to use xarray, so I think it would be better to have the returned type optional (for example `output='xarray'` but the default would be numpy).

I'll try to comment on the API draft later.

**Comment by hoechenberger** [comment]
I see what you mean :) However, "magic" like this is actually exactly what I was trying to avoid here... Esp. since you have to insert "`newaxes`" it many places, I always found that counter-intuitive and error-prone. But like I said, maybe that's just me. I'll think some more about it :)

**Comment by hoechenberger** [comment]
> I'll try to comment on the API draft later.

Any feedback would be greatly appreciated, sine there's so many different possible approaches -- really hard to pick one without having a thorough discussion / exchange of ideas!

**Comment by mmagnuski** [comment]
> However, "magic" like this is actually exactly what I was trying to avoid here... Esp. since you have to insert "newaxes" at many places -- I always found that counter-intuitive and error-prone. 

I agree that it is not straightforward, but implementation-wise it is very easy/simple. `np.newaxis` is actually used only in one line - but this is something you would have to do (in plain numpy) to broadcast well because posterior array will always be smaller than likelihoods. Comparing this to matlab's `bsxfun` I think it is rather intuitive :)

When it comes to your proposed API I think it is nice - looks intuitive. I would maybe rename `output_params` to `response_params` but that's a nitpick. :) I also wouldn't limit users to what gets added to `_PsychometricFunctionMapping` but allow to pass their own functions.

**Comment by domstoppable** [comment]
It's awesome to see this effort having already been started. I'm looking to use Quest+ for quickly estimating contrast sensitivity. It looks like this is maybe incomplete or stalled? What contributions are still needed for this to be usable?

**Comment by hoechenberger** [comment]
Hi @domstoppable, yes, it's stalled — my bad, I'm afraid! BUT today I gave a project report on some threshold estimation procedures I had conducted last year, and since this afternoon Quest+ is back on my agenda. I was planning to start looking into this in the course of next week (and also check which parts have been implemented already, I honestly don't remember :)) Shall we stay in touch, would you like to help testing and / or coding? 

Best wishes, 
Richard

**Comment by domstoppable** [comment]
What lucky timing!

I would be very happy to help with testing and coding as far as I am able to. I'm new to PsychoPy, so maybe keep your expectations not-so-high!

If it's easier to communicate over email, please feel free to contact me at dom@greenlightgo.org. I'm eager to contribute my efforts and see something working.

**Comment by mmagnuski** [comment]
Since we last spoke in this thread I have sucessfully used my Q+ implementation in various contexts including one complex experiment. I am planning to release it as a small package in a few weeks.
If you would like to check if the code works for you it is here: [link](https://github.com/mmagnuski/exp_CircStim/blob/master/weibull.py#L184)

Below some visualisations (the first one does not show the entropy for next contrast because `next_contrast` method has not been called yet):
<img src=https://user-images.githubusercontent.com/8452354/36934816-75c3f9b6-1eef-11e8-86ff-7a9a197b6a55.png width='500pix'>

<img src=https://user-images.githubusercontent.com/8452354/36934834-c39796ac-1eef-11e8-9b32-d88fa0c030f0.png width='500pix'>

**Comment by kdesimone** [comment]
Was there any news on release of the small Q+ package?

**Comment by hoechenberger** [comment]
@kdesimone There is @mmagnuski‘s package, mentioned in the comment above. And I‘ve also created a small package, which can be found at https://github.com/hoechenberger/questplus
In fact, I have been working on PsychoPy integration today, and I hope to be finished this Friday (QuestPlusHandler is finished; currently working on MultiStairHandler integration; after that, will work on Builder integration). Should be available for testing very soon — will most likely file a Pull Request by the end of this week.

**Comment by kdesimone** [comment]
Stellar! Thank you for the detailed response and, of course, all the hard work!

**Comment by hoechenberger** [comment]
@kdesimone What would be your intended use case? There’s still time to adjust the API, you know ;)

**Comment by kdesimone** [comment]
I'm working on a flicker fusion experiment. Looking at things as they are, it seems pretty straightforward to me. I'm going to muck around with it now, will let you know if I have any user-oriented suggestions/questions. Thanks again!

**Comment by hoechenberger** [comment]
Cool. Drop any questions in the project’s issue tracker then, please :)

**Comment by hoechenberger** [comment]
I also just realized there’s currently no demo script in the repo. Will probably add that tomorrow.

**Comment by kdesimone** [comment]
Yes I did notice that actually, but your README.md is quite detailed. A
demo wouldn't here though ;)

**Comment by hoechenberger** [comment]
I do have a demo script that also creates some figures etc. Will add this tomorrow

**Comment by hoechenberger** [comment]
> I do have a demo script that also creates some figures etc. Will add this tomorrow

Sorry, too much stuff going on here ATM. Will either do it later today or … well, later. :)
