### ISSUE TITLE
1.85.0 does not read float values from the Excel file

### ISSUE THREAD

**Issue by ahmezon** [psychopy/psychopy#1418]
My experimental paradigm involves asking participants to identify differences between mirror-flipped images at the top and the bottom of the screen. I recorded the locations of the differences, then entered them into the excel file for each pair. By drawing a rectangle around each location, Psychopy can identify whether the clicked location is within that rectangle. This method worked perfectly for 1.84.2 version, however, upon updating to version 1.85.0 and beyond, I got a message telling me that the entered value can not be changed into a float. I think this is a bug that needs to be fixed as Psychopy recognizes them as a string. Hopefully, my description was clear. 

Below is a picture of the message in the output window

![1 85 1 issue](https://cloud.githubusercontent.com/assets/28864996/26309825/79c5796a-3ef6-11e7-92dd-e6850c27b79b.png)

**Comment by peircej** [comment]
Although you *intend* it to be used as a number, the value you've provided contains parentheses, commas, spaces and periods. It's hard for Python/PsychoPy to be certain from such a format that you intend it to be a number. Note that Excel interprets this as a string and a csv file would interpret this as a string.

For now you'll need to create a column for `corrW` and `corrH` rather than a single one for `corrSize`. Then you can set your size value to be:

  $(corrW, corrH)

**Comment by mmagnuski** [comment]
If I remember correctly setting positions from excel using `[` instead of `(` works well.

**Comment by lindeloev** [comment]
@peircej is right. Another solution is to make python interpret the cell contents as python code, so `$eval(corrSize)` should work with your current data file layout. But in general, `eval` and `exec` are to be avoided if possible.
