### ISSUE TITLE
note; source code tarballs aren't "complete" any longer since submodules (psychojs) aren't included

### ISSUE THREAD

**Issue by yarikoptic** [psychopy/psychopy#1451]
I don't know if that is possible (do not see anything to state that .gitattributes could be instructed to export submodules as well)

**Comment by peircej** [comment]
Right, yes. On my own distribution I'm now zipping the psychojs package during my build process and putting it inside the python package as a datafile. I'm still slightly questioning the wisdom of separating them at all, but it was a suggestion from a user that did seem sensible in a way

Source distributions built by setuptools can still have the file added, but not files that are built automagically by github as part of the tagging/releasing process there.

**Comment by csteacherd22** [comment]
What's the recommended work around?

**Comment by peircej** [comment]
Oh, I'll have to fix that but you can just download the psychojs library, zip it up and drag it into the root of the psychopy folder?

**Comment by peircej** [comment]
I've checked that psychojs is included in the zip files that I build so my build scripts are working fine. Maybe you're talking about the github-generated source zip files? I can imagine those don't include psychojs but I don't think I can alter those. 
In the future this is going to disappear as an issue altogher because we'll be pointing to psychojs releases online rather than making any attempt to package them. I'm closing for now

**Comment by peircej** [comment]
OK, I worked out what was going on here and fixed it in #1708 and then made it neater in #1709

The issue was that the setup.py script was trying (unnecessarily) to rebuild the psychojs.zip file whereas now it (correctly) either uses the existing zip OR builds it.
