### ISSUE TITLE
Support for Tobii Pro SDK?

### ISSUE THREAD

**Issue by j-duff** [psychopy/psychopy#1467]
I'm designing (my first) simple 'eye-tracking while watching video' experiment for a Tobii TX300 on a computer running Windows 7, with Python 2.7.

Things have been going smoothly until I completely ran into a wall: Tobii discontinued the Tobii Analytics 3.0 SDK, which is what the [iohub Tobii materials](https://github.com/psychopy/psychopy/tree/master/psychopy/iohub/devices/eyetracker/hw/tobii) are made to interact with. The replacement, the "Tobii Pro SDK" has [very little of the same structure](http://developer.tobiipro.com/python/python-oldmigrationsdk.html), and they've removed all options for downloading the older versions.

Are there plans to adapt iohub to work within the new framework? Otherwise, it's sadly made un-modded PsychoPy/iohub a completely inaccessible option for anyone just getting started, which is a real pity, since it seems to really be the best option out there... Unless someone is maintaining a version of the old Tobii Analytics 3.0 SDK somewhere?

**Comment by j-duff** [comment]
A few hours of research later, seems like the only team to have begun migrating to the Tobii Pro SDK is PyGaze/OpenSesame, [as of a few days ago](https://github.com/esdalmaijer/PyGaze/issues/98)! Of course, it hasn't been completed yet, but in the meantime, [this inline code example](https://github.com/alisdt/tobii-pro-sdk-opensesame-example) by alisdt can be adjusted for use in OpenSesame, if anyone else finds themselves in this difficult position.

**Comment by peircej** [comment]
I'm not sure when we'll update the iohub (it's Sol's baby and he hasn't got much time at the moment) but there are several options:
 - use the tobii pro sdk (which has python wrappers) directly. Looking at the docs it doesn't look too hard: 
  - http://developer.tobiipro.com/python/python-getting-started.html
  - http://developer.tobiipro.com/python/python-sdk-reference-guide.html
 - use Sogo Hiroyuki's tobii controller for PsychoPy https://github.com/hsogo/psychopy_tobii_controller which I assume is using Pro SDK

best wishes, 
Jon

**Comment by peircej** [comment]
@hsogo could you confirm which SDK your controller uses?

**Comment by hsogo** [comment]
Yes, my tobii_controller users Tobii Pro SDK.

**Comment by grebdems** [comment]
Hi! 
Magnus from the Tobii Pro SDK team here.
Didn't see this one until today (to be fair, I _am_ on vacation...)

Sorry that you got stuck because you couldn't find the "Analytics SDK" any longer, @j-duff ! 
IMHO we should have kept it on the site, but with a big "deprecated" text. 
IF you still need it, contact our support (https://www.tobiipro.com/contact/support/) and they should be able to give you the last (deprecated) version.

We _are_ looking into adding some support for OSS frameworks into Tobii Pro SDK (or is it the other way around?) right now. Hence the PyGaze work.
Haven't gotten around to properly assess how to best do it for PsychoPy/IOHub yet, unfortunately.
Any pointers are much welcome! ;-)
Should the support for Tobii Pro SDK deprecate the support for the old Analytics SDK, or should they live side by side? Maybe allowing for selecting which one to use (setting/args)? Or chosen depending on installation base (if import of tobii_research fails, try the old...)?

/M

**Comment by peircej** [comment]
Just been alerted (on the psychopy forum) to the existence of another such toolkit/wrapper here:
https://github.com/oguayasa/tobii_pro_wrapper/blob/master/tobii_pro_wrapper/tobii_pro_wrapper.py

by @oguayasa
So there are several options around but, yes, ultimately it would be great to move these into iohub for the sake of having a unified API across different eyetrackers

**Comment by janfreyberg** [comment]
It could also be a nice idea to have a list of external packages for eye trackers or other devices somewhere in the docs.

**Comment by hoechenberger** [comment]
@janfreyberg PRs welcome ;)

**Comment by janfreyberg** [comment]
Although it would be good to know if that's actually wanted - since they don't integrate into builder and wouldn't be supported particularly well by the psychopy forum community, is it a good idea to list them on the psychopy website?

I think so, especially if we display a prominent disclaimer about them. But maybe others have a different opinion?

**Comment by peircej** [comment]
Yes, I think so too. Some people my not be aware that they can use a certain eyetracker  (or other device), even though we don't provide built-in support. I think we could even provide a table listing devices supported by:

  - ioHub
  - pygaze (which I could also package I think)
  - 3rd party libs (like the 2 that i know of for Tobii)
  - manufacturer libs

**Comment by janfreyberg** [comment]
Sounds like a good plan. I will take a look at creating one of these later.

**Comment by mdcutone** [comment]
@isolver Is this something that has been dealt with in iohub?

**Comment by isolver** [comment]
Yes, iohub is now using (since early 2019 I think) the tobii-research package.
