### ISSUE TITLE
Adding a .pth file to the python2.7 folder on Mac is not working

### ISSUE THREAD

**Issue by astralcai** [psychopy/psychopy#1503]
I'm trying to import a package I wrote myself in the PsychoPy Coder view, and I created a file called my_path.pth, with the file path to my package folder in it. I placed it under "/Applications/PsychoPy2/Contents/Resrouces/lib/python2.7", but I'm still unable to import my package

**Comment by hoechenberger** [comment]
Hi @astralcai, not really addressing your issue here, but is there any specific reason for you to use the standalone package? If you developed your own package, you seem to be at least an intermediate Python programmer. At this stage, it might be very useful to switch to a "manual" install inside your custom Python environment, which will make many things (like installing packages) much easier.

**Comment by hoechenberger** [comment]
Oh btw, I believe the `.pth` file has to be placed inside the `site-packages` directory.
