### ISSUE TITLE
PsychoPy 1.85.4 doesn't load

### ISSUE THREAD

**Issue by jvcasillas** [psychopy/psychopy#1524]
I just downloaded the newest available download (1.85.4) for mac os x and the following popped up...

<img width="420" alt="captura de pantalla 2017-09-20 a la s 15 24 50" src="https://user-images.githubusercontent.com/1747068/30663280-2609be22-9e18-11e7-9a8a-ad53b453af2c.png">

I am unable to open old experiments or access the builder/coder windows.

**Comment by CRiddler** [comment]
@peircej I can't test this currently. Seems like an issue in something that was bundled up for the 1.85.4 release though- I think we need to comb through the version tags and settle this out. Should be addressed immediately since new users won't be able to use the most recent version.

@jvcasillas switch back to a previous version if you can until we sort this out. Thanks so much for letting us know about this issue.

**Comment by peircej** [comment]
I'm looking into it. Looks like a dependency change in one of the other libs (lib2to3) and not sure why it's now needed and/or why not working. I've removed the 1.85.4 download pending working it out

**Comment by peircej** [comment]
I've uploaded a version 1.85.4b for the mac where this application loading issue is fixed (basically the lib2to3 had to be moved outside the site-packages.zip folder for some reason
