### ISSUE TITLE
Builder: rating scale is broken

### ISSUE THREAD

**Issue by EruIluvatar** [psychopy/psychopy#1545]
Hi

The rating scale element in Builder has some shortcomings (when using as visual analog scale at least):
1. It produces incorrect code if the slider is `glow` and therefor doesn't run.
The resulting code inserts twice the `markerExpansion` keyword.
`
valence_rating = visual.RatingScale(win=win, name='valence_rating', marker=u'glow', markerExpansion=5, size=1.0, pos=[0.0, -0.4], low=0, high=1, precision=100, showValue=False, markerExpansion=0, scale=u'Wie f\xfchlen Sie sich gerade?')
`
2. It ignore the 'low' and 'high' values, eg. defined as 0, 10 (integers) and produces `low=0, high=1` arguments.
3. It ignores the labels. Eg. 'negativ', 'positiv' also results in `low=0, high=1` arguments.

**Comment by CRiddler** [comment]
Hi, sorry for the delayed response but I've found a fix for all of your issues. The marker expansion issue was definitely a bug and will be fixed as soon as I submit a PR for it.

However I think your other issues are worth discussing, as they seemed to be hardcoded very intentionally.  If its a visual analog scale, change low and high to 0 and 1 respectively. Also it purposely ignores any labels you pass if you're using the rating scale as a visual analog scale. Unfortunately I wasn't around when this was initially coded so I'm hesitant to make large feature changes.

@hoechenberger do you know the reason behind hardcoding these values to the VAS from the builder?
https://github.com/psychopy/psychopy/blob/f5c1b5a40dc988721b28935755c74b343ce9cb83/psychopy/app/builder/components/ratingScale/__init__.py#L226

**Comment by jeremygray** [comment]
The markerExpansion duplication is definitely a bug, should be fixed.

The visual analog scale lack of features were intentional. This idea is to be a visual analog (spatial), not symbolic and or quantitative representations (verbal or numerical). Its intended to avoid being a "1 to 10" scale. Using 0-1 as endpoints means that no intermediate tick marks will be drawn on the screen. Similarly, labels are suppressed to avoid having words on-screen. (That was the idea, maybe labels should be allowed?)

Another consideration is that the options in the builder are intentional simplifications. Rating scale is complex, and takes a LOT of options. Part of the intent of the Builder interface is to reduce that flexibility. The customize-everything option is still available for people who want more control -- in fact, anything doable can be done through that option.

**Comment by peircej** [comment]
The reason the 'glow' stopped working was the use of 
```
self.marker = copy.copy(self.markerOrig)
```
An stimulus isn't safe to copy because it makes use of (and/or creates) resources that can't be copied this way. In this case the gaussian texture had been uploaded to the graphics card but had been lost in the copy() replacement
