### ISSUE TITLE
Travis still failing with wxPython 4

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1589]
While @Schubisu improved wxPython 4 compatibility via #1581, the respective Travis build is still [failing](https://travis-ci.org/psychopy/psychopy/jobs/298047586):
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/psychopy-conda/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /feedstock_root/build_artefacts/wxpython_1508963567428/work/wxPython-4.0.0rc1.dev3440+0f9b36e/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/psychopy-conda/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /feedstock_root/build_artefacts/wxpython_1508963567428/work/wxPython-4.0.0rc1.dev3440+0f9b36e/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed
/home/travis/.travis/job_stages: line 57:  8219 Segmentation fault      (core dumped) pytest --cov-config .travis_coveragerc --cov=psychopy -v -s -m "not needs_sound" psychopy
```
I _suspect_ that the test exits the Python interpreter before the wxPython app has properly shut down.

**Comment by peircej** [comment]
It could be that a (Python) error message is being swallowed leaving only this seg fault to be reported. If the app starts, and gets as far as the Coder view being created, this will open the Output window which then starts catching stderror messages (rather than terminal). If something crashes really badly now then the error message gets sent to the Output window but gets lost as that window dies!
Workarounds is to start the app with preference `ShowOutput` set to False so that this panel is not created.

**Comment by peircej** [comment]
Im' not sure which exact change fixed this but it's gone
