### ISSUE TITLE
TrialHandler2 cannot save xlsx

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#1590]
**MWE:**
```python
from psychopy.data import TrialHandler2

conditions = [dict(Foo=i) for i in range(10)]
trials = TrialHandler2(conditions, nReps=1)

for trial in trials:
    pass

trials.saveAsExcel('/tmp/foo')
```
**Output:**
```python
Traceback (most recent call last):
  File "/Users/hoechenberger/Library/Preferences/PyCharm2017.3/scratches/scratch_35.py", line 9, in <module>
    trials.saveAsExcel('/tmp/foo')
  File "/Users/hoechenberger/Development/psychopy/psychopy/data/base.py", line 322, in saveAsExcel
    dataArray = self._createOutputArray(stimOut=stimOut,
AttributeError: 'TrialHandler2' object has no attribute '_createOutputArray'

Process finished with exit code 1
```

**Comment by peircej** [comment]
Yes, this is the remaining known (to me) difference between the two and is why Builder still outputs TrialHandler code instead of version 2 code. The problem is that this form of output was really easy to write for TrialHandler because the data are stored in a 2D array  (conditionsXreps) inherently. For TrialHandler2 the data are initially a 1D array so we'd need to do some conversion first.

**Comment by alokkumary2j** [comment]
I would love to contribute to Psychopy. Would this be an issue which I should work upon?

**Comment by hoechenberger** [comment]
@alokkumary2j Great to hear you're willing to contribute! I haven't really looked into this issue so far, so I'm unsure just how difficult it will be to come up with a proper fix. The easiest intermediate solution, obviously, would be to simply raise a `NotImplrementedError` for the time being ;) There's also a number of issues requiring [low](https://github.com/psychopy/psychopy/labels/effort%20low) or [medium](https://github.com/psychopy/psychopy/labels/effort%20medium) effort, you may want to check these out as well!
