### ISSUE TITLE
missing pyopengl dependency

### ISSUE THREAD

**Issue by djmannion** [psychopy/psychopy#1705]
Installation via pip or ```setup.py``` (1.90.0-dev1) does not install PyOpenGL, which is required by ```windowwarp.py```.

Might just need adding to the ```required``` list in ```setup.py```?

**Comment by peircej** [comment]
I didn't realise that windowwarp strictly requires pyopengl. Most of PsychoPy uses pyglet instead. Then again I'm currently working on a new text renderer and struggling to make that work with pyglet.gl (whereas it works fine with pyopengl) so that might be +1 for PyOpenGL as a strict dependency.

I think @mdcutone will approve of that too! There are a couple of places where pyopengl is nicer (not requiring casting to ctypes pointers bleurgh!)

**Comment by djmannion** [comment]
I'm not sure how strictly it is required - it just came up when trying to get the tests to pass.

The line is:
```python
from OpenGL.arrays import ArrayDatatype as ADT
```

**Comment by peircej** [comment]
I've added that to the dependencies and just pushed 1.90.dev2 to PyPI so hopefully this is fixed (reopen if not)
