### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by AlexeyAM** [psychopy/psychopy#1804]
Using Windows 7
Command:
C:\Users\AM>python -m pip install psychopy

Here is command prompt output (last lines):
               ------------------------
  Using cached https://files.pythonhosted.org/packages/ee/88/1b57f7318b3079b41a5
b4299ae99caedcd00b5f9897dd765c2e553b694c3/moviepy-0.2.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    error in moviepy setup command: 'extras_require' must be a dictionary whose
values are strings or lists of strings containing valid project/version requirem
ent specifiers.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\am\appda
ta\local\temp\pip-install-vmncq4\moviepy\
       -----------------------------

I use the last version of pip (updated just before installation).
What should I do with it?

**Comment by peircej** [comment]
I've never called pip like that. It's usually:

`pip install psychopy`

Not sure if that's the problem, but this is certainly not a psychopy bug, if it's a bug at all. The issue apparently comes when installing moviepy (a dependent package which we don't write)

**Comment by hoechenberger** [comment]
Hi,

> I've never called pip like that.

it's actually a common way to invoke pip, and leads to the [exact same results](https://stackoverflow.com/questions/25749621/whats-the-difference-between-pip-install-and-python-m-pip-install) as calling `pip` directly.

Although we didn't write `moviepy`, I feel we should check why installation fails, otherwise people won't be able to easily install PsychoPy from PyPI. In fact, since the dependencies list in `setup.py` had been massively expanded in 38e87ce62e9dd71aeee9ebb9abd5aa33d8754e4e, I have been unable to `pip install psychopy` on all platforms. I switched to installing only the base dependencies (to generate visual stimuli and to use `data.py`) manually, and then installing PsychoPy via `pip install --no-deps psychopy` so it wouldn't try to pull in dependencies that don't install.

So while the idea behind 38e87ce62e9dd71aeee9ebb9abd5aa33d8754e4e was to make installation easier, it seems to cause more trouble at least to some users. I am wondering if we should go back to only specifying the absolutely necessary dependencies in the `install_requires` list, and add an [`extras_require` section](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) e.g. for different sets of dependencies (e.g., "full", "sound", etc.)

cc @lindeloev @mmagnuski

**Comment by tjwilli58** [comment]
I think pip is basically just a shortcut to python -m pip. You may want to try 
python -m pip install --no-cache-dir

**Comment by peircej** [comment]
I just tried `pip install -U moviepy` on a mac and it worked fine. I've seen similar problem at other times; if a dependent lib is failing to install itself with pip then this is what happens. It's usually short-lived but all we can do is pass the message upstream to the owners of that package

**Comment by AlexeyAM** [comment]
The problem was in moviepy - package, that is being installed with psychopy. This package requires updated setuptools. After I updated setuptools (from v 16 to 39) I could install moviepy separately and then psychopy.

**Comment by sadeabiodun** [comment]
i'm on a Mac 11.6 trying to install psychopy3 using pip install psychopy with python 3.8.13 inside a fresh conda environment (conda 4.12.0, pip 22.1.2) and I’m getting this error. (I also tried installing the most recent standalone package for Mac, but psychopy crashes immediately after displaying the splash window.) Any idea what might be going wrong?
````
pip install git+https://github.com/psychopy/psychopy.git

Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/zj/tlwtxx0j0qsgx8p8pkmnlgdr0000gq/T/pip-install-gs62ny_h/wxpython_721d30261ae2414eaef73e2cc689e0eb/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/private/var/folders/zj/tlwtxx0j0qsgx8p8pkmnlgdr0000gq/T/pip-install-gs62ny_h/wxpython_721d30261ae2414eaef73e2cc689e0eb/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`
```
