### ISSUE TITLE
Psychopy2_PY3 cannot load inpout32.dll

### ISSUE THREAD

**Issue by stfnrpplngr** [psychopy/psychopy#1809]
Hi,

trying to run my experiment using the `Psychopy2_PY3` version, it fails importing `psychopy.parallel`. It seems like it cannot load the inpout32.dll giving the following error message:

`OSError: [WinError 193] %1 is not a valid Win32 application`

The error occurs running  [`__init__.py`](https://github.com/psychopy/psychopy/blob/master/psychopy/parallel/__init__.py) of the parallel module at lines 38-42:
```
elif sys.platform == 'win32':
    from ctypes import windll
    if hasattr(windll, 'inpout32'):
        from ._inpout32 import PParallelInpOut32
        ParallelPort = PParallelInpOut32
```

As is being described [here](https://discourse.psychopy.org/t/cannot-send-a-signal-via-parallelport-using-psychopy-on-windows7-64bit/969), I saved the `inpout32.dll` in the directory of the executable file.
I tried loading the file with `ctypes.cdll.LoadLibrary()` referring directly to the `inpout32.dll` getting the same error as above.

What do you think?

PS: I found [this comment](https://hynek.me/articles/hasattr/) advising against the use of `hasattr()`.
____
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
IPython 6.1.0 -- An enhanced Interactive Python.
Spyder 3.2.8
PsychoPy-1.90.1-py3.6

**Comment by peircej** [comment]
I'm not sure if this is a problem with Python3 per se or with the fact that you're using a 64bit python. To use 64bit python you will need the 64bit version of inpout32. (Using 32bit libs on 64bit platforms is fine, but all the libs need to match so you can't have 64bit python with a 32bit dll).

Could you:

 - try using the Standalone PsychoP3 (which is the 32bit version) instead of Anaconda?
 - try installing a 64bit parallel port driver?

> PS: I found this comment advising against the use of hasattr().

`hasattr` is just easier in this line of code and we know the object that we're getting so it's fine.

**Comment by stfnrpplngr** [comment]
Yes, you are right. I could start the experiment in the standalalone version.
Now, I try to get make it run with the `inpoutx64.dll`.

> hasattr is just easier in this line of code and we know the object that we're getting so it's fine.

The whole if construction does not work with `hasattr` because it raises an OSError.

**Comment by peircej** [comment]
@stfnrpplngr are you saying that simply calling windll fails because of `OSError`? Are there further lines to this error message that you weren't showing us?

**Comment by stfnrpplngr** [comment]
After merging PR #1812 supporting x64 parallel port driver, the Issue can be closed.
