### ISSUE TITLE
Make TextureMixin._createTexture() a static method

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#1864]
Hello,

TextureMixin._createTexture() has a pretty robust texture creation routine. Making it a static method should make it more accessible when one wishes to load textures into video memory without creating a new ImageStim instance.  

It should ultimately return the OpenGL reference ID which one can use to reference the texture later.

**Comment by peircej** [comment]
Yes, I think this would be possible. In fact it has, at times, been a separate function, not attached to any class at all. It sometimes needed access to various parameters about the stimulus but I think those are all now passed as args anyway.
There is also potential to improve the performance further (e.g. by keeping textures as L rather than RGBA when possible and suchlike) but that needs a lot of testing to make sure that other uses of the texture aren't being broken.

**Comment by mdcutone** [comment]
We could make a 'texture' class which stores IDs and deletes them automatically when the class is garbage collected.

**Comment by mdcutone** [comment]
This can be done with the new `gltools.createTexImage2D` function. An example on how to load images from file to video memory is in that function's documentation.
