### ISSUE TITLE
Replace PySoundCard with SoundCard

### ISSUE THREAD

**Issue by toddrjen** [psychopy/psychopy#1924]
It looks like [PySoundCard](https://github.com/bastibe/PySoundCard) hasn't been updated upstream in 3 years.  The same developer, however, has a newer, better-maintained alternative called [SoundCard](https://github.com/bastibe/SoundCard).  It might make sense to switch over to that.

**Comment by peircej** [comment]
Thanks for the heads-up. Very interesting. 

I had switched to [SoundDevice](https://github.com/spatialaudio/python-sounddevice) due to the fact that it looked better supported and had the same design concepts as PySoundCard (developed  by the number 2 contributor to PySoundDevice). I have effectively considered PySoundCard deprecated in PsychoPy for some time.

But yes, SoundCard looks very interesting too. In particular, it looks like it's plugging directly into the platform-specific sound libraries, which is almost unique. Most other libs are using portaudio as an intermediary to handle the cross-platform support but that means:

- relying on an additional compiled lib that has to be supplied (whereas this new project is pure python, connecting to libs directly in the OS)
- an additional layer that, in the limit, would necessarily be slower than calling the OS calls directly. Then again some libs, like pyo, are then filling the buffers from a separate compiled lib which has a performance advantage.

## Things we'll need to investigate:

- latency questions. This has the advantage of skipping the portaudio middle-man, but the disadvantage that operating in pure python might not be as fast as filling buffers from a c compiled lib
- channel mixing. portaudio under mac/linux supports multiple streams to be opened with different sampling rates. portaudio under windows does not, so if a user 

## Implementation

In PsychoPy, sound backends are now separated off into separate files, so adding a new one should be easy enough to do

So far, only pyo supports mic recordings and I'd like to add support elsewhere too.

## Other options

We also recently hired Mario Kleiner to port the psychtoolbox (PTB) audio code to python, which he's done and currently testing. So that will be *another* backend for sound. This is another portaudio option so requires compiled libs to be provided but should have very good performance on Mac/linux. Under win32 I believe this relies on ASIO (proprietary) drivers with a less-good fallback to the ASIO4All (free) driver. Then there will be a new question about whether PTB is windows/ASIO4All is better or worse than using SoundCard with WASAPI

So many options/questions!

**Comment by bastibe** [comment]
Hi PsychoPy!

First up, PySoundCard is indeed dead. If you need portaudio bindings, use SoundDevice instead. It is Matthias Geier's much better maintained pseudo-fork of PySoundCard. Alternatively, if you are only going to need sound card access internally, PyAudio is a much more low-level CPython module with portaudio bindings, which is probably somewhat faster than SoundDevice/PySoundCard and probably easier to integrate into a bigger project due to its stricter adherance to portaudio's API.

That said, I wrote SoundCard specifically as a better alternative to all the portaudio bindings out there, because portaudio puts a hard limit on the usefulness of any audio application in that it does not and can not know the true default audio device, adds some additional overhead and buffering between the developer and the sound system, and requires a separate binary to be shipped. Also, it has its own bugs that may or may not get fixed quickly (try opening a sound card with a non-power-of-two number of channels on macOS), and is generally constricted to the semantics of a C library. In that sense, I believe SoundCard's approach to be the only possible solution for a truly great sound card library in Python.

However, I strongly prefer a consistent and simple API to a maximally efficient one. This is why SoundCard uses pulseaudio and WASAPI instead of ALSA and ASIO--which means somewhat higher latencies, but comes installed by default, and it knows of the operating system's default sound cards. Of course, maintaining bindings for three separate C APIs is no doubt a source of bugs, and making sure that all three bindings are identical is a bit of a challenge, too.

As far as latency is concerned, SoundCard is not bad, but it seems like all three audio libraries (pulseaudio, coreaudio, WASAPI) could be configured for lower latencies than SoundCard currently uses. SoundCard uses the APIs "normally", but there seem to be additional configuration options to take "ownership" of a sound card and force the APIs to go into low-latency modes, with some additional configuration burden and probably a chance to trip up other users of the sound card. However, the documentation is extremely vague on these points, and I haven't been able to figure this stuff out (and am not particularly interested in it, either). SoundCard does provide a raw mode for recording, though, where it does not re-buffer anything, but simply returns samples as the APIs produce them. This can cut out some latency, but you will have to deal with variably-sized audio blocks. I also tried to make SoundCard allocate as little memory as possible, which helps with performance (memory allocations being the single biggest performance killer for audio applications).

As for channel mixing, the upside of using the operating systems' default APIs is that it uses the OSs' default mixers as well. You should be able to open many streams with arbitrary sampling rates without any issue. Also, SoundCard uniquely allows you to use channel maps, i.e. play or record only a small subset of channels of a sound card with many channels. This is particularly important for professional sound cards with many channels and Python, where many channels lead to big allocations, and quickly to buffer underruns.

I spent almost a decade on this stuff, and I believe SoundCard's approach to be the only truly viable option. I believe that I have a pretty good handle on what pulseaudio, coreaudio, WASAPI, and portaudio can do, so feel free to ask if you have questions.

**Comment by bastibe** [comment]
What would you need to make SoundCard more useful to you?

**Comment by toddrjen** [comment]
On Sat, Aug 4, 2018 at 3:35 PM, Bastian Bechtold <notifications@github.com>
wrote:

> What would you need to make SoundCard more useful to you?
>

The things we currently need in our lab that don't seem to be handled:

ASIO support
Ability to set the buffer size
The ability to play and record in a single operation.

Besides this, we basically we have three main use-cases:

1. Play and/or record an array and block until it is done.  For example
something like:

>>> arr = card.record(1024)

2. Play and/or record an array and return immediately.  Do some stuff while
the sound is playing.  Once that stuff is done, block until the playback
and/or recording is done.  For example:

>>> card.record(1024)
>>> other_func()
>>> arr = card.block()

3. In a loop, play and/or record a single buffer-length sequence of sound,
keeping a certain numbers of buffers available (usually 3) in the
background.  If the number of buffers in the background goes above that
number, block until one has finished.  Once the loop is done, wait until
all remaining buffers are done.  For example:


>>> for buff in arr.reshape(1024, None):
...     card.play(buff)
...     other_func()
...     card.block_if_n_buffers(3)
>>> card.block()

Looking at the code, it looks like only the first case is handled.

**Comment by bastibe** [comment]
Most of these are already possible in SoundCard:

> Ability to set the buffer size

You  can set a `blocksize` on all player and recorder objects. This controls the amount of buffering done by the backend APIs (to the extend they allow it).

> The ability to play and record in a single operation.

This is not possible in either of the backend APIs. Portaudio allows it, but it is faking it. However, all player/recorder objects on the same soundcard share the same hardware clock, and are always synchronized.

```python
with default_mic.recorder(samplerate=44100) as mic, default_speaker.player(samplerate=44100) as sp:
    while True:
        data = mic.record(numframes=1024)
        sp.play(data)
```

> 1. Play and/or record an array and block until it is done.

This happens automatically if you use the non-context-manager `play`/`record` functions:

```python
sc.default_speaker.play(data, samplerate=48000)
sc.default_microphone.record(numframes=1024, samplerate=48000)
```

> 2. Play and/or record an array and return immediately. Do some stuff while the sound is playing. Once that stuff is done, block until the playback and/or recording is done.

This happens automatically on `__exit__`:

```python
with sc.default_speaker.player(samplerate=48000) as ply:
    play.play(data)
    other_func()
    # __exit__ will wait for pending data to be played
```

> 3. In a loop, play and/or record a single buffer-length sequence of sound, keeping a certain numbers of buffers available (usually 3) in the background.

This happens automatically if you set a `blocksize`:

```python
with sc.default_speaker.player(samplerate=48000, blocksize=1024*3) as ply:
    while True:
        play.play(data[:1024]) # will block if too much data is buffered
        other_func()
```

The only thing SoundCard fundamentally does not support is ASIO, for the above reasons. Also, detailed latency information is currently only available on pulseaudio, but would not be hard to implement on the other APIs.

**Comment by peircej** [comment]
Thanks very much @bastibe ! I completely agree that a package targeting the OS-specific libs directly is the right direction to go in, at least to try. Thanks for driving a library that way. I really like these context methods too, allowing one function to run concurrently and another to block. Really neat. 🥇 Great news that this will remove the channel-mixing restrictions.

We have a saying in England that "the proof of the pudding is in the eating" so I think it's time to put theory aside and measure how SoundDevice compares in terms of measured latency, and making sure that it doesn't fall over when doing other things simultaneously (an OpenGL thread in our case). I suggest we knock up a new backend option to support this and see how it compares.

Regarding ASIO, @toddrjen if that's what you need then I'd suggest just using pyo or, soon, the new Psychtoolbx->python port. In fact, it would be great to find out how those ASIO-portaudio packages compare with WASAPI on a high-spec ASIO-compatible system like yours.

**Comment by toddrjen** [comment]
On Sun, Aug 5, 2018, 11:32 Bastian Bechtold <notifications@github.com>
wrote:

> Most of these are already possible in SoundCard:
>

That is good to hear.  I wasn't able to find it in the documentation.

Ability to set the buffer size
>
> You can set a blocksize on all player and recorder objects. This controls
> the amount of buffering done by the backend APIs (to the extend they allow
> it).
>

That is good to hear, although it looks like that isn't supported on
Windows.

The ability to play and record in a single operation.
>
> This is not possible in either of the backend APIs. Portaudio allows it,
> but it is faking it. However, all player/recorder objects on the same
> soundcard share the same hardware clock, and are always synchronized.
>
> with default_mic.recorder(samplerate=44100) as mic, default_speaker.player(samplerate=44100) as sp:
>     while True:
>         data = mic.record(numframes=1024)
>         sp.play(data)
>
>
That is all the more reason to support professional-oriented APIs like ASIO
and Jack, which as far as I can tell do support simultaneous IO.

The problem is not some much have the playback and recording using the same
clock, but to know what time a playback starts in relation to a recording
so we can line them up in our analysis.



>
>    1. Play and/or record an array and block until it is done.
>
> This happens automatically if you use the non-context-manager play/record
> functions:
>
> sc.default_speaker.play(data, samplerate=48000)
> sc.default_microphone.record(numframes=1024, samplerate=48000)
>
>
Yes, as I said, this is the one I could tell was supported from the
documentation.


>
>    1. Play and/or record an array and return immediately. Do some stuff
>    while the sound is playing. Once that stuff is done, block until the
>    playback and/or recording is done.
>
> This happens automatically on __exit__:
>
> with sc.default_speaker.player(samplerate=48000) as ply:
>     play.play(data)
>     other_func()
>     # __exit__ will wait for pending data to be played
>
>
Is there a way to do that without without having to re-initializing the
player object?


>
>    1. In a loop, play and/or record a single buffer-length sequence of
>    sound, keeping a certain numbers of buffers available (usually 3) in the
>    background.
>
> This happens automatically if you set a blocksize:
>
> with sc.default_speaker.player(samplerate=48000, blocksize=1024*3) as ply:
>     while True:
>         play.play(data[:1024]) # will block if too much data is buffered
>         other_func()
>
>
Is there a way to define how much is "too much data"?


There is also one thing we need that I forgot to mention: some way to check
if there have been buffer underruns.  Depending on the situation we will
either raise a warning or an error.


> The only thing SoundCard fundamentally does not support is ASIO, for the
> above reasons.
>

As I said, that is a perfectly legitimate design decision.  It just renders
SoundCard unusable for us.

**Comment by bastibe** [comment]
> I think it's time to put theory aside and measure how SoundDevice compares in terms of measured latency

I would be very interested in those results, too. I suspect them to vary wildly between sound cards and operating systems.

>> You can set a blocksize on all player and recorder objects. This controls the amount of buffering done by the backend APIs (to the extend they allow it).
> That is good to hear, although it looks like that isn't supported on Windows.

I am sure it is supported (the parameters are clearly there), I just haven't figured out how, yet. This might only be possible for exclusive-mode devices.

> The problem is not some much have the playback and recording using the same clock, but to know what time a playback starts in relation to a recording so we can line them up in our analysis.

Sorry for not expressing this clearly enough. What you want is definitely possible on the same sound card. On the same sound card, both recorder and player use the same clock, and therefore express delays and current playback times (not available in SoundCard ATM, but not hard to implement) in the same time frames.

> Is there a way to do that without without having to re-initializing the player object?

Why? You still have a handle on the sound card object. Think of getting the player object more as a start/stop than a heavyweight object construction.

> Is there a way to define how much is "too much data"?

That's the block size.

> some way to check if there have been buffer underruns

I did look for this in all three APIs, but at least some of them do not seem to record this information. I'm afraid this is just something we have to live with.

> It just renders SoundCard unusable for us.

Fair enough.

**Comment by peircej** [comment]
> > It just renders SoundCard unusable for us.

> Fair enough.

Todd isn't talking here for the PsychoPy project generally, only for his own lab needs. I think SoundCard looks very promising and most of our users do not have genuine ASIO hardware

**Comment by mirh** [comment]
Uh, well.. just for the records every realtek chip has an actual legit [native](https://github.com/psychopy/psychopy/files/3143879/ASIO_v2.4e.zip) [driver](https://forum.cockos.com/showthread.php?t=205623#post1978940). 
I never really benchmarked its latency tho. 

Also [windows 10](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/low-latency-audio#windows-audio-session-api-wasapi) should have some api improvement in this regard

**Comment by peircej** [comment]
Closing this thread as very out of date - PsychoPy does now support psychtoolbox audio engine which includes WASAPI drvier support on windows and we've measured very low-latency audio start with that in our [timing megastudy](https://peerj.com/articles/9414/) including onset bias correction (so the _lag_ is very low as well as the _variability_)
