### ISSUE TITLE
StandalonePsychoPy3_PY3-3.0.0b6-win32.exe created shortcut points to non-existent file and location

### ISSUE THREAD

**Issue by denisfitz57** [psychopy/psychopy#1947]
After running StandalonePsychoPy3_PY3-3.0.0b6-win32.exe, the shortcut in:
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\PsychoPy3_PY3
target contains:
"C:\Program Files (x86)\PsychoPy3_PY3\pythonw.exe" "C:\Program Files (x86)\PsychoPy3_PY3\Lib\site-packages\psychopy\app\psychopyApp.py"

"C:\Program Files (x86)\PsychoPy3_PY3\Lib\site-packages\psychopy\app\psychopyApp.py"
doesn't exist (file or location).

I'm on Windows 10
This may be true for all PsychoPy3_PY3 betas

**Comment by peircej** [comment]
Ah, thanks for the alert. I've tracked this down and it will be fixed in the next release (3.0.0b7).

FWIW I was testing the effects of having a 64bit python3 on my machine and its copy of pip3 had taken over my package installing. I'll change to use the pip explicitly for the correct Python executable.
