### ISSUE TITLE
Cannot push changes to Pavlovia

### ISSUE THREAD

**Issue by WeichengTao** [psychopy/psychopy#2011]
### Summary:
When I was tring to push or sync, the error message showed that push failed due to some username issues. I tested this issue on both macOS13 and macOS14 beta with the command line developer tools shiped with xcode9 and xcode10 beta. 

### Steps to Reproduce:
Download psychopy3 beta 9 from github.
Install it as normal.
Open it and login using the registed pavlovia account.
Search public experiment using the build-in feature.
Fork and sync peircej's flash_drag experiment (everything looks ok right now).
Open synced experiment.
Either sync or run this experiment online using the buld-in feature will cause the push error listed below.
```
Pushing files to PavloviaTraceback (most recent call last):
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/app/pavlovia_ui/project.py", line 455, in syncProject
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/projects/pavlovia.py", line 758, in firstPush
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/git/cmd.py", line 548, in <lambda>
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/git/cmd.py", line 1014, in _call_process
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/git/cmd.py", line 825, in execute
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git push -u origin master
  stderr: 'fatal: could not read Username for 'https://gitlab.pavlovia.org': Device not configured'
```

**Comment by DynamicThoughts96** [comment]
I have the same issue on MacOS 10.13.6 High Sierra. This is the output I get: 

`Synchronising...
Pulling changes from remote...done
Already up to date.
Pushing changes to remote...Traceback (most recent call last):
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/app/pavlovia_ui/project.py", line 475, in syncProject
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/projects/pavlovia.py", line 612, in sync
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/projects/pavlovia.py", line 686, in push
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/projects/pavlovia.py", line 677, in push
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/git/cmd.py", line 548, in <lambda>
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/git/cmd.py", line 1014, in _call_process
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/git/cmd.py", line 825, in execute
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git push
  stderr: 'fatal: could not read Username for 'https://gitlab.pavlovia.org': Device not configured'`

**Comment by peircej** [comment]
Thanks. This has been brought up on the discourse forum too and we're looking into it. 

One possibility is that we need to do a little more on the config of a project when we fetch it. I've just pushed a couple of changes to the app to make sure that a username is associated with the project when it is created locally (this was already being done when initialising a new project from a local existing one, but not when fetching from pavlovia)

The other possibility is that the git project is not correctly detecting the user key in the SSH and connecting that with the one at gitlab, and I'll look at making some more checks there too.

The problem is that I haven't managed to recreate this issue on my own machines (probably because my own machines have my identities set up for all the other code development I do) and until I do it's hard to work out if it's fixed

**Comment by peircej** [comment]
Currently trying to get a mac virtual machine working so I can test on a clean system...

**Comment by DynamicThoughts96** [comment]
Jon,

Thank you so much for your help, I really appreciate your time and attention to this! I recently tried to push the project and received a slightly different error message (attached below). I will retrace my steps to set up the SSH key and ensure that's it matches what I entered into Gitlab as well

`Pushing files to PavloviaTraceback (most recent call last): File"/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/app/pavlovia_ui/projectpy", line 455, in syncProject
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/psychopy/projects/pavlovia.py", line 758, in firstPush
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/git/cmd.py", line 548, in <lambda>
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/git/cmd.py", line 1014, in _call_process
  File "/Applications/PsychoPy3.app/Contents/Resources/lib/python3.6/git/cmd.py", line 825, in execute
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git push -u origin master
  stderr: 'ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
Permission denied, please try again.
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
Permission denied, please try again.
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
git@gitlab.pavlovia.org: Permission denied (publickey,password).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.`

**Comment by peircej** [comment]
Well, it wasn't the steps that you take exactly. PsychoPy sets up the keys for you, but it clearly isn't connecting all the pieces correctly (seemingly just on macs). So hold fire for now and I'll see if I can build something new tomorrow for you to test with.

thanks for your patience

**Comment by WeichengTao** [comment]
**I have successfully pushed a project to my account at gitlab.pavlovia.org using manually generated access token and ssh key (not via psychopy built-in function).**

<img width="554" alt="repo" src="https://user-images.githubusercontent.com/29521987/46001271-7818d980-c0dd-11e8-85da-594f3c9d4f61.png">

**However, the private experiment shown in the pavlovia.org is not runnable.**

<img width="192" alt="pavlovia" src="https://user-images.githubusercontent.com/29521987/46001606-45bbac00-c0de-11e8-81ef-ec006ced992c.png">

**What might be the reason for this problem?**

<img width="777" alt="error" src="https://user-images.githubusercontent.com/29521987/46001269-77804300-c0dd-11e8-8e0b-43d18f1cc500.png">

**Comment by peircej** [comment]
I have now been able to recreate the error `'fatal: could not read Username for 'https://gitlab.pavlovia.org'` using a virtual machine. I'm working on a solution for that. It looks most like the system path being different for a terminal than the application. In terminal, if you do `which git` what does it report?

On the other issue, that the project can't be made active, I'll talk to Ilixa Ltd about what that might be

**Comment by WeichengTao** [comment]
Thank you, Jon.

Because I am using the Xcode version of git, the result of `which git` would always be `/usr/bin/git`. However, the actual location of git binary file will depends on where I installed the Xcode or Xcode toolchains. In my case, it should be `/Applications/Xcode.app/Contents/Developer/usr/bin/git`, which is the default location for Xcode installed via App Store. 

Regarding the project active issue, it actually shows `active` on the website. When I click `run`, the website can successfully redirect me to the `https://pavlovia.org/run/weicheng/preference/html`. The problem is, after redirection, it shows `404 Not Found` instead of the experiment.

**Comment by peircej** [comment]
> Because I am using the Xcode version of git, the result of which git would always be /usr/bin/git. However, the actual location of git binary file will depends on where I installed the Xcode or Xcode toolchains. In my case, it should be /Applications/Xcode.app/Contents/Developer/usr/bin/git, which is the default location for Xcode installed via App Store.

Hmm, OK, if you are using xcode git then it isn't the problem I thought (I was guessing the problem was that one version of git had been set up but not the other).

> Regarding the project active issue, it actually shows active on the website. When I click run, the website can successfully redirect me to the https://pavlovia.org/run/weicheng/preference/html. The problem is, after redirection, it shows 404 Not Found instead of the experiment.

Yes, I can see. I'm seeing the Ilixa guys tomorrow and I'll bring it up with them then.

**Comment by njvack** [comment]
For what it's worth: I had this problem, and syncing suddenly started working for me once I created an access key and pushed from the command line.

It may have been problematic for me because I have 2FA enabled for my pavlovia account?

**Comment by peircej** [comment]
@WeichengTao I think the issue with your study was just that it was somehow activated before it had any materials in. Right now the server isn't updating studies that have been activated (we need to work on the right options for that, because people might not *want* their live study to change when they push a change). The result for you (I think) is that you managed to activate it while empty, and now can't update it with the real materials. By the way, I had a look at your study and I _think_ you'll want to use `pics/3AF-203.jpg` without the ./ for the image names.

**Comment by WeichengTao** [comment]
@peircej Thank you so much! After installing Psychopy via `pip install -e /path/to/latest/repo`, I can successfully sync and run study online. 

I found that to manually activate/deactivate study at Pavlovia is not supported by now. Looking forward to your update.

For `./pics/3AF-203.jpg` issue, I tried your solution, but it seems like Psychopy automatically convert `pics/3AF-203.jpg` to `./pics/3AF-203.jpg` (generating the same error) and Pavlovia may not able to recognise files within subfolder. Everything works great after I moved my pictures out of the subfolder.

**Comment by peircej** [comment]
FYI, the https://pavlovia.org/explore does now allow us to de/re-activatea study (spanner activates, cross deactivates)

**Comment by DynamicThoughts96** [comment]
> For what it's worth: I had this problem, and syncing suddenly started working for me once I created an access key and pushed from the command line.
> 
> It may have been problematic for me because I have 2FA enabled for my pavlovia account?

Did you save your SSH key pair to the suggested path or to a new file path? If you saved it in a new file path was it the same path to access your local project?

**Comment by njvack** [comment]
I... I think it prompted me for a password (I used my access token) and stored it somewhere. I've added my SSH keys to gitlab but it lists them as never having been used.

But basically, my solution was "go to the repo, get command line `git push` to work" and it was fixed. I suspect I'll need to do this again for other repositories.

**Comment by njvack** [comment]
This is probably getting OT for this thread, but it sounds like you should probably start your repo by cloning and then commit from there, or do a `git pull` to get the remote changes.

I'm not sure how psychopy handles git with ssh keys and passphrases; I'm like 99% sure I'm using password auth.

**Comment by DynamicThoughts96** [comment]
I was able to figure it out. There was already an existing repository in the file. Thank you!
