### ISSUE TITLE
Window standalone installation should not require admin access

### ISSUE THREAD

**Issue by njvack** [psychopy/psychopy#2127]
Hi!

I'm trying to install psychopy on a Windows machine where I don't have local admin access. If my memory serves me, in the past I've been able to copy a psychopy installation from Program Files into another folder and have it work fine in the new location.

Assuming that's really true, can you change the installer so it doesn't require admin access? Or put up a standalone .zip file with the contents of the installation?

For what it's worth: I do have access to write to C:, but not to \Program Files or anything.

I guess another workaround would be to install anaconda and then install psychopy through that, but that seems like a really complicated workaround.

My ultimate goal is to have researchers "bring psychopy with them" rather than relying on systemwide installed tools, so systemwide upgrades don't cause surprises for studies that collect data for 5+ years. Well, not quite as often ;)

**Comment by njvack** [comment]
For what it's worth: I just got psychopy3 installed on a Windows system and verified that I can copy that folder to another computer and have it work okay.

**Comment by peircej** [comment]
Yes, it's true that the entire folder should be reasonably portable; we make very little use of registry keys etc except to associate files (if you move the folder then double-clicking a pyexp file won't open the app). 

The thing I'm more scared about is the NSIS script (https://github.com/psychopy/psychopy/blob/master/buildCompleteInstaller.nsi) which is a slightly unpleasant beast. There's an NSIS extension that seems to be designed to support single/multi-user installs (https://nsis.sourceforge.io/Docs/MultiUser/Readme.html) but my experience with NSIS is that it nearly always takes more effort to get right than I was expecting.

Just providing a zip folder isn't very nice because that doesn't provide things like Start Menu items and file associations,  so we'll get flooded with questions about "How do I start it?"

**Comment by njvack** [comment]
Thanks for the info there — yeah, this makes sense and NSIS looks a little "adventurous." We might be able to take a look at this in the new year...

**Comment by dgfitch** [comment]
I've started a branch to look into this.

The builtin NSIS MultiUser plugin appears to work, but the documentation is very weak. It also doesn't support elevation on-demand which is the "nicest" way to do things.

You may want to use https://github.com/Drizin/NsisMultiUser, which does elevation on-demand.

The main remaining issue is that the PsychoPy installer assumes it can write PATH changes to HKLM. Once I resolve that for the CurrentUser style install, I should have a pull request for this.

**Comment by dgfitch** [comment]
A scary thing: using NSIS to modify PATH on windows can [break when the path is over 1024 characters](https://stackoverflow.com/questions/21897103/nsis-envvarupdate-overwrites-system-path-when-path-is-too-long-is-there-a-wor).

See also the big warning in the [NSIS documentation about environment variables](https://nsis.sourceforge.io/Environmental_Variables:_append,_prepend,_and_remove_entries) where they warn that you can corrupt the PATH by doing what the current PsychoPy NSI is doing.

The workarounds are:

* Use a special build of NSIS that ups the breaking point from 1024 to 8096 (yuck)
* Use a [whole ugly bunch of nutty NSI macros](https://www.smartmontools.org/browser/trunk/smartmontools/os_win32/installer.nsi?rev=4110#L636) that try to detect if the path is too long using native functions, and then simply error out if so
* Use an external tool like [PathEd](https://github.com/awaescher/PathEd) to do the editing. Downside: an external dependency for editing the dang path. That one depends on .NET Framework 2.0.

Another option would be to simply have the build process provide a .zip Windows distribution _in addition to_ the auto installers, for folks like us to use.

Thoughts?

**Comment by peircej** [comment]
I do use the long build to avoid this issue. The PsychoPy installer is not having this problem.

**Comment by peircej** [comment]
See this thread where I discuss the issue with NSIS people. They suggested using a different plugin (EnvVar instead of EnvVarUpdate) but I never got around to it because it was easy enough to install the big build version.

By the way though the other thing around the build system is that NSIS only generates a setup.exe and one other user has requested that we have MSI installers instead.

**Comment by njvack** [comment]
Should psychopy even try to change PATH for all users? It's not supposed to be a general-purpose python install... is it? That seems like it's more in the purview of Python / Anaconda than psychopy...

**Comment by peircej** [comment]
I can't remember why it's needed but I'm pretty sure it is. Maybe it was
needed so that python.dll gets found

**Comment by njvack** [comment]
I'm think you don't need it? I've just zipped up the whole distro and dumped it on another computer before... but maybe PATH was already set to include python.dll. But would almost certainly have been pointing to a very old python2.x variant even when I'm transferring a python3 psychopy. Hm...

**Comment by peircej** [comment]
"If it ain't broke don't fix it." 
If setting the path is causing any genuine problems, we could stop doing it and then deal with whatever other problem that raises (it might actually be something that used to be an issue and isn't any more). But while it isn't appearing to cause any problems I'm not keen to change it.

**Comment by njvack** [comment]
Sorry, didn't explain my worry well... if a modified path is needed, and we can't change systemwide path as a non-admin, then when a different user logs in, they'll be missing it and have troubles.

I can't test that in our environment (at least, not without making a VM) as all our Windows desktops have a couple of centrally-deployed pythons including a version of psychopy...
