### ISSUE TITLE
Blank Screen when starting the experiment online (Pavlovia) after adding JS to custom code component 

### ISSUE THREAD

**Issue by Katsuragiai** [psychopy/psychopy#2137]
Dear all, 

I have a question regarding running psychopy3 online (with Pavlovia). 

We pushed our experiment on Pavlovia, and it was able to start when it only included Python code. Eventually, we  encounter an error in our experiment with undefined variables in the custom code component. We looked online and learned that we need to write separate JS code because Pyschopy3 does not auto translate python to JS in the custom code components. So, we added JS code; however, after adding JS code to the custom code component (using the Code Type: Both screen) in the beginning of the experiment, the experiment would not run on Pavlovia (instead, we got a blank white screen).  

Both the Python version and the JS version of the code are shown below. 

Python: 
`import numpy as np

result = np.random.randint(2)

if result == 0:
   Group = "BlockRandomizationFile_1.xlsx"

else:
   Group = "BlockRandomizationFile_2.xlsx"`

JS: 
`import java.util.Random;

int result; 

String Group;

result = rand.nextInt(1) + 0;

if (result == 0){
    Group = "BlockRandomizationFile_1.xlsx";
    }

else {
    Group = "BlockRandomizationFile_2.xlsx";
    }`

1. Could someone let us know what's the potential problem here?

2. Is it because the JS code wasn't correct? 

3. Even when replacing our JS code with something very simple (e.g., "import java.util.Random;"), we still get the same blank white screen problem. Assuming we input correct JS code, is there another reason we would get a blank white screen?

Thanks in advance! 

Best Regards,
Kats

**Comment by hoechenberger** [comment]
Your code is not valid JavaScript; this is Java. Consequently, already the import line will fail, as this module doesn’t exist in JS. 

Pavlovia should still produce an error message instead of “silently” failing, though...

Btw, (global) variables should be created using the new Variable Component, I believe, and not in-code :)

Jon, I was wondering whether we could automatically run linters on the generated Python and JS code so error like these code be discovered already when the user chooses to compile / export their experiment (so one wouldn’t have to run it to figure there are syntax errors etc)?

--
