### ISSUE TITLE
Image size too big on builder view

### ISSUE THREAD

**Issue by sarah756** [psychopy/psychopy#2165]
Hello,

I am constantly getting these messages when trying to run my experiment. I was wondering if I could get any help with resolving these issues. Many thanks.

7.7552     WARNING     User requested fullscreen with size [1024  768], but screen is actually [1440, 900]. Using actual size
2018-12-24 16:52:39.602 python[930:425594] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
Traceback (most recent call last):
  File "/Volumes/Sarah/trial_lastrun.py", line 83, in <module>
    image=faces, mask=None,
NameError: name 'faces' is not defined

**Comment by m-macaskill** [comment]
This is not an issue with the software, but with your setup and procedure. It is best to take such questions to the user support forum at https://discourse.psychopy.org

I'm closing this issue here as it doesn't relate to a bug, but do please raise it at the forum and you'll get the assistance you need.
