### ISSUE TITLE
Updating `Use version.allowedVals` component template – How to do it correctly, what to expect?

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2172]
When running `genComponsTemplate.py --out` on `master` to regenerate `componsTemplate.txt`, `SettingsComponent.Use version.allowedVals` is set to `['latest', '3', '3.0', '', '3.0.0']`

If I change the respective `Settings Component` parameter to call `versionchooser.versionOptions()` with the `local=False` kwarg (the default is `local=True`):

```python
        self.params['Use version'] = Param(
            ...
            allowedVals=versionOptions(local=False) + [''] + availableVersions(),
            ...
```

I get:

```
SettingsComponent.Use version.allowedVals:['latest', '3', '1', '3.0', '1.90', '1.85', '1.84', '1.83', '1.82', '1.81', '1.80', '1.79', '1.78', '1.77', '1.76', '', '3.0.0']
```
At least the order seems to be a bit off, and I'm not sure if "3" should really be present 3 times – is this intended?

**Comment by peircej** [comment]
@kastman might remember better than me, but I think the reason 3, 3.0 and 3.0.0 all show up is that you can request 3.0 to get the latest in the 3.0 series, or 3 gives the latest of that major version etc.

I thought @dvbridges had set up a block so that in Python3 you would not be permitted to try and run versions <1.90.  That should certainly be done since 1.85 will definitely fail on a Python3 installation

**Comment by kastman** [comment]
I peeked at this briefly (haven't seen it in a long time!) and don't see where the 3, 3.0, and 3.0.0 are coming from; it must be `_localVersions` but I'm not sure if we filtered the betas somewhere. I'll try to duplicate this tomorrow, but I suspect it might be an interaction between the remote `psychopy/versions` repo which hasn't been updated past 1.90.2 and the local repo you're using for `genComponsTemplate.py`?

I also didn't see an obvious block for restricting to the 1.90 stream in py3, but that might be something else to follow up on.

**Comment by dvbridges** [comment]
> I thought @dvbridges had set up a block so that in Python3

Yes, a RuntimeError should be raised if a user attempts to use a version of PsychoPy that is not compatible with Python 2: 

https://github.com/psychopy/psychopy/blob/92f9ee984322af3cd08b386ab99d8eb847a4685f/psychopy/tools/versionchooser.py#L96

I think a more sensible option would be to filter the list used to populate the version chooser in Experiment Settings, and keep the runtime error for those using the ```useVersion``` function in custom code.

**Comment by dvbridges** [comment]
> I think the reason 3, 3.0 and 3.0.0 all show up is that you can request 3.0 to get the latest in the 3.0 series, or 3 gives the latest of that major version etc

Its a good idea, but having only major.minor.revision (or just 'latest') gives the user clarity which version they are actually using.

**Comment by peircej** [comment]
OK, @dvbridges can see how we could get rid of that option or keep it. David has also now added the option to filter our other incompatibilities (e.g. you don't have compatible Python/wx for that version).

I definitely think we can get rid of the option for really broad versions like "3". But I think I do see the merit in offering "any version within a bugfix" like 3.0. Maybe the problem is just a visual one that it's jarring to have different numbers of digits (3.0 or 3.0.1). So what if we switched to having `*` where needed:

```
3.0.*
3.0.2
3.0.1
3.0.0
1.90.*
1.90.2
1.90.1
```
Does that look OK and make clear that version 3.0 never existed but you can havea version in that series?
@hoechenberger @kastman if you're happy with this scheme it will be easy for us implement

**Comment by kastman** [comment]
Can we use the version matching in [pep440](https://www.python.org/dev/peps/pep-0440/#compatible-release)? Or is this just for our own drop-downs to show people in Builder?
