### ISSUE TITLE
Experiment not recognized as existing project upon reopening

### ISSUE THREAD

**Issue by jvcasillas** [psychopy/psychopy#2283]
I have created an online experiment that randomly presents auditory stimuli and records the participants responses. The experiment work online as expected. However, whenever I reopen the experiment in builder, make changes, and attempt to synchronize with pavlovia (commit and push new changes), a dialog box pops up stating that the file does not belong to any existing project (though it has been used and synchronized many times). If I click on the “create a new project” button and use the exact same name as the current repo then everything works fine and I can push changes. I can then make more changes and use the synchronize icon from builder (the earth icon the white arrows). If, however, I close psychopy and reopen the experiment file I have to go through the process again.

**Comment by jvcasillas** [comment]
My understanding is that this pull request will take care of the issue. 

https://github.com/psychopy/psychopy/pull/2258

**Comment by marizephe** [comment]
Two years later, and it seems the problem is still there. I have lost many hours and participants. The worse is it will run through the whole experiment and then fail to save at the end!  And it may happen when I have changed nothing (or at least did not mean to). I am feeling very grumpy at the minute. If at least you could get an error message at the start of the experiment. I mean psychopy is free but Pavlovia is not. I reached the stage where I am terrified of updating anything at all whatsover, not even open psychopy in case the damn problem occurs again :-(

**Comment by peircej** [comment]
I believe the point in the original post is fixed. The subsequent comment by  
@marizephe seems to be about the an experiment that has crashed at run time, rather than an experiment not being recognized as existing by PsychoPy
