### ISSUE TITLE
ipython failed as shell with wx - using pyshell instead

### ISSUE THREAD

**Issue by danieltomasz** [psychopy/psychopy#2291]
I installed latest `psychopy v3.0.4` I use `wxPython 4.0.4`
when python shell is changed to ipython in preferences I got

`/home/daniel/.local/lib/python3.6/site-packages/psychopy/app/preferencesDlg.py:289: wxPyDeprecationWarning: Call to deprecated item. Use SetToolTip instead.
  ctrls.valueCtrl.SetToolTipString(_translate(hint))`

and

`1.7866     WARNING     IPython failed as shell, using pyshell (IPython v0.12 can fail on wx)`

**Comment by peircej** [comment]
Don't worry about the SetToolTipString warning - that is just a warning.
Yes, I hadn't done any further work getting iPython to play nicely with wx. It might be that someone else has implemented that by now but I don't know any

**Comment by danieltomasz** [comment]
It seems there are very ugly workarounds since Ipython dropped wx support since `v0.12`
https://github.com/neurodroid/stimfit/issues/23

the links with examples don't work but it is possible to find them by google
https://github.com/ipython/ipykernel/blob/master/examples/embedding/ipkernel_wxapp.py
(but I doubt that you want to add a qt dependency)

For this moment I propose a better description of the issue for the users (if possible), for example
`1.7866 WARNING IPython failed as shell, using pyshell (IPython dropped wx support  since v0.12 release)`

**Comment by hoechenberger** [comment]
I, too, would very much like to see a better REPL than the one we currently have. It's honestly pretty much useless with its extremely limited (editing, history, ...) capabilities (re history: the capability kind of _is_ there, but nobody figures it out because it contradicts what people expect). Several colleagues have independently brought this up to me too; they've since all switched to IPython-based solutions (typically Spyder's console). So if there's any way to make the REPL less painful, I'd be +1000 on it ;)

**Comment by mdcutone** [comment]
I'm currently making a new REPL that is marginally better than what we have now. It is able to spawn separate Python interpreter processes rather than using the application's (which is my biggest problem with PyShell). 

I was also able to run IPython and JS shells from it, but it's really tricky to get working since we don't have real terminal emulation here.

**Comment by mdcutone** [comment]
Closing this since we have a slightly improved REPL in the dev branch (proper history, separate processes, etc.). It's unlikely we'll get IPython support reintroduced anytime soon and the option to change interpreters will be completely removed.
