### ISSUE TITLE
Command "python setup.py egg_info" failed

### ISSUE THREAD

**Issue by mmolet** [psychopy/psychopy#2303]
Hi, 
When I paste this: pip3 install  iolabs in to my terminal/command line (MAC), I got the following message: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/rb/v90fvk0n5570dvp0xx8908y80000gn/T/pip-install-9usik5fi/ioLabs/; anyone knows why? 
thanks in advance for your time

**Comment by peircej** [comment]
I think this is because iolabs hasn't been touched since 2010 (I'm not sure the button box is even available any more) and the code therefore hasn't been updated to support Python3. Even if I had time to update it, I don't have an ioLabs box to test the fixes on. I think I'd recommend switching to a different button box (like the labhackers millikey, the BBTK button box, or the Cedrus response boxes)
