### ISSUE TITLE
saveMovieFrames() method for screenshots only saving blank screen v.3.0.5

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychopy#2345]
Minimal working example:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import, division
from psychopy import visual, core

psychopyVersion = '3.0.5'

win = visual.Window(
    size=[1920, 1080], fullscr=True,
    monitor='testMonitor', color=[-1,-1,-1], colorSpace='rgb',
    blendMode='avg', useFBO=True,
    units='height')

text = visual.TextStim(win=win, name='text',
    text='Example text',
    depth=0.0);

for frame in range(60):
    text.draw()    
    win.getMovieFrame(buffer='back')
    win.flip()

win.saveMovieFrames('screenshot.jpg')
win.close()
core.quit()

```

**Comment by peircej** [comment]
I'm pretty sure this isn't broken everywhere (because the test suite uses geMovieFrame to check stimulus rendering). Getting the 'front' buffer should only be done after the win.flip() call so either use the back buffer or make the call after the flip. (But I'm not sure that's the problem - I think in your code you'd just get a 1-frame lag between drawing and screenshots)

**Comment by dvbridges** [comment]
Yes cheers, I have tested that but still the same problem. Code edited above.

**Comment by dvbridges** [comment]
I think I made an error with the code - its works after all!
