### ISSUE TITLE
Sounddevice preference crashes when trying to load a sound file (PsychoPy 3.0.6, Py 2.7 - Windows)

### ISSUE THREAD

**Issue by frankgasking** [psychopy/psychopy#2355]
Just been testing out 3.0.6 Python 2.7 edition on Windows 7 and 10 platforms, and have found the following issue with the sound preference:

With 'sounddevice' as the default, every time you try to load an audio file (Wav or MP3),  it will result in a :

```
raise SoundFormatError(err)
psychopy.exceptions.SoundFormatError: Tried to create audio stream 22050_2_128 but 44100_2_128 already exists and win32 does not support multiple portaudio streams.
```

As a result, right away we need to switch over preference to Pyo or PyGame to get any sound playback working.

Also - if you ever so slightly get the formatting wrong for the preferences, it corrupts the text and puts in garbage like ['j', 'j' '', 'jjj'], so you have to reset it back to the old preferences to fix.  No major issue.

NOTE: We are looking to move over to Python 3 next year, if EyeLink 1000 support comes across as well.  Really we need to stick to 2.7 for this year.

**Comment by frankgasking** [comment]
Just to update - but i've also tested on 3.0.5 and 3.0.0 Py2.7 Win 32 editions and the same issue is present, so seems to have started since V3.

**Comment by frankgasking** [comment]
Just to update - but this is still broken in 3.0.7 Py27 Win 32 after some testing of the most recent build.

**Comment by peircej** [comment]
Regarding the sound stream clashes, is it possible that you have another sound object in the experiment, other than just this wav file? If I just have a 22050 sample rate wav file everything works fine. The issue crops up if I try to use this after a 44100 file (or synthesized sound) which is the expected behaviour.

On the question of Eyelink, our new release 3.1.0 (hopefully today!) will have beta support for an updated (python3-compatible) pylink toolbox and iohub will be supporting that too. So you could test that out too if you like. Note that PsychoPy3 installs alongside PsychoPy2 and they won't interact, so you can give it a go and see if it works.

**Comment by frankgasking** [comment]
Ah, yes - that's it!  Some of the experiments are using sound files with different levels.

Great news about the Eyelink support too - we are going to stick with the 2.7 flavour this year, then move over to 3 next year.

I'll close this request btw.
