### ISSUE TITLE
psychopy 3- Name error: name 'basestring' is not defined

### ISSUE THREAD

**Issue by Hostate** [psychopy/psychopy#2397]
In psychopy 3, Windows 10, buiderview, I want to change key_resp's "Allowed keys" in each trial, but it responded that: Name error: name 'basestring' is not defined.
It seems that this problem only occurred in psychopy 3.

**Comment by dvbridges** [comment]
Hi @Hostate , which version of PsychoPy are you using? I recently made a pull request to fix this: 

>When a variable is used as a keylist and is not a list, tuple or np array,
it is evaluated to determine whether it is a string. In Python 2,
basestring is the comparison type, but basestring does not exist in
Python 3. This fix changes the comparison type depending on Python version
running.
See https://github.com/psychopy/psychopy/pull/2379

I believe this will be fixed in the next release - 3.1.0

**Comment by Hostate** [comment]
Hi @dvbridges  , I used Psychopy 3.0.6
I fix this problem by uninstalling that version of Psychopy and install 1.9.0. All problems are solved.
I can't wait for the next release, I will use this program in my undergraduate thesis.
Anyway, thank you for your reply and tolerating my poor English. XD
And thank you for your contribution to this repo.
