### ISSUE TITLE
Adding variable to builder causes `AttributeError: 'str' object has no attribute 'tStart'`

### ISSUE THREAD

**Issue by njvack** [psychopy/psychopy#2499]
To replicate, make a blank Builder experiment, add a variable, try to run it. In my example, it's called `var1`. Run it, and you'll get a crash with `AttributeError: 'str' object has no attribute 'tStart'`.

In the generated python code, I get:

```
# Line 78:
var1 = ''

# ...
# Line 92
trialComponents = [var1]
for thisComponent in trialComponents:
    thisComponent.tStart = None
```

which is indeed not going to work because `var1` is just a string. I both feel like I must be doing something wrong because otherwise this would be broken for a ton of people, but that if so, I have no idea what I'm doing wrong,

Tested in 3.1.2 Standalone on macOS.

**Comment by dvbridges** [comment]
Hi @njvack , thanks. You are are using the Variable correctly. This issue has arisen following new changes that the track start and stop times of PsychoPy components. The code is failing because types of data commonly used in a Variable component, such as strings and ints, do not allow attributes to be added to them. I am posting a fix now which should skip this step causing the error for any Variable components in the task.
