### ISSUE TITLE
Add QUEST+ code & Builder demos

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2541]

**Comment by drbenvincent** [comment]
Just mentioning this here because it's related...

From the next release (3.2.0 I believe) PsychoPy will include our adaptive methods. Preprint here:

> Vincent, B. T., & Rainforth, T. (2017, October 20). The DARC Toolbox: automated, flexible, and efficient delayed and risky choice experiments using Bayesian adaptive design. https://doi.org/10.31234/osf.io/yehjb

Our methods have similar functions to QUEST+ in that we can optimally select multiple design variables at a time (not just one). Our methods are also very efficient and so can be applied to models with relatively high number of parameters etc.

We have a core algorithm, and we write experiment specific code which uses this. So far we have created a bunch of decision making examples. However we will soon be extending this to psychophysics examples. 

I guess it doesn't really matter if there is both QUEST+ and our methods, but I'm just mentioning our plans.

**Comment by hoechenberger** [comment]
Sounds great, looking forward to playing with some psychophysics examples!
