### ISSUE TITLE
git remote not added when adding an existing repo to a project

### ISSUE THREAD

**Issue by kastman** [psychopy/psychopy#2552]
For existing repos, I seem to be having an intermittent error where the remote is being connected / internally registered when Builder registers a project at first, but then the remote disappears. Pushing with the builder still works, but `git remote -v` returns nothing. Manually adding a remote with `git remote add` does seem to work, and allows pushing.

Is this intended behavior? Not reproducible? If it doesn't happen to other people we can close this issue, but I thought I'd bring it up as noticed, odd behavior.

**Comment by kastman** [comment]
Was this possibly resolved in https://github.com/psychopy/psychopy/commit/08d7937 ?

**Comment by peircej** [comment]
That commit made it possible to sync (from within the app) to an ssh remote (added outside the app). Previously, by searching for 'gitlab.pavlovia.org/' we were implicitly only checking whether the experiment had an https remote. That was mostly fine because the app was creating https remotes, but wasn't fine if the user created the repo from terminal using ssh remote.

So I don't think it affects the issue you've raised which I haven't been able to reproduce. Is it something you're still having trouble with?

**Comment by hoechenberger** [comment]
@kastman Does this issue still exist for you?

**Comment by kastman** [comment]
@hoechenberger Double checked and it seems to be ok; I'll re-open if I hit it again!
