### ISSUE TITLE
MultiStairHandler should support method='fullRandom'

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2635]
Currently, `MultiStairHandler` only supports `method='sequential'` and `method='random'`. The latter will randomize the order of staircases on each trial separately, which ensures that no staircase can ever be called on more than 2 consecutive trials. However, certain experimental designs demand a _full_ randomization across _all_ trials. This is not possible with the current implementation of `MultiStairHandler`. `MultiStairHandler` should support this behavior, which was dubbed `fullRandom` in the `TrialHandler`.

**Comment by peircej** [comment]
Hmm, for TrialHandler this is done by concatenating the trials and then shuffling. The method can't be *quite* the same for staircases because they have an indetrminate number of trials (in advance) so we can't do the advance concatenation, but we could keep track of still-running staircases and do a resample-with-replacement on each trial? I think that would be the same effective strategy, right? Actually for TrialHandler2 there's the same issue and probably the same solution.

**Comment by peircej** [comment]
(because in TrialHandler2 we might have an issue that a trial wants to be rerun and therefore appears again)
