### ISSUE TITLE
Rect is not created at the right size.

### ISSUE THREAD

**Issue by maartenuni** [psychopy/psychopy#2644]
I'll show a brief program below. The program demonstrates unclear/consistent behavior of the size, width and height arguments when creating a new Rect. Using the argparse module, the user can easily create a rectangle using the size argument. When the program isn't given any argument, the width and height argument of `Rect()` are used and then the the proper size is used for the rectangle, if the `size=(width, height)` is used, the height and width dimensions are half the width and height that would be expected.

```
#!/usr/bin/env python3
'''This program creates a window of 800 by 600 with a black background
So when we display a Rectangle of 600 by 600 in the middle of the window,
the rectangle should touch the upper and lower boundary of the window

when a rectangle is created with the size argument, the size is half as
big as one would expect, since the rectangle doesn't touch the bottom
and upper boundary of the window, whereas when the width and height arguments
are used, the resulting rectangle is as big as one would expect.
'''


from psychopy.visual import Window, Rect
import argparse as ap
import platform, sys

print("python.version = ", sys.version)
import platform
print(platform.uname())
print(platform.system())
print(platform.processor())

WIDTH, HEIGHT = 600, 600
SIZE = (WIDTH, HEIGHT)

BLACK = (-1, -1, -1)
WHITE = (1, 1, 1)
POS   = (0, 0)

parser = ap.ArgumentParser()
parser.add_argument (
    "-s", "--use-size",
    help=('Use size to determine the size of the rectangle, displays rect'
          'in incorrect/ unexpected dimensions'),
    action='store_true'
    )
parser.add_argument (
    "-n", "--num-frames",
    help="Number of frames to display the rectangle",
    type=int,
    default=180
    )

args = parser.parse_args()

win = Window((800, 600), color=BLACK, units='pix')

rect = None
if args.use_size:
    rect = Rect(win, color=WHITE, size=SIZE)
else:
    rect = Rect(win, color=WHITE, width=WIDTH, height=HEIGHT)

for i in range(args.num_frames):
    rect.draw()
    win.flip()
```

This result in the following output for me:

> python rectangle.py -s
> python.version =  3.5.2 (default, Nov 12 2018, 13:43:14) 
> [GCC 5.4.0 20160609]
> uname_result(system='Linux', node='im-lab-009-02', release='4.15.0-47-lowlatency', version='#50~16.04.1-Ubuntu SMP PREEMPT Fri Mar 15 17:23:09 UTC 2019', machine='x86_64', processor='x86_64')
> Linux
> x86_64
> 0.7824 	WARNING 	Monitor specification not found. Creating a temporary one...
>

**Comment by peircej** [comment]
I don't think size was intended to be used at all for Rect but the developer that contributed this made it possible to provide any arguments withouth getting an error. I think the bigger thing we need to do is go through and remove places in our code where subclasses receive/pass arguments blindly using `**kwargs`

For now simply stick to width, height.

**Comment by mdcutone** [comment]
So what do we do here? Should we get rid of width/height or size?

**Comment by maartenuni** [comment]
Perhaps "size" is a misleading term. A size for 2D rectangles is something that implies width and height. But if I understand it correctly, size is used as a scaling_factor. size[0] is the scaling along the x-axis and size[1] along the y-axis. I wouldn't make the same error with Rect(win, scaling_factor=(width, height)), than I would lookup some other argument and only use scaling_factor when I want to scale a Square to a Rectangle for example.

**Comment by peircej** [comment]
**For explanation:** For most stimuli, although size is scaling the vertex position, this is actually the correct behaviour. We set the vertices to be -0.5 : +0.5 so multiplying these up has the desired effect. On this occasion, the person that added `Rect` broke from that model (for some reason that I forget) and used adjusted the vertices directly rather than leaving them alone and changing the scale.

**What to do?** Right now people using Rect (including Builder scripts) are using width, height anmd I don't like breaking people's scripts unless really necessary, so we could stick with that. But all the other stimuli use size[0], size[1] and I don't like things being inconsistent either! ;-)

Maybe we should allow both, and push that through to all other stimuli too. Maybe there's even an advantage in that. We could make `stim.width` into an alias for `stim.size[0]` and using properties that would work fine.

The immediate fix for Rect is that setting width,height should _not_ alter the vertices as it currently does. Those should always be -0.5,0.5 etc. Width,height should alter size and use that to scale the vertices and then we can set size in both ways as @maartenuni was expecting

**Comment by mdcutone** [comment]
Opened PR #2650 to address this issue.
