### ISSUE TITLE
inconsistent rt data from csv and log files

### ISSUE THREAD

**Issue by hhouhouhou** [psychopy/psychopy#2679]
Hello,

I found the rt data from the csv file is somewhat different from the log file (computed based on keypress and response_starttime). This time differences vary from several ms to almost 100ms. I use the 3.2.3 psychopy builder and the keyboard component to get data. Do you any insight about the difference? And which file do you use to analyze the rt data?

Thanks in advance!

**Comment by peircej** [comment]
Hard to know from this answer because I there are multiple ways to get key timing. I'm guessing that you're using Builder and that you have a 64bit python3 install in which case you're probably using the new keyboard class. In that case the response time in the csv file is reporting the time the key was detected at the point of of the USB cable, whereas the logfile is indicating when the key was first noticed by the Python thread (later than the USB bus).
So the csv file would be the one to use.

Note that this is probably a query for the forum rather than an issue for the github repository.
