### ISSUE TITLE
Clicking the "Run" button should actually run the experiment

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#2815]
With the new Runner, clicking "Run" in the Coder or Builder view doesn't do as promised, as the experiment isn't being run; instead, the user is taken to the Runner view and has to run the experiment from there. This is annoying during testing. Can the process be adjusted such that clicking Run would add the experiment to the Runner and run it automatically, without requiring any further user interaction?

(I do know about the double Cmd-R keyboard shortcut workaround, but I don't think it's really convenient)

cc @shirllim

**Comment by peircej** [comment]
This one is something we debated and deliberately chose this route (hence change of icon). Yes, technically, it's easy to automatically start the run as well, but half the point of the runner is to give us a chance to provide alerts before running. As the range of alerts increases this seems useful.

So the question is how to make it easy for experienced users but also provide good info for newbies (salient alerts).

**Comment by hoechenberger** [comment]
How about:
- Handing over the experiment to the Runner, as is being done now
- If no Alerts show up, run immediately
- otherwise, don't run so the user can view (and fix) the Alerts?

**Comment by mdcutone** [comment]
I suggest adding a dropdown to the tool which allows the user to choose from a menu whether to immediately run the experiment in a console or use runner. Though I really like having runner, the stdout and alerts all in one place is really cool.

**Comment by peircej** [comment]
Yes, implementing Richard's solution sounds fair enough. It's very easy to implement and for now that would work. Right now there aren't many alerts ( https://psychopy.org/alerts/ ) so that box would normally be empty, but I do envisage the alerts for Builder experiments to ramp up fairly quickly - the plan is to start going through places where we currently use logging.warn and replace with an appropriate alert. For scripts there isn't currently  any analysis of the script being performed so alerts can only currently occur through the script being launched. That will change in time as well though (e.g. we could analyse the script in advance to see if the user is calling event.getKeys rather than Keyboard class).

For the option of the dropdown buttons, I agree this would be helpful (and probably we should an additional shortcut key). I think that means switching the current wx.Toolbar to be a wx.RibbonToolBar because I don't think standard Toolbar has dropdown options. That might have additional benefits anyway, but I've never used one (I'm presuming this isn't available only on windows. Once we've gone that route we could make the run button automatically go to Run, Runner, and Debug (the last could be local debug for web, and we could implement debug support for Coder ultimately too)

**Comment by mdcutone** [comment]
> For the option of the dropdown buttons, I agree this would be helpful (and probably we should an additional shortcut key). I think that means switching the current wx.Toolbar to be a wx.RibbonToolBar because I don't think standard Toolbar has dropdown options.

Ribbon toolbar is janky in wx. The regular toolbar can have dropdown items, but I think we should use the AUI toolbar that also supports them. It looks more consistent across platforms and supports custom art providers for themes (eg. dark mode).

**Comment by peircej** [comment]
ah, OK. Yes AUI toolbar is better - I didn't know that supported dropdowns. Cool

**Comment by mdcutone** [comment]
I think wxPython 4.1 is tracking wxWidgets 3.1 which has baked-in support for the ribbon bar now (the original was pure-python and kind of messy last time I messed around with it). Once it's released (4.1) we can consider it. One thing it's missing was the toggle button in the top-right corner ribbon bars all have, which I think they added.

**Comment by peircej** [comment]
I initially wrote the response below, that we should delay for compatibility reasons with useVersion, but I've just remembered that we don't need to worry - people aren't using wx *during* experiments anyway because it was fouling up the pyglet event loop and I had force use of Qt for experiment dialogs. So, yes, I could update the Standalone to use 4.1 in the next feature release (2020.2)

**Comment by mdcutone** [comment]
> people aren't using wx during experiments anyway because it was fouling up the pyglet event loop

Any known reason for this? I can attempt to fix it in upstream wxPython if that's the case.

**Comment by peircej** [comment]
Well, with wx 4.0.0 the following halts execution when the dialog is created (it never shows). I've never worried about it because the qt dialogs worked fine (and are arguably prettier). This is tested just now on a Mac but my memory is that it's broken on all platforms.

``` python
from psychopy.gui import wxgui
print(wxgui.wx.__version__)

# comment either of these lines out and it will run
from psychopy import visual
dlg = wxgui.DlgFromDict({"a":1})

print('got here')
```

**Comment by mdcutone** [comment]
It seems to be working fine for me with Pyglet. Not sure what's going on here, I'm using wxPython 4.0.7pre2.
