### ISSUE TITLE
Request: Rating Scale show current value and accept text

### ISSUE THREAD

**Issue by chepo92** [psychopy/psychopy#2837]
I would like the rating scale to show the current value and the accept text at same time, as currenty it shows one or another, also would be nice if the value could be put in/above/under the marker and not in the accept button

**Comment by peircej** [comment]
Instead of Rating Scale you use the Slider and then simply create the button yourself - draw a square and add whatever text you like on top of that square (you could set it to $"{} OK?".format(mySlider.markerPos). Then add a mouse and make the square "clickable" ending the Routine on a Valid Click.

This system might be a few more steps than simply using the Rating Scale with its OK button but in the end it means complete flexibility to change the string however you like.
