### ISSUE TITLE
Packge tries to overwrite system files

### ISSUE THREAD

**Issue by TheChymera** [psychopy/psychopy#2838]
I am updating the Gentoo Linux package for psychopy, and I find that it tries to overwrite files belonging to another package, more specifically to `dev-python/packaging`.

This is the full [build.log](https://github.com/psychopy/psychopy/files/4367796/build.log).

It would be cool if the generation of these replacement files could be prevented (we can just delete them in the package manager file, but that would make the package more convoluted and potentially less sustainable).
Any idea how I can prevent psychopy from generating these replacement files?

**Comment by peircej** [comment]
One part of this is certainly at my end - I renamed a folder `packaging` that had previously been called `buildScripts` and I've now called it `building`. The name `packaging` certainly isn't a wise choice because it can clash with the packaging lib.

BUT that folder shouldn't be getting installed (whatever it gets called) into site-packages. The scripts it contains are purely for packaging psychopy into an application and running tests etc. these files shouldn't be needed by end users. Why is the gentoo build system treating them as a package to install?

**Comment by TheChymera** [comment]
@peircej thank you, it works for the time being by explicitly removing it as part of the build script. I assume that the reason the Gentoo package manager attempts to install the directory is because it contains an `__init__.py` file.

**Comment by peircej** [comment]
The `__init__` file is needed so that I can import the functions. Ah, but I've found what might be the cause. In setup.py we use an automated call `find_packages()` and I bet that's what has found the packaging folder and treated it as a separate installable object. I'll fix that too

**Comment by TheChymera** [comment]
Thanks!
