### ISSUE TITLE
Some Problem When Running on Win 10

### ISSUE THREAD

**Issue by dayekuaipao** [psychopy/psychopy#2851]
I write my code in my computer on win 10.However, when I send this to my classmate but it doesn`t work.The error message is 'Cound not find the Qt platform plugin "windows" in "". ' What`s the problem?

**Comment by peircej** [comment]
Very hard to tell from this information but most likely this is a problem with the installation on your friend's computer. Could you use the forum as your first step (but provide omre information there, including all the lines of the error message)? If it really looks like a bug in PsychoPy (with some idea of where the bug is) then we can open an issue here. Thanks

**Comment by peircej** [comment]
A quick google revealed this: https://forum.qt.io/topic/90293/could-not-find-or-load-the-qt-platform-plugin-windows-in/2
