### ISSUE TITLE
Icons for .psyexp files appear as Coder not Builder

### ISSUE THREAD

**Issue by TEParsons** [psychopy/psychopy#3072]
![image](https://user-images.githubusercontent.com/25686106/90491177-7c1dcc80-e137-11ea-9322-0c86a27ee936.png)
Files ending in .psyexp should have the Builder icon but seem to have Coder instead

**Comment by peircej** [comment]
OK, I think I can see what's doing that - when we associate .py files with PsychoPy were reusing the file "type" `PsychoPy.experiment` rather than adding `PsychoPy.script` type

Actually though maybe we shouldn't associate py files with PsychoPy at all, as they're too general? I think I'll disable this entirely for now

**Comment by peircej** [comment]
fixed in 2a14c7c
