### ISSUE TITLE
Keyboard/Mouse input not working on other computer with same settings

### ISSUE THREAD

**Issue by bastienk** [psychopy/psychopy#3273]
Hello,

I have a project using keyboard input on some routines. The project is working perfectly fine on macOS 10.15.7. When I try to run the project on an other computer also running on macOS 10.15.7 the keyboard inputs are not recognized (I use them to go to an other routine). The keyboard inputs are enabled under macOS Privacy settings. Trying to replace the keyboard with mouse input produces the same issue. I am using Psychopy 2020.2.5 and it has been installed using brew, however I'm getting the same issue with the standard dmg install. Any idea of what's going wrong?

Thank you for your help!

**Comment by TEParsons** [comment]
Is this something specific to one experiment or can you not get keyboard/mouse input from any experiment?

**Comment by bastienk** [comment]
The issue happens on any experiment

**Comment by peircej** [comment]
If all experiments aren't working I feel sure it's going to be an issue with mac not granting sufficient permissions. Maybe you've enabled keyboard inputs for a different version of PsychoPy (e.g. labelled PsychoPy3 is a different app) but not the one you're using?

If you install using brew then it will depend how you launch the app - if you launch from terminal then you'll also need to grant input access to terminal. But I think this is a user support issue with macOS (more suitable for the forum), rather than a bug in PsychoPy per se, so I'm closing as an issue. I mean, I don't think it's something we can fix if the system prevents PsychoPy having keyboard access.
