### ISSUE TITLE
Routine responses and image not timing correctly

### ISSUE THREAD

**Issue by jgo650** [psychopy/psychopy#3280]
Hello,

I'm having trouble timing a routine's image and number of responses to be in sync. The routine showing an image is supposed to only last 20 seconds and participants are supposed to input key responses as much as they can in those 20 seconds (there are 32 correct inputs total). However, when I run the experiment, the image stays over 20 seconds and waits for 32 inputs to be put in.

In Builder, I set the duration for the image for 20 seconds, the keyboard responses have infinite duration, and there are 32 repetitions for the loop.

I thought it could be the number of repetitions, but when I set it to 1, the routine automatically ends when only 1 input is put in (without inputs put in, oddly enough, the image stayed up for 20 seconds).

I'm new to PsychoPy and coding, so I'm not sure how to input a custom code to fix this.

**Comment by TEParsons** [comment]
I think you're misunderstanding what loops and Routines are for - a Component is contained within a Routine, so if the Routine ends the Component ends. If you have a loop, it will repeat the same Routine n times, so what's happening is you're making a 20s Image component and then ending it (by ending its routine) from a keypress, then starting the same routine again, resetting the timer. Instead of a loop I would recommend adding in a Code component with something in Each Frame to check for number of keypresses, probably:
```
if len(myKeyboardComponent.getKeys()) >= 32:
    continueRoutine = False
```

For future reference, support issues like this are better suited to our discourse forum:
https://discourse.psychopy.org/
The Issues tab on GitHub is more for things which are a bug in the software itself
