### ISSUE TITLE
Versions 2020.2.7-2020.2.9 not showing in 'Use Version' of 2020.2.10

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#3359]
previous version not available in use version dropdown box

**Comment by tpronk** [comment]
Hey @RebeccaHirst, our issues might be related :). Cross-linking them. https://github.com/psychopy/psychopy/issues/3360

**Comment by peircej** [comment]
I've done this now. 

For info on how it works, the system is built upon the useVersion function fetching a copy of this git repo: https://github.com/psychopy/versions
When you say `useVersion('2020.2.5')` we update the repo (if needed), checkout that tag and then tell Python to use this instead of the installed version of PsychoPy.

So, after a new release I have to (at some stage) copy the new files over to that versions repo and tag the new version within it.

When it goes wrong it's because I haven't done that step so the versions repo doesn't have the tag for that new version.
