### ISSUE TITLE
Running psyexpCompile.py with --version latest compiles a psyexp file to version 3.2.4

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychopy#3360]
I had the issue mentioned in the subject. Diving into the code a bit, I noticed the following:
- psyexpCompile.py calls `useVersion` to get the right version
- After a couple of function calls it ends up at [this line](https://github.com/psychopy/psychopy/blob/2510db23de0659d42863c22c7bcb56621f0a23c2/psychopy/tools/versionchooser.py#L306), which gets the first element of a list of versions.
- That list is generated via [this line](https://github.com/psychopy/psychopy/blob/2510db23de0659d42863c22c7bcb56621f0a23c2/psychopy/tools/versionchooser.py#L203). 

If I print `_localVersionsCache` from the line above, I get the output shown below. Two things seem to be going wrong:
1. It sorts the version numbers in decreasing order, but my hunch is that the versions are sorted as strings instead of numbers. 
2. It seems newer versions (2020.7 upwards) aren't included.

```['3.2.4', '3.2.3', '3.2.2', '3.2.1', '3.2.0', '3.1.5', '3.1.4', '3.1.3', '3.1.2', '3.1.1', '3.1.0', '3.0.7', '3.0.6', '3.0.5', '3.0.4', '3.0.3', '3.0.2', '3.0.1', '3.0.0', '2020.2.6', '2020.2.5', '2020.2.4', '2020.2.3', '2020.2.2', '2020.2.1', '2020.2.0', '2020.1.3', '2020.1.2', '2020.1.1', '1.90.2', '1.90.1', '1.90.0', '1.85.6', '1.85.4', '1.85.3', '1.85.2', '1.85.1', '1.85.0', '1.84.2', '1.84.1', '1.84.0', '1.83.04', '1.83.03', '1.83.01', '1.83.00', '1.82.01', '1.82.00', '1.81.03', '1.81.02', '1.81.01', '1.81.00', '1.80.06', '1.80.05', '1.80.03', '1.80.02', '1.80.01', '1.80.00', '1.79.00', '1.78.01', '1.78.00', '1.77.02', '1.77.01', '1.77.00', '1.76.00']```

**Comment by tpronk** [comment]
Perhaps related to https://github.com/psychopy/psychopy/issues/3359?

**Comment by peircej** [comment]
It's because of this:
https://github.com/psychopy/psychopy/blob/a7c7cc5f30a79659c1963af8126e44c96ad81ace/psychopy/tools/versionchooser.py#L279
Basically we're sorting a list of strings and now that we've switched to year-based major versions that doesn't work ('2020.2.10' is less than '3.2.4' in a string comparison). There are functions in the [packaging.version lib](https://packaging.pypa.io/en/latest/version.html) that allow proper version comparison and we do use that elsewhwere in the code but hadn't implemented it here. I think we'll need to do something where we sort based on `version.parse()` and then convert back to a string.

It's unrelated to the other #3359 which is just that I need to update the repo/tags at https://github.com/psychopy/versions/tags which is a separate repository of released versions only

**Comment by tpronk** [comment]
Thanks for the pointer! I'll go play around with parse_version and see if I can fix it myself

**Comment by tpronk** [comment]
Done. Made a PR: https://github.com/psychopy/psychopy/pull/3364
