### ISSUE TITLE
'None' is not a valid color space when running the VSHD demo

### ISSUE THREAD

**Issue by mdcutone** [psychopy/psychopy#3609]
When running the VSHD demo `hardware` > `VSHD_Distortion.py` demo (need to change `nSamples` to `numSamples` to get it to run. The demo locks up when pressing a button and I get the following printed out to builder multiple times.

```
'None' is not a valid color space
```

Might be related to the use of either the ImageStim or TextStim class.

**Comment by TEParsons** [comment]
I can't replicate this, what buttons were you pressing specifically? That error I think is in the Color class - when you pass it a color space that isn't in `colors.colorSpaces` - I'm guessing at some point an object's colorSpace is set to None and it then tries to create a `Color` with space `None` rather than treating `None` as "not set" and reverting to a default...

**Comment by mdcutone** [comment]
When I press any of the buttons I get the error.

**Comment by TEParsons** [comment]
I think this is fixed now?

**Comment by mdcutone** [comment]
Does the demo run when you try it?

**Comment by TEParsons** [comment]
Yeah, seems fine on my build at least

**Comment by mdcutone** [comment]
Okay closing for now.
