### ISSUE TITLE
Check for PsychoPy updates never finds newer versions because version is outdated

### ISSUE THREAD

**Issue by pn2200** [psychopy/psychopy#3677]
The version used to check if updates are available, at https://psychopy.org/version.txt, is outdated, so checking for updates never finds a newer update to install. This file should be updated on each release, so the update check can work correctly.

**Comment by peircej** [comment]
I think this shouldn't be updated on every release, at least historically not, because we don't necessarily recommend everyone updates immediately all the time. I agree it should be updated now. We haven't been using the system for so long that I don't actually know if the patch updates still work 🤔

**Comment by pn2200** [comment]
I am exaggerating a little bit, but I am also serious with this suggestion. Given that this feature is buggy (#3675), hasn't been used in 20+ releases, does not appear to have tests, and there hasn't been any clamor to make it work, maybe it isn't needed and can be removed?

**Comment by peircej** [comment]
I don't think it needs removing right now - the concept is useful and it should be worked on and fixed. With the next release I will update version.text on psychopy.org alerting people to get up to 2021.1.4
At that point I'll look into whether patch-update still works and, if so I can set it to patch update from 2021.1.0
