### ISSUE TITLE
Eye tracking Calibration: Not presented if MouseGaze used

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#3945]
The calibration routine does not present if MouseGaze is the eye tracking device type.

**Comment by isolver** [comment]
This is most likely because of the "Disable Component" issue or issue of component gui state != 'internal' state. If you generate the python script, is there any call to calibration? I have had to be generatng python script from Builder to check things like this to see if it is Builder not genrating expected code.
