### ISSUE TITLE
psychopy.info disappeared

### ISSUE THREAD

**Issue by alexholcombe** [psychopy/psychopy#4065]
psychopy.info is not showing up for me or my student, in 2021.1.4, when one calls:

`import psychopy`

If one then executes
'psychopy.info', for example from the Psychopy IDE’s Shell, one gets this error:

AttributeError: module 'psychopy' has no attribute 'info'

Versions of psychopy a couple years ago did not have this error, and e.g. `psychopy.visual` does not throw an error.  I'm guessing that some initialization thing that makes `info` available got lost. Note that what does still work is:

`from psychopy import info`

For more see [the discourse post](https://discourse.psychopy.org/t/psychopy-info-disappeared/23619/2)

**Comment by peircej** [comment]
This is actually the expected behaviour. We could set up the `psychopy/__init__.py` to import all submodules in which case your code would work, but haven't done that for many years because it means _all_ of PsychoPy being imported when you import _any_ part of it. With the notation:
```
from psychopy import info, visual, data
```
you can choose which parts of the package you import and for something as large as PsychoPy that's important
