### ISSUE TITLE
Pyo problem in MacOS

### ISSUE THREAD

**Issue by iPsych** [psychopy/psychopy#4122]
There are many reports in forum on mic issue with MacOS.
I've struggled for days, and found solution.
It's just hacky solution, and hope the dylib with correct relative path is included in new release : )

in the pyo folder, 
`/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/pyo
`
run below commands.
`install_name_tool -change @loader_path/libportaudio.2.dylib @loader_path/…/…/…/…/Frameworks/libportaudio.2.dylib _pyo.cpython-36m-darwin.so
`

**Comment by thewoz** [comment]
I try you hack.
However I not able to open PsychoPy since the file look dameged.
Moreover the ... in the path should be ..?

**Comment by iPsych** [comment]
@thewoz 
It's hacky way, since it's touching the dylib after it compiled. 
So, SIP should disabled. First check it.
Than possiblly need to disable sudo spctl --master-disable.
Little safer way is trying xattr based on below link.
https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/

**Comment by thewoz** [comment]
Hi thanks for the answer.
I have disable the xattr and PsychoPy start.
however I still have an error running an experiment. #4134

**Comment by iPsych** [comment]
@thewoz Me neither...
2021.1.4 is currently works, but not 2.0 or 2.0.1...

**Comment by peircej** [comment]
I'm surprised this works - I thought pyo was being stripped entirely since we began codesigning for macOS gatekeeper (a requirement to working on Big Sur)

BUT there's a new Microphone class that uses Psychtoolbox instead:
  https://github.com/psychopy/psychopy/blob/release/psychopy/sound/microphone.py
I believe this is more robust, almost certainly lower-latency, and works out the box (although for macOS you should fetch the 2021.2.1 release uploaded this morning because the 21.2.0 release also had issues with PTB and the wretched GateKeeper signing)

I'm assuming you're using the older microphone code and I expect us to fully deprecate that sooner or later
