### ISSUE TITLE
Pavlovia doesn't play moviepy stimuli

### ISSUE THREAD

**Issue by StefanoVicentin** [psychopy/psychopy#4235]
Hello everyone, 
I am having some issues to load movie stimuli to Pavlovia. 
I have created an experiment where subjects needs to see a video clip (2 minutes) right before the task. It works pretty well offline, but once I load it in Pavlovia, the movie does not start, showing only the first image for the whole duration of the video stimulus, without audio. Stimuli are .mp4, saved in the moviepy backend, last for 120 s and are 25 to 100 MB. 
Does any one else had the same problems? 

Here's the link to the task: 
https://pavlovia.org/Stefano_PhD/thai_coam

Any suggestions? 
Thanks to everyone

**Comment by jfkominsky** [comment]
Moviepy isn't relevant here because Pavlovia uses a different system for playing movies. Online studies are run using JavaScript rather than Python, and I believe movies in particular are loaded as HTML5 movie tags. Are the movies h.264 encoded? In general mp4s should work, but more often than not this is an issue with the movie files themselves. See https://discourse.psychopy.org/t/pavlovia-wont-play-the-movie-stimuli/11747

**Comment by TEParsons** [comment]
Moving this over to the PsychoJS repo as it concerns online studies specifically.

https://github.com/psychopy/psychojs/issues/480
