### ISSUE TITLE
Eyetracker calibrate routine: "Press space to start" text not visible if window color is black

### ISSUE THREAD

**Issue by RebeccaHirst** [psychopy/psychopy#4262]
Because the text "press space to start" in the eyetracker calibrate routine is black, the text is not visible if the background is black. Ideally we could either expose this text in the callibration routine, or make the text the inverse of the background colour so it is always visible

**Comment by isolver** [comment]
Since three of the eye trackers initial calibration screen is different (either different text or text + other graphics), I think we should add support for specifying the calibration text _color_ as a new eye tracker calibration setting and expose this in Builder.

**Comment by HanZhang-psych** [comment]
Minor comment: the same issue applies to the validation routine as well. E.g., the validation results are hard to see if the background color is black.

**Comment by isolver** [comment]
[This branch](https://github.com/isolver/psychopy/tree/enh-calibration-text-color) fixes the text color issue for calibration. The new default behaviour does what @RebeccaHirst suggested, calculating the text color based on the background color. The nice thing about this approach is that it does not require any Builder GUI updates. ;) Wondering if we should add these type of functions to the Color class, so `color.inverse()` could be called to get an inverse of the color `color`? 

In Python, you can also now manually specify the text color to use during calibration, but this new setting is not added in Builder yet, so Builder projects use the text auto color default.

Wondering if I should submit this as a PR now, targeted for Release, and leave out the setting in Builder for now? Or should we add the Builder setting and therefore probably target the fix for the Dev branch instead? @RebeccaHirst, @TEParsons, what do you think?

I'll add text color support for validation in a seperate branch; created [a new issue](https://github.com/psychopy/psychopy/issues/4273) for it as well.  Thank you

**Comment by isolver** [comment]
Fixed by PR #4275 which has been merged into Dev
