### ISSUE TITLE
Mismatch between Python en Web

### ISSUE THREAD

**Issue by erikkemperman** [psychopy/psychopy#4373]
Hi,

There seem to be methods available in Python, e.g. ImageStim.overlaps(), which are not present in the JavaScript library. This is very unfortunate -- researchers merrily use these functions while developing their experiments, only to find that things don't work on the web. Perhaps I missed something, but the documentation doesn't seem to warn us about this.

Is this a known issue? Is there an overview somewhere documenting which methods can and can't be expected to be available in JS?

**Comment by peircej** [comment]
We try and maintain a list of the major functionality and what is/isn't supported online:
    https://www.psychopy.org/online/status.html
Furthermore, in the next major release (2022.1.0) we will be adding toggle in the Builder only to show components that support the JS and/or Python engines so that if you know you want to run the study online you can choose not even to see the Components that aren't supported.

That said, we aren't currently planning to get to the level of listing every method/attribute of every class, including those that users might put into a Code Component. It would be a very long comparison that would be hard to maintain accurately

**Comment by erikkemperman** [comment]
Thanks for the quick response! I’ve implemented a JS kludge myself, and I will let the researcher know to check your link before spending a lot of time on a potential dead end.
