### ISSUE TITLE
msgpack TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by tillea** [psychopy/psychopy#4440]
Hi,
I'd like to forward a long standing [bug report in Debian](https://bugs.debian.org/829424) which contains suggestion how to fix it sensibly.  I confirm that the issue persists here:

    psychopy/iohub/client/eyetracker/validation/procedure.py:624:        rootScriptPath = os.path.dirname(sys.argv[0])
    psychopy/iohub/client/__init__.py:846:        rootScriptPath = os.path.dirname(sys.argv[0])

Kind regards, Andreas.

**Comment by isolver** [comment]
As of 2021.1.x iohub no longer uses or creates an .iohpid file, so the original report in debian should no longer be an issue. Could you confirm what the error is you are now getting when using the current release of psychopy? Thank you

**Comment by emollier** [comment]
Greetings,

I tried to run the reproducer in today's debian sid, _ipython3_ 7.31.1 and _psychopy_ 2022.1.3 and got a different output.  Actually the new issue is reproducible in the classical interpreter:
```
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psychopy.iohub as iohub
>>> io = iohub.launchHubServer()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/psychopy/contrib/lazy_import.py", line 118, in __call__
    return obj(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/psychopy/iohub/client/connect.py", line 256, in launchHubServer
    return ioHubConnection(iohub_config)
  File "/usr/lib/python3/dist-packages/psychopy/iohub/client/__init__.py", line 294, in __init__
    self.iohub_status = self._startServer(ioHubConfig, ioHubConfigAbsPath)
  File "/usr/lib/python3/dist-packages/psychopy/iohub/client/__init__.py", line 984, in _startServer
    self.udp_client = UDPClientConnection(remote_port=server_udp_port, timeout=0.1)
  File "/usr/lib/python3/dist-packages/psychopy/iohub/net.py", line 116, in __init__
    SocketConnection.__init__(self, remote_host=remote_host,
  File "/usr/lib/python3/dist-packages/psychopy/iohub/net.py", line 48, in __init__
    self.packer = msgpack.Packer()
  File "/usr/lib/python3/dist-packages/msgpack_numpy.py", line 127, in __init__
    super(Packer, self).__init__(default=default,
  File "msgpack/_packer.pyx", line 124, in msgpack._cmsgpack.Packer.__init__
TypeError: __init__() got an unexpected keyword argument 'encoding'
```
The result feels like this is because of running a _python2_ script in _python3_ context, but the necessary _python2_ libraries on which _psychopy_ depends, such as the module _pathlib_, are not available anymore in Debian to do such test.

Kind regards,
Étienne.

**Comment by isolver** [comment]
> `File "msgpack/_packer.pyx", line 124, in msgpack._cmsgpack.Packer.__init__
> TypeError: __init__() got an unexpected keyword argument 'encoding'`

This error is from an older version of `msgpack(-python)` being installed. If you have `msgpack-python` installed, please uninstall it. Then install/upgrade to the latest version of the `msgpack` package (`pip install msgpack`).

Thank you

**Comment by tillea** [comment]
Am Tue, May 03, 2022 at 06:15:04AM -0700 schrieb Sol Simpson:
> This error is from an older version of `msgpack(-python)` being installed. If you have `msgpack-python` installed, please uninstall it. Then install/upgrade to the latest version of the `msgpack` package (`pip install msgpack`).
Thanks.  The latest msgpack version is now packaged and psychopy builds nicely with it.

**Comment by emollier** [comment]
Hi there, I confirm the _iohub_ server is starting properly with latest _msgpack_:
```
In [1]: import psychopy.iohub as iohub

In [2]: io = iohub.launchHubServer()

 *** iohub warning: Display / Monitor unit type has not been set.
pygame 2.1.2 (SDL 2.0.22, Python 3.10.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
```

The remaining bug turned out to occur in _msgpack-numpy_ in the specific case of running with _python3_.  Even though the code branches to the newer _msgpack_ version, it seemed to have some _python2_-ish encoding handling which does not exist anymore in _python3_.  Running a _2to3_ conversion of _msgpack-numpy_ and excluding the _encoding_ arguments at the incriminated lines 128 and 147 did the trick; will continue investigating it in other channels.  As far as I can tell, the issue is sorted on your end, Thank you!

Have a nice day,  :)
Étienne.

**Comment by ghost** [comment]
dd
