### ISSUE TITLE
Instantiating MoveStim3 object before SoundPyo object causes SoundPyo sampleRate argument to be silently ignored. 

### ISSUE THREAD

**Issue by grahamfindlay** [psychopy/psychopy#4690]
I am using an [external USB audio interface](https://focusrite.com/en/usb-audio-interface/scarlett/scarlett-2i2)  to deliver ultrasonic vocalizations at 192kHz to mice, while also playing them silent natural-scene movies. I have discovered that unless the `noAudio` option is set to True when creatuing a `MovieStim3`  object, even if the video file has no audio track, the `sampleRate` argument to subsequently created `SoundPyo` objects is silently ignored, and auditory stimuli are instead downsampled to 44.1kHz. If the `SoundPyo` object is created before the `MoveStim3` object, this does not happen. 

Perhaps there is a way for `SoundPyo` to check if it has actually succeeded at setting the requested `sampleRate`, and having it raise an error or a warning if it has not? 

I discovered this issue by recording playback during an experiment with an ultrasonic microphone, and was puzzled when there was no frequency content above 22kHz when running my experiment, while there had been ultrasonic content while testing. 

Thanks for all the wonderful work you do with PsychoPy!

**Comment by mdcutone** [comment]
Thank you for your post. Looking at the code, the SoundPyo backend spawns a server to interface with the audio driver that is configured only on the first use. Sample rate cannot be changed in successive instances of `Sound` object. I'll add a warning for now since allowing multiple sample rates requires substantial changes right now.
