### ISSUE TITLE
Setting random seed fails to produce fixed sequence for NoiseStim()

### ISSUE THREAD

**Issue by emilskog** [psychopy/psychopy#4696]
Hi,

I have noticed that setting the random seed fails to produce a fixed sequence of noise images for NoiseStim(). 
I noticed this while attempting to recreate my experiment that relies on saving noise textures. 
I have tested on 2 machines, running V2021.2.3 and V2021.2.0.

Recreate by making a sequence/loop of NoiseStim() in Builder and setting the random seed. The noise textures will not have a fixed sequence when experiment is repeated. 

The file seedTest.py illustrates that setting the seed in data.TrialHandler() does not fix the sequence of noise images. 
[seedTest.zip](https://github.com/psychopy/psychopy/files/8251806/seedTest.zip)

Thank you for the wonderful work you do with PsychoPy.

**Comment by peircej** [comment]
Setting the random seed for the Trial Handler should only alter the random pattern for the ordering of trials, not for all possible uses of random. It's important that the two things are kept separate (for example, if we used a single global seed, and then you added an extra random() call somewhere in your code it would cause the sequence to change).

We haven't yet provided an option to set the seed of the noise stimulus. 

Workarounds:
- you could set the global seed of the numpy.random module (again, that won't affect your trial order because we've made sure that's separate for the reasons above).
- you could save images of noise patterns and use those as textures in your stimulus so you'll be absolutely sure they're unchanging

**Comment by peircej** [comment]
I'm closing this for now because I believe the current behaviour is the desired one
