### ISSUE TITLE
win.getActualFrameRate reports incorrect frameRate on external monitor

### ISSUE THREAD

**Issue by waltervanheuven** [psychopy/psychopy#4721]
I have an external monitor (2560x1440, max 144Hz) connected to my M1 MacBook Pro (Monterey 12.3) and set it to the main screen. I noticed that `win.getActualFrameRate()` always returns ~60Hz even though the monitor refresh rate is set to 120Hz or 144Hz. 

```python
from psychopy import visual
winType='pyglet'
win = visual.Window(
    size=[2560, 1440], fullscr=True, screen=0, 
    winType=winType, allowGUI=False, allowStencil=False,
    monitor='testMonitor', color=[0,0,0], colorSpace='rgb',
    blendMode='avg', useFBO=True, 
    units='height')
print("RefreshRate: %3.2f Hz" % win.getActualFrameRate())
```

Furthermore, running the script with `screen=1` results in a black screen on the MacBook retina screen (notting is shown on the screen and refresh rate reported does not make sense). Same happens the other way around with the retina screen as the main screen and the monitor as screen=1.

**Comment by davidhildebrand** [comment]
Any update on this bug?
Found it today while troubleshooting more or less the same problem.

In case it helps, some additional information follows.
PsychoPy version: 2021.2.3
Operating system: Ubuntu 20.04
Graphics card: NVIDIA GeForce RTX 2080 Ti Founders Edition
Stimulus display (via USB-C): ASUS XG16AHPE ROG Strix
Non-stimulus/system display (via HDMI): Dell P2219HC

The operating system and graphics card appear to properly recognize the displays and set the correct refresh rate.
```
$ xrandr
Screen 0: minimum 8 x 8, current 3668 x 2160, maximum 32767 x 32767
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-0 connected primary 1920x1080+0+1080 (normal left inverted right
x axis y axis) 476mm x 267mm
   1920x1080     60.00*+  59.94    50.00
   1600x900      60.00
   1280x1024     75.02    60.02
   1280x720      60.00    59.94    50.00
   1152x864      75.00
   1024x768      75.03    60.00
   800x600       75.00    60.32
   720x576       50.00
   720x480       59.94
   640x480       75.00    59.94    59.93
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 disconnected (normal left inverted right x axis y axis)
DP-5 disconnected (normal left inverted right x axis y axis)
USB-C-0 connected 1920x1080+1748+0 (normal left inverted right x axis
y axis) 344mm x 194mm
   1920x1080    144.00*+ 120.00   119.88   100.00    74.91    60.00    59.94
   1680x1050     59.95
   1440x900      59.89
   1280x1024     75.02    60.02
   1280x960      60.00
   1280x800      59.81
   1280x720      60.00    59.94
   1152x864      75.00
   1024x768      75.03    70.07    60.00
   800x600       75.00    72.19    60.32
   720x480       59.94
   640x480       75.00    72.81    59.94    59.93
$
```

The operating system settings are set such that the stimulus display should have a refresh rate of 144 Hz.
![Ubuntu display settings](https://user-images.githubusercontent.com/799157/176319191-6a71c40d-624c-4826-95f8-3bb2afe42c98.png)

The NVIDIA X Server Settings are set such that the stimulus display should have a refresh rate of 144 Hz.
![NVIDIA stimulus screen device information](https://user-images.githubusercontent.com/799157/176318209-4d1afe6d-de21-42e7-bcc4-e4c90bc14733.png)
![NVIDIA sync setting](https://user-images.githubusercontent.com/799157/176319252-0448ab52-3dca-43f6-9a59-f6cf84597661.png)

PsychoPy measures the refresh rate as 60 Hz, not 144 Hz.
`1.7120 DEBUG Screen (1) actual frame rate measured at 60.00`

The window.flip() commands run with the timing that would be expected of 60 Hz (e.g., 60.1 sec to display 3607 frames).

This occurs under various different NVIDIA X Server Settings configurations for the stimulus display, including with 'Sync to VBlank' being on or off and 'Allow G-SYNC/G-SYNC Compatible' being on or off.

Any updates or workarounds would be greatly appreciated.  Thanks!

**Comment by m-macaskill** [comment]
> PsychoPy measures the refresh rate as 60 Hz, not 144 Hz.

PsychoPy can measure the screen refresh rate, but can't set it. Hence it is not clear that this is a PsychoPy bug, rather than errors in the reported refresh rate via xrandr and the OS - there have been a number of issues reported about this under Ubuntu.

My suggestion would be to try disconnecting your second display (the one connected by HDMI). What then happens to PsychoPy's measured refresh rate (not sure if a restart would be needed or not)?

**Comment by davidhildebrand** [comment]
> PsychoPy can measure the screen refresh rate, but can't set it. Hence it is not clear that this is a PsychoPy bug, rather than errors in the reported refresh rate via xrandr and the OS - there have been a number of issues reported about this under Ubuntu.

As shown through the outputs and screen shots in my previous post, the screen refresh rate appeared to be correctly reported by xrandr and the operating system.  They both report it as 144 Hz, as does the display itself.

> My suggestion would be to try disconnecting your second display (the one connected by HDMI). What then happens to PsychoPy's measured refresh rate (not sure if a restart would be needed or not)?

Thanks, this is good suggestion and helps clarify.
After disconnecting the non-stimulus/system display (HDMI), PsychoPy indeed reports a refresh rate of ~144 Hz.
`145249.9947 DEBUG Screen (1) actual frame rate measured at 145.68`
And the window.flip() commands run with the timing that would be expected for a refresh rate of 144 Hz (e.g., 30.3 sec to display 4370 frames).

**Comment by m-macaskill** [comment]
> As shown through the outputs and screen shots in my previous post, the screen refresh rate appeared to be correctly reported by xrandr and the operating system. They both report it as 144 Hz, as does the display itself.

I haven't seen any evidence that is the case. Again, PsychoPy is actually _measuring_ the refresh rate. So this might indicate that you should view those reports above with some scepticism. As noted, there are multiple reports of screen refresh rates under Ubuntu not being correctly displayed by the OS/xrandr. This is particularly the case when several monitors are connected, when it can happen that the system drives the multiple displays at a lowest common denominator refresh rate, while reporting the native or maximum rate as the actual value.

This seems to be validated by the result of your experiment - PsychoPy can measure the refresh rate at (approximately) 144 Hz, _if the system is actually driving it at that rate._

I don't know enough about this to be much further help, but if you have access to a second ASUStek monitor of the same specs, and connect that instead of the 60 Hz Dell, what happens then? i.e. it is possible that two displays with the same ability to run at 144 Hz might work. This could be complicated by whether your HDMI port can drive that display at 144 Hz, but that is a test you can do with the existing monitor. Otherwise, can one of the DisplayPorts be used?

What happens if you set the ASUStek rather than the Dell to be the primary display?

Ultimately, the only real way to be sure is to do a physical measure, using a photodiode or similar, with software that creates an alternating light/dark display every frame. Ideally you'd use something other than PsychoPy to definitively show whether PsychoPy is the actual source of the problem.

**Comment by davidhildebrand** [comment]
Finally able to offer an update after purchasing a second ASUS XG16AHPE ROG Strix to use as the system display (via HDMI).

> I haven't seen any evidence that is the case. Again, PsychoPy is actually _measuring_ the refresh rate. So this might indicate that you should view those reports above with some scepticism.  As noted, there are multiple reports of screen refresh rates under Ubuntu not being correctly displayed by the OS/xrandr. This is particularly the case when several monitors are connected, when it can happen that the system drives the multiple displays at a lowest common denominator refresh rate, while reporting the _maximum_ rate as the actual value.

Are there no good solutions these days, then?  Windows 10 doesn't seem compatible with gamma correction (at least through PsychoPy) and Psychtoolbox seems like it has given up on anything past Windows 7.  But Ubuntu can't seem to report the correct refresh rate in instances with multiple monitors?  
Yikes...

> This seems to be validated by the result of your experiment - PsychoPy can measure the refresh rate at (approximately) 144 Hz, _if the system is actually driving it at that rate._

You are correct.  Once I have both a system and a second stimulus ASUS XG16AHPE added to the system, it seems that both are driven at the correct rate.
`230.9316 DEBUG Screen (1) actual frame rate measured at 143.73`

> What happens if you set the ASUStek rather than the Dell to be the primary display?

Not completely sure.  I seem to remember trying it, but I don't have screenshots to prove that I did.  I think that I didn't target this as a solution previously because it is also undesirable to have the dock/taskbar on the stimulus screen.

> Ultimately, the only real way to be sure is to do a physical measure, using a photodiode or similar, with software that creates an alternating light/dark display every frame. Ideally you'd use something other than PsychoPy to definitively show whether PsychoPy is the actual source of the problem.

Fair enough.  Fortunate enough here to have two monitors and what appears to be a working solution now, but troubleshooting Ubuntu issues in the future may be worthwhile.

Thanks for your comments and suggestions, @m-macaskill!

**Comment by m-macaskill** [comment]
Thanks for getting back to us David - this report and your testing will be a useful guide to others with the same problem in the future. As this didn't seem to be a PsychoPy issue after all, I'll close the issue for now (although the OP raised this on on Mac OS – hard to know if that is the same sort of problem).

**Comment by davidhildebrand** [comment]
> As this didn't seem to be a PsychoPy issue after all, I'll close the issue for now.

Fine by me, though note that the original issue was not on Ubuntu and my experience may have been unrelated to that report.
