### ISSUE TITLE
Problems with installation on Ubuntu 20.04

### ISSUE THREAD

**Issue by ambitious-octopus** [psychopy/psychopy#4829]
I'm trying to install Psychopy on Ubuntu 20.04. Unfortunately, the installation with pip gives an error because some dependencies related to PulseAudio are missing. In addition, I tried to follow the instructions to create a conda environment, but the installation failed. Is there a docker container? If there isn't, it would be interesting to create one; if you think it's a way to guarantee usability for Linux users, I can take care of it.

**Comment by peircej** [comment]
For further information about installing on ubuntu see these posts on the forum:
https://discourse.psychopy.org/t/installation-headaches-and-partly-fixes-on-ubuntu-20-04/16476/9
https://discourse.psychopy.org/t/how-to-install-psychopy-on-ubuntu-21-10/26762
(actually the comments in those posts about adding the group are now being handled better within PsychoPy app by providing a dialog that tells users what to paste into the terminal to get that part working).

Happy to take updates to the documentation, which is all on github, to make this easier for other users

My understanding is that docker won't work, or will be hopeless performance, because it doesn't have access to the hardware it would need. Singularity might be a better alternative. See the discussion here on the possibility of providing a docker image:
https://discourse.psychopy.org/t/is-there-a-docker-image-for-psychopy/27094

Again, happy to take contributions on that if we're reasonably confident that it works as expected.

What I'd really love is to get back to the place where we could do `apt install psychopy` and there has been some packaging work recently by the Debian-med team but I don't think it's working yet

I'm closing this issue for now though since the points are covered elsewhere.
