### ISSUE TITLE
Unable to download psychojs-2022.1.4

### ISSUE THREAD

**Issue by naiqixiao** [psychopy/psychopy#4850]
I'm using PsychoPy 2022.1.4 to generate JS file for an online study. When I tested the online program, it will generate a lib folder within the program folder. In this folder, there a several .js files, such as psychojs-2022.1.4.js.

However, each file was nearly empty. The only content is:
`<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>`

There might be an issue in downloading PsychoJS 2022.1.4 files.

I have replicated this issue both on Mac 12.4 and Windows 11.

**Comment by frankpapenmeier** [comment]
I can confirm that it is not possible to create new online experiments with the newest PsychoPy version 2022.1.4. This was tested on Windows 10.

We have two issues:
1.) JavaScript files and index.html are copied into a folder called "index.html" instead of right next to the psyexp file, causing Pavlovia not to automatically detect the PsychoPy version used.
2.) If one copies the files manually to the correct location, it will then fail with the error reported by @naiqixiao that is a 404 for psychojs-2022.1.4.js

**Comment by peircej** [comment]
Definitely appears to be there now https://lib.pavlovia.org/psychojs-2022.1.4.js
