### ISSUE TITLE
Multiple Touchscreen Support

### ISSUE THREAD

**Issue by KenR22** [psychopy/psychopy#4896]
Hi,

We are working with macaques working on 8 touch screens. I was wondering if psychopy supports 8 touch screen?
Also, it would be nice if there are tutorials for touchscreen stimulus selection?

Thanks,
Ken

**Comment by m-macaskill** [comment]
This sort of question is better addressed to the support forum at <https://discourse.psychopy.org> - ideally Github is used for specific code issues rather than general support queries.

However you might be interested in this paper by Ben Seitz: <https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0246446> 

PsychoPy should be able to display stimuli on as many monitors as your computer supports. Whether it can independently track mouse/touch events on each one I'm not sure - best to raise that at the forum.

Re tutorials for touchscreen stimulus selection - this should be no different than selecting stimuli via the mouse - from PsychoPy's point of view, a touch event is registered as a mouse click.
