### ISSUE TITLE
Timezones should be stored in the date by default

### ISSUE THREAD

**Issue by LordFckHelmchen** [psychopy/psychopy#5075]
## Problem description

Currently, the experiment info contains the date of the experiment without a timezone. This would create problems when labs use the the same script across different timezones.

## Suggested solution

`utils.getDateStr()` should store the [local timezone](https://dateutil.readthedocs.io/en/stable/examples.html#tzlocal-examples) (or even better UTC - but this would require some awareness in the users).

**Comment by peircej** [comment]
I'm afraid I'm inclined to disagree with this one, on the basis that:

1. I _think_ the need to know the timezone of the participant is exceedingly rare, even when data are collected in international settings. Then again, what's your use-case where the absolute time is needed rather than the relative time for the participant?
2. the timezone and/or UTC time can be added into the data file with a single line in a Code Component
3. adding this as an optional parameter increases heterogeneity between users

**Comment by LordFckHelmchen** [comment]
My concern would be that when you run online/distributed experiments, that you end up with different timestamps. I agree that this is a niche case, but UTC would simply prevent any problems there (and parsing the additional timezone info isn't really a hard overhead).
Imho, On 3., handling it directly out-of-the-box would make things more uniform as no timezone handling would have to added anywhere - but again this depends on how much of a niche case you consider this.
