### ISSUE TITLE
remove javascripthon?

### ISSUE THREAD

**Issue by tbenst** [psychopy/psychopy#5215]
As far as I can see, `javascripthon` is not used in psychopy codebase, but it causes the build to fail on macOS for python 3.9.

javascripthon depends on metapensiero which depends on dukpy, which fails to build on macOS.

I understand this was discussed previously as well: https://github.com/psychopy/psychopy/issues/2757

**Comment by peircej** [comment]
The thing that we _need_ is `metapensiero` so that the [app can convert code snippets into JS](https://github.com/psychopy/psychopy/blob/dev/psychopy/experiment/py2js_transpiler.py). That's why `javascripthon` is a requirement even though that appears never to be imported itself. 

If the ultimate issue is that metapensiero/dukpy doesn't build on Mac Python 3.9 then let's get it fixed so that it does. Removing it from psychopy (at least from the app) isn't an option right now.
