### ISSUE TITLE
viewport is None when checkTiming=False (2022.2.5)

### ISSUE THREAD

**Issue by igmmgi** [psychopy/psychopy#5306]
```
from psychopy import visual, core

win = visual.Window(checkTiming=False) # works on 2022.2.4
# win = visual.Window(checkTiming=True) # works

txt = visual.TextStim(win)
txt.draw()  
win.flip()  

core.wait(2)  
win.close()

# Pyglet 1.5.27 vs. 1.4.11, Ubuntu 22.10, python 3.9.13
```

**Comment by TEParsons** [comment]
Ah, I see the problem here - if checkTiming is False then the initial frame rate test is skipped, and this is the only thing in Window.__init__ which calls Window.flip. Without that initial flip, the viewport remains as None as it hasn't been initialised yet. 

This has cropped up in this release due to a change in how viewport is set - previously it was set manually on init, now it's set by flip or by calling Window.resetViewport. Easy fix I believe, just need to add a call to that function to init if checkTiming is False. Thanks for catching this!
