### ISSUE TITLE
after playin a video via MovieStim the status stays 0 and the experiment can't terminate

### ISSUE THREAD

**Issue by nastia-lado** [psychopy/psychopy#5463]
Here is the code that I use for the experiment, created based on online tutorials:
```
win = visual.Window(size=[1280, 720], units='pix')  # fullscr=True
video_names = [f'{stimuli_dir}/S1.mp4', f'{stimuli_dir}/S2.mp4']
n_reps = 2
trials = data.TrialHandler(video_names, n_reps, method='random')
for trial in trials:
    mov = visual.MovieStim(win, trial,
                           size=None,  # set as `None` to use the native video size
                           # pos specifies the /center/ of the movie stim location
                           pos=[0, 0],
                           flipVert=False,  # flip the video picture vertically
                           flipHoriz=False,  # flip the video picture horizontally
                           loop=False,  # replay the video when it reaches the end
                           autoStart=True,  # start the video automatically when first drawn
                           units='pix')
    while mov.status != visual.FINISHED:
        mov.draw()
        win.flip()
win.close()
core.quit() 
```
The first video plays without any problems, but then mov.status stays always 0. So it never becomes -1 necessary to break the while-loop.

Python version is 3.10

**Comment by nastia-lado** [comment]
Psychopy version was 2023.1.0 and the problem was in that version. When I downgraded to 2022.2.5 (the previous one), everything started working

**Comment by TEParsons** [comment]
Previously stimuli were inconsistent in how status was applied - in some components like ImageStim, it was only ever set from Builder and the ImageStim object wouldn't touch its status attribute. In others like MovieStim and SoundStim, calling `stop` or letting the clip play to completion would change its status.

In 2023 we changed it so that status was purely a Builder thing for all stimuli, which is why this no longer works. You should use `mov.isFinished` instead - the value of this attribute will be either True or False.
