### ISSUE TITLE
[Bug]: builder generated code restarts audio clips with ptb backend

### ISSUE THREAD

**Issue by Jolinda** [psychopy/psychopy#5858]
### PsychoPy Version

2023.2.1

### What OS are your PsychoPy running on?

Windows 10, macOS Intel

### Bug Description

Code generated by builder will potentially start replaying audio clips when using the ptb backend. The culprit is the line:
` sound_1.pause()  # ensure sound has stopped at end of Routine`
which is generated at the end of a routine containing audio. If the routine has previously called sound_1.stop(), or if the sound has finished, this will cause the sound to begin playing again. The only case that appears to avoid this is for a routine with a fixed duration shorter than the duration of the sound clip -- in that scenario the clip is still playing when the routine ends, and pause will stop the clip.

### Expected Behaviour

I expect an audio clip in a builder routine to not start playing again when the next routine begins.

### Steps to Reproduce

1. Create a builder experiment with two routines and ptb audio backend
2. Place an audio clip with blank duration in the first routine
3. Place a text stimulus in the second routine
4. Run it. Sound will begin playing again at the start of the second routine.
5. Same behavior occurs if a variable duration is given for the sound, or a constant duration greater than the length of the sound clip.
...
[audio_test.zip](https://github.com/psychopy/psychopy/files/12441819/audio_test.zip)

**Comment by peircej** [comment]
Thanks @Jolinda for digging in and diagnosing the problem. I've fixed it in #5874 

Basically, I think `pause` shouldn't be a toggle (the name doesn't convey that) and that caused this problem because we switched to using it for stop-but-don't-reset relatively recently not anticipating the toggle behaviour that was inserted in 2023.1 

So I've reverted that toggling behaviour of PTB sound and this will be fixed in 2023.2.2 (imminent)
