### ISSUE TITLE
[Feature Request]: Standardize checking status of movie stimulus playback in PsychoPy and PsychoJS

### ISSUE THREAD

**Issue by jfkominsky** [psychopy/psychopy#6055]
### Description

The most recent versions of PsychoPy use the MovieStim.isFinished property to report whether a movie has finished playback. PsychoJS uses PsychoJS.Status.FINISHED. The FINISHED status was removed from Python in favor of the isFinished property, but no corresponding property was added to PsychoJS.

You can work around it with a bit of effort, but even in a code component you can't use auto->js because you have to use the isFinished property in Python and the FINISHED status in PsychoJS. 

### Purpose

Prior to the MoveStim rewrite and use of ffpyplayer library, both PsychoJS and PsychoPy used a "FINISHED" status, so it was possible to use auto->js code translation or a condition to start a component (e.g., show a response only after a movie finishes playing within a single trial) that would work both locally and online. 

### Is your feature request related to a problem?

Just that you end up creating experiments that work _either_ locally or online but not both without a very careful workaround,  and it's unintuitive and bad for standardization. It's also not well-documented, since the MovieStim API page just references isFinished.

### Describe the solution you would like

I can think of three fixes, not sure what would be easiest:

1. Add an isFinished property to MovieStim in PsychoJS
2. Add a redundant "FINISHED" status back in to PsychoPy's MovieStim
3. Change auto->js to interpret ".isFinished" as "=== PsychoJS.Status.FINISHED" (not ideal because it doesn't necessarily work as a condition for a component)

### Describe alternatives that you have considered

N/A

**Comment by peircej** [comment]
We added `.isFinished` to the Python class so that we could distinguish between a movie that had reached its end versus one that had been told by Builder to finish. Basically the class needs to have a record of how the file-reading is going that's independent of how the experiment is running. BUT the aim was for the movie.status also to be updated on every frame so that checks on `movie.status==FINISHED` would still work

@TEParsons implemented that for [SoundComponent in  lines 165-171](https://github.com/psychopy/psychopy/blob/f8854fb76cb9c81b3584af25073ee054e1c47a04/psychopy/experiment/components/sound/__init__.py#L165-L171) but it looks like the same wasn't done for Movie

**Comment by TEParsons** [comment]
Solution 2 is implemented in #6740
