### ISSUE TITLE
[Bug]: AttributeError: 'SoundPygame' object has no attribute 'seek'

### ISSUE THREAD

**Issue by AzyshFotbnxe** [psychopy/psychopy#6145]
### PsychoPy Version

2023.2.3

### What OS are your PsychoPy running on?

Windows 10

### Bug Description

I am running psychopy, with playing sound from an external .wav file. Then the error jumps and the program terminated.

### Expected Behaviour

The sound should be played and the program continues.

### Steps to Reproduce

1. Fully uninstall psychopy and reinstall
2. Fully uninstall python and reinstall

**Comment by peircej** [comment]
Hi there @sanosenx86 
Is there a reason you need to use pygame for the sound player? The PTB engine is far superior in terms of performance and that's the strongest recommendation. Can you change your preferences to use that as the first listed option? 

You should be seeing a warning within the app that this is strongly recommended when you run your study

**Comment by AzyshFotbnxe** [comment]
> Hi there @sanosenx86 Is there a reason you need to use pygame for the sound player? The PTB engine is far superior in terms of performance and that's the strongest recommendation. Can you change your preferences to use that as the first listed option?
> 
> You should be seeing a warning within the app that this is strongly recommended when you run your study

Thank you for your reply. Yes, I have tried PTB at the first, and all the other engines; however, the sound plays weirdly (like 10x faster than it should be), I think it is relevant to the sampling rate but I have no idea how to fix it. Only pygame works as expected.

By the way, the experiment with pygame engine works well in v2022.2.3 version.

**Comment by peircej** [comment]
For us to look at this one at all we would need the full stack-trace (to work out where the problematic seek call was being made) but we won't be willing to spend much time on this since our supprot for pygame is essentially deprecated in favour of the higher-performance sound engines. If you have a minimal demo (e.g. a sound file and the minimal code/exp) of the PTB engine failing, or some more information for us to work out what's gone wrong there then we'd prefer to fix that instead.

thanks

**Comment by peircej** [comment]
I'm closing this for now pending further info. To reiterate, we really want to focus on a single audio engine so let us know how to get PTB working
