### ISSUE TITLE
[Bug]: hardware.keyboard.waitKeys crash on Windows 11

### ISSUE THREAD

**Issue by csarradet** [psychopy/psychopy#6243]
### PsychoPy Version

2023.1.2

### What OS are your PsychoPy running on?

Windows 11

### Bug Description

On Win11, call the waitKeys method of a psychopy.hardware.keyboard.Keyboard instance.  If no key is pressed within ~6 seconds, Windows will flag python as unresponsive and terminate it.

In my experiment I replaced the stock waitKeys method with a monkey patched version.  Changing the time.sleep(0.00001) call to psychopy.core.wait(0.00001) fixed the problem.

### Expected Behaviour

The waitKeys call should wait politely until a key is pressed or maxWait is reached

### Steps to Reproduce

1.  hwkb = psychopy.hardware.keyboard.Keyboard()
2.  kwkb.waitKeys()
3.  Wait approx 6 seconds with no keyboard input, eventually Windows will produce the "Python is unresponsive" popup

### Additional context
Python 3.9.5

_No response_

**Comment by peircej** [comment]
Good catch @csarradet 
Digging a bit further, it looks like the issue is that the windows needs to keep processing events or Windows think it's died. 
`psychopy.clock.wait` includes a call to `psychopy.clock._dispatchWindowEvents` which `time.sleep` doesn't. I think adding that next to time.sleep in the waitKyes function would be a good way to go (rather than including core.wait which includes further unnecessary logic about whether we're hogging the CPU). Would you agree @mdcutone ?

@csarradet if you'd like to make that change/pull-request then you'll get the credit for tracking down the issue (we like contributors to get credit). If you'd prefer we do it that's fine too though

**Comment by csarradet** [comment]
@peircej Thanks for the quick reply - you can go ahead with the fix
