### ISSUE TITLE
[Bug]: Space character in column name of conditions file yields `UnboundLocalError` in Builder

### ISSUE THREAD

**Issue by hoechenberger** [psychopy/psychopy#6438]
### PsychoPy Version

v2024.1.4

### What OS are your PsychoPy running on?

macOS Silicon

### Bug Description

Adding a loop with a conditions CSV file that has a space in at least of the column names yields, immediately after selecting the file:

```python
Traceback (most recent call last):
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/app/builder/dialogs/__init__.py”, line 1681, in onBrowseTrialsFile
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/app/builder/dialogs/__init__.py”, line 1715, in updateSummary
  File “/Applications/PsychoPy.app/Contents/Resources/lib/python3.8/psychopy/data/utils.py”, line 499, in importConditions
UnboundLocalError: local variable ‘trialList’ referenced before assignment
```

### Expected Behaviour

PsychoPy should parse the conditions file

### Steps to Reproduce

1. Create a CSV file with e.g. the following content:

    ```csv
    Col1,Col 2
    Foo,Bar
    ```

1. In Builder, `Insert Loop` and select the CSV file for `Condition`

### Additional context

Removing the space (`Col 2` -> `Col2`) works around the problem.

Has been reported on the forum before:
https://discourse.psychopy.org/t/unboundlocalerror-local-variable-triallist-referenced-before-assignment/13472

**Comment by TEParsons** [comment]
This seems to be specific to CSV files, with xlsx files it's intercepted and displayed by the dialog as it should be:
![image](https://github.com/psychopy/psychopy/assets/25686106/0bbcb514-d2f6-4ff8-9b3f-0c0aa41489ba)

Looking at the code I think it's that the csv loading code doesn't call `_assertValidVarNames`, so rather than raising the error that's caught safely (`psychopy.exceptions.ConditionsImportError`) it carries on and hits something unhandled. I'll try to add some checking code in, some time after we have column names but before we hit that error

**Comment by hoechenberger** [comment]
Thanks, @TEParsons!
