### ISSUE TITLE
[Bug]: Plugin component instances fail to load when `reloadPrevExp` enabled

### ISSUE THREAD

**Issue by domstoppable** [psychopy/psychopy#6569]
### PsychoPy Version

2024.1.5

### What OS are your PsychoPy running on?

macOS Silicon

### Bug Description

When using Builder, plugin components show as unknown components (puzzle piece with question mark) if the experiment is loaded at startup via the `reloadPrevExp` preference. Saving the experiment in this state changes the XML tag in the `.psyexp` file, causing it to be broken in future loads as well.

### Expected Behaviour

Plugin components should be available even when an experiment is automatically loaded

### Steps to Reproduce

1. Create a Builder experiment
2. Open preferences and ensure `reloadPrevExp` is enabled
3. Add a component that comes from a plugin (I used the AprilTag component from the Pupil Labs eyetracker plugin)
4. Save the experiment
5. Close and re-open Psychopy
6. Observe the broken component
...

### Additional context

With `reloadPrevExp`, I suspect that the experiment is loaded before plugins.

In addition to correcting that, I'd also suggest that unknown components are not saved as "UknownPluginComponent" in the `.psyexp`. Rather, they should maintain the tag they previously had. This would also occur if someone opens an experiment that requires a plugin that they did not have installed and configured as a startup plugin.

**Comment by TEParsons** [comment]
The first bug you describe (not recognising Components if loading the experiment on launch) is exactly as you say, the first call to `activatePlugins` is after creating the starting frames and reopening experiments. `activatePlugins` can be called earlier, so that's an easy fix - will get that in ASAP.

We certainly should be saving unrecognised plugin Components by the name from the experiment file rather than `UnknownPluginComponent` - I'll look into why that's not happening. 

I'll link the PR for the first fix to this issue so it closes on merge, then make a second issue for the second bug.

**Comment by TEParsons** [comment]
Ahh, looks like the value of `UnknownPluginComponent.type` was being overwritten by the base Component init code, meaning the original class name was lost. Won't bother with another issue, will just link to this one :)
