### ISSUE TITLE
[Discussion]: Should EyeTrackerRecordComponent be a StandaloneRoutine?

### ISSUE THREAD

**Issue by TEParsons** [psychopy/psychopy#6612]
As pointed out in #6607, EyeTrackerRecordComponent works quite differently from most Components in that it has the capacity to *just* start or *just* stop, where all other Components with timing both start and stop during a Routine. The reason for this is that it just does one thing (either starting or stopping an eyetracker) and then moves on. 

The question is: Would this make more sense as a Standalone Routine? Or maybe a pair of Standalone Routines (one for starting and another for stopping)?

**Comment by peircej** [comment]
The reason we decided against that initially was that people might want to start and stop the tracking at fixed points within a trial. Maybe that use case is rare though

**Comment by mh105** [comment]
I'm gonna push back and argue that it _needs_ to be a component instead of a standalone routine. This is because cognitive neuroscientists need to have more granular control of when eye tracking starts and stops during a routine.

In fact, a huge motivation for me to fix the EyetrackerRecord component is because I wanted my students to be able to think about how the recording is timed relative to key cognitive events in an experiment. Otherwise I could have used `pylink` and just inserted code components to start and stop recording in the first place, which would have been easier than making PRs...

Besides, there is the tradition in pupillometry research to start/stop recording around each trial. Although this is a bad practice for reasons that I won't go into here (the more correct way is to start recording at the beginning of an experiment and send timestamp triggers), people still do it enough that if PsychoPy can't easily do it with a component, researchers will resort to code components that are more prone to errors.

So I personally think the current `EyetrackerRecordComponent` (after the recent fix in #6607) is working reasonably well enough  that I'm willing to recommend folks around me to use it.

**Comment by peircej** [comment]
All solid arguments. Let's close
