### ISSUE TITLE
[Bug]: gui.DlgFromDict changing keys when order is specified

### ISSUE THREAD

**Issue by JMankewitz** [psychopy/psychopy#6808]
### PsychoPy Version

2024.2.1

### What OS are your PsychoPy running on?

Windows 10, macOS Intel, macOS Silicon

### Bug Description

When using `dui.DlgFromDict` with a specified order, new key-value pairs with the original key and their order are appended to the dictionary instead of editing the values in-place. For example:

```
gui_dict = {"test1": False, "test2": False}
dlg = gui.DlgFromDict(gui_dict, order = ["test1", "test2"])
print(gui_dict)
```

returns (when the booleans are toggled to `True`...)

`{'test1': False, 'test2': False, 'test1|0': True, 'test2|1': True}`

instead of 

`{'test1': True, 'test2': True}`

This means we're unable to predictably retrieve the new values from users' input. 

If you have any other suggestions for using the DlgFromDict with a variable dict length, I'd love to know!

### Expected Behaviour

`dlg.DlgFromDict` should edit the dictionary values in-place instead of appending new key-values to the dictionary.

### Steps to Reproduce

```
gui_dict = {"test1": False, "test2": False}
dlg = gui.DlgFromDict(gui_dict, order = ["test1", "test2"])
print(gui_dict)
```

**Comment by TEParsons** [comment]
Ah, I see the problem... In the interest of reusing code where possible, I thought "let's use the new pipe syntax to achieve what we were previously doing with `order`", but of course adding pipe syntax to the key means it appears in the final dict as a new key. I think the same is also true of the `fixed` param - you'll get `|fix` on the end in the final dict.

I think this is fixable though, the code which adds those characters is right before the code which does the sorting, so I think it's just a case of doing the sorting from the params given rather than by proxy of the pipe syntax. Will try to get this sorted ASAP!
