### ISSUE TITLE
Does PsychoPy currently require Python < 3.11?

### ISSUE THREAD

**Issue by mark-andrews** [psychopy/psychopy#6839]
### PsychoPy Version

2024.1.3-1029-gfe5cfd368

### What OS are your PsychoPy running on?

Linux-based systems

### Bug Description

I tried pip installing from the `dev` branch on Arch Linux as follows:
```
pip install --no-deps git+https://github.com/psychopy/psychopy.git@dev
```

Installation failed with:
```
ERROR: Package 'psychopy' requires a different Python: 3.12.5 not in '<3.11,>=3.8'
```

This requirement is found here in `pyproject.toml`:
https://github.com/psychopy/psychopy/blob/fe5cfd368867ff856bd83e09cc75b47629fefd29/pyproject.toml#L5

In a local clone of the repo, I changed that line to
```toml
requires-python = ">=3.8"
```
and then installed with 
```
pip install -e .
```
And that worked.

I presume there is no real requirement for Python versions less than 3.11? 

### Expected Behaviour

Pip installation should have succeeded,

### Steps to Reproduce

After pip installing the dependencies
```
pip install --no-deps git+https://github.com/psychopy/psychopy.git@dev
```

### Additional context

I am using Python 3.12.5 on Arch Linux.

**Comment by peircej** [comment]
None of the core team have done any work testing py>=3.11 so I'm not comfortable us changing that status to say it's supported. More than that, I _expect_ some things to fail, because there are many dependencies and it's unlikely they all work on cutting-edge versions of Python. If you've found it broadly works on py12 then that's great and maybe you could document here the issues that _don't_ work (e.g. the packages that you haven't been able to install etc) that would be great

**Comment by mark-andrews** [comment]
I understand.

I'll continue using 3.12 and see what happens. So far, the only issue I've encountered is the problem described here https://github.com/psychopy/psychopy/issues/6808 but I assume, though haven't tested it make sure, that that occurs with Python < 3.12 too.

**Comment by mark-andrews** [comment]
I assume this issue should be closed. But I will let @peircej or others decide.

**Comment by peircej** [comment]
OK, it is also an interesting issue to track... testing how close we are to supporting py3.11 and py3.12
But I guess that can be a new thread/issue
