### ISSUE TITLE
[Bug]: Export to HTML, or running locally with the "Pilot in browser" option produce code that doesn't work, missing files, etc. 

### ISSUE THREAD

**Issue by MichaelWoodc** [psychopy/psychopy#6850]
### PsychoPy Version

2024.2.1

### What OS are your PsychoPy running on?

Windows 11

### Bug Description

It seems psychopy is not exporting the correct files for the page to work.  For example, this file is missing: 
![image](https://github.com/user-attachments/assets/bf55850c-a8a9-4733-8d9d-a4684a4391e2)

other file issues create these errors:
![image](https://github.com/user-attachments/assets/37e6a750-d209-4629-b91c-114c704ec277)

Depending on how I try and solve the issue on my PC, one thing that I can't resolve is this:
![image](https://github.com/user-attachments/assets/c4aac873-acd9-42e2-997e-1246864f769a)

I tried to grab the file from the pavlovia website by viewing source of some experiments developed recently but I cannot find it anywhere!

Also psychopy has the same issues when generating the javascript then trying to view the files from psychopy:

![image](https://github.com/user-attachments/assets/04094c82-ede5-4a56-8ff9-b5a133027c28)

### Expected Behaviour

I would hope I could run it in my browser

### Steps to Reproduce

1.export html and / or javascript options
2. try and open in browser
3. press f12 and see errors / non working page
...

### Additional context

This only happens with certain experiments, some seem to run fine in the browser EDIT: Cannot currently remember the experiment it may have been, and I can not currently find one that works

**Comment by TEParsons** [comment]
This was specific to the 3.10 standalone installer for 2024.2.1 - essentially, after release we realised that one of the installers was missing git, so pulled it and replaced it with a fixed version. To make it easier to tell which installer someone had used, we added `post1` to the version number - not realising that this would break PsychoJS code as `post` isn't on the list of things we strip from the version number (we do cover `rc` and `dev` for example). @jon fixed this in #6873 for future installs, and  the newest version doesn't have `post1` in the installer's version anyway.

I would guess the experiments which still worked were ones with "useVersion" set as something in their experiment settings - as that would mean the version number was whatever that value was instead of `2024.2.1post1`
