### ISSUE TITLE
[Bug]: PsychoPy crashes on startup after error about locale not found

### ISSUE THREAD

**Issue by meetinthemiddle-be** [psychopy/psychopy#6898]
### PsychoPy Version

2024.2.2

### What OS are your PsychoPy running on?

macOS Silicon

### Bug Description

After installing PsychoPy 2024.2.2 (StandalonePsychoPy-2024.2.2-macOS-py3.10.dmg) on MacOS Sonoma 14.6.1 with a locale set to "English (Belgium)", Starting the application renders an error message saying 

```
PsychoPy3 Warning 
Cannot set locale to language "English (Belgium)".
```

~/.psychopy3/last_app_load.log has one line:
`0.5990 	DEBUG 	Opening message catalog /Applications/PsychoPy.app/Contents/Resources/lib/python3.10/psychopy/localization/../app/locale/en_US/LC_MESSAGE/messages.mo for locale en_US`

### Expected Behaviour

If the log classifies this as "DEBUG" and the message on screen is marked as a "Warning", I would not expect a crash of the program.

### Steps to Reproduce

1. Install on a MacOS with locale set to English (Belgium)
2. Start the application

### Additional context

MacOS generates a crash report to be sent to Apple which is 3280 lines long. I don't feel comfortable posting it here (too long and probably also has some unique IDs pointing to my machine), but if necessary for debugging I can share a copy. From this crash report, however, that this might also have something to do with Rosetta transforming the x86-64 code to Apple Silicon:

```
Thread 0 Crashed:: PTB mainthread Dispatch queue: com.apple.main-thread
0   ???                           	    0x7ff8954c6a78 ???
1   libsystem_kernel.dylib        	    0x7ff8051dedb6 __pthread_kill + 10
2   libsystem_pthread.dylib       	    0x7ff805217ebd pthread_kill + 262
3   libsystem_c.dylib             	    0x7ff80513da79 abort + 126
4   libsystem_malloc.dylib        	    0x7ff8050423a9 malloc_vreport + 857
..
..
58  Python                        	       0x10ef4d8a1 _PyEval_EvalFrameDefault + 24193
59  Python                        	       0x10ef4604f 0x10ed92000 + 1785935
60  Python                        	       0x10efbb9fd 0x10ed92000 + 2267645
61  Python                        	       0x10efbb1bd _PyRun_SimpleFileObject + 365
62  Python                        	       0x10efbecad PyRun_SimpleFileExFlags + 109
63  PsychoPy                      	       0x1043d6ec5 0x1043d2000 + 20165
64  PsychoPy                      	       0x1043d5357 main + 257
65  dyld                          	       0x2046e5345 start + 1909

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7fff1b414 0x7ff7fff17000 + 17428

..
..
..

```

**Comment by meetinthemiddle-be** [comment]
Since PsychoPy experiments don't run in a Windows virtual machine (lacking graphics capabilities), the severity of this bug is critically hampering MacOS-only users.

**Comment by peircej** [comment]
Hi there, thanks for posting. I think the locale warning is unrelated to the crash

I imagine the crash is the same as the discussion on discourse that I link here for cross-referencing:
https://discourse.psychopy.org/t/psychopy-crashes-immediately-upon-launching-it-on-imac-apple-m3-macos-sequoia-15/42295

The tricky thing is that this fails on some systems but not all - and we've seen different error messages for some people than others. So it's a confusing bug but we're working to try and understand what's causing the crashes

**Comment by peircej** [comment]
I wonder if you could try installing [this version](https://drive.google.com/file/d/1fkvUeYVqImahdfQyEZVjfjkC3-u5B_Xd/view?usp=sharing), which has been built using a different version of setuptools, since there are some reports that some versions of that can interact badly with the packaging lib we use (py2app)

**Comment by meetinthemiddle-be** [comment]
Hey Pierce, appreciate the ad-hoc build, but can you please get me a file that has a bit more certainty that it hasn't been tampered with? (e.g., have this built by GithubActions and publish it through there)? The security warnings I'm getting from Google Drive are a bit ominous and company policy prevents me from moving forward after such a warning:

```
Google Drive has detected issues with your download

This file is too large for Google to scan for viruses.

This file is executable and may harm your computer.
```


Sorry for the hassle, but I'm more than happy to help troubleshoot the MacOS issues on my end if I can get a legit download link.

Thanks in advance!

**Comment by peircej** [comment]
Actually the build *was* made through github actions, just not stored there because it isn't a release. The message is only to say that google drive doesn't do a virus scan of the file. But if you download it you can virus scan it yourself but you'll also be able to confirm that the file is signed by us (Open Science Tools) with the same digital signature as the usual release - both the dmg file and the app bundle inside it are signed by the exact same process as our release. That allows you to confirm that this comes from us and cannot have been tampered with along the way.

But no worries. A few people on the discourse thread I linked to have found that this does solve the issue for them so I'm confident that is the issue and closing this. We have a couple more minor things I want to bring in before formally releasing 2024.2.3. So you can also just wait a few days for the official release.
