### ISSUE TITLE
[Bug]: Getting the code and builder to start; default setting is not 'all'

### ISSUE THREAD

**Issue by jnvandermeer** [psychopy/psychopy#6939]
### PsychoPy Version

2024.2.1

### What OS are your PsychoPy running on?

Linux-based systems

### Bug Description

I have installed psychopy on Arch Linux, and one of the last issues was that the builder and the coder did not start.

The culprit was a setting  in the code I found in _psychopyApp.py, line 557, that the defaultView needs to be not set to 'last', but to 'all'. Since it was my first installation, the last setting was an empty list, so none of the windows started.

I recommend setting/changing the default userPrefs.cfg file that you distribute in pip; change the defaultview to 'all', instead of 'prev'. (because there is no prev on a first installation)

Many thanks
Johan

### Expected Behaviour

see above; code and builder should start by default on a first installation

### Steps to Reproduce

starting psychopy in a conda environment on Linux , after installing the required packages

`conda activate psychopy`
`psychopy`

**Comment by peircej** [comment]
I believe this is fixed better in https://github.com/psychopy/psychopy/pull/6926

I think "last" is the best option for the preference, rather than all. I close the app with Cmd-Q and when I reopen the app I want to have the same windows come back. BUT if there is no last THEN we should open all. So #6926 leaves default preference as "last" but handles the absence of a previous frames in appData.cfg
