### ISSUE TITLE
Builder components not accessible after deleting ISI

### ISSUE THREAD

**Issue by kohlman** [psychopy/psychopy#853]
I was deleting an ISI during which some components were updated. The components were still visible, but I couldn't edit them anymore (only components with ISI update were affected), i.e., clicking them or choosing "edit" didn't give me the dialog anymore. I went into the .psyexp file with a text editor and changed the relevant options to "constant", then everything was fine again.

I don't know how this should be handled best. One could just set the updates back to "constant" or display a warning in a dialog box when you are trying to delete an ISI that is used.

**Comment by jeremygray** [comment]
Hard to say what seems best here. But dong something seems like an improvement :-) How about reverting back to constant plus raise some sort of warning? Warnings are easy to miss, but no one should have to edit the psyexp file manually.

**Comment by kohlman** [comment]
Yeah, that's probably the best solution. In this case, one would have to check all components of the relevant routine to see whether they are using the ISI. Do you know an efficient way of doing this? I can also give it a try - getting to know the code a little bit better ...

**Comment by jeremygray** [comment]
Just looping through all components will be efficient enough. I don't think there's a data structure pre-populated with that info, or some other clever way to get that info more efficiently.

**Comment by peircej** [comment]
Sorry I've been out of the loop (pardon the pun) on this one. The last 
month I've been organising recruitment for our PhD programme and it's 
been mayhem. Hopefully I'll have time to be a bit more involved with 
this one because it's a potential bees nest I think!

Did either of you do any actual work on this yet, or was it in ideas stage?

You're right:
     1) the Static component (SC) should ideally work from a different 
routine to its own
     2) when we delete one it should inform all the components that 
point to it that they need to change their value.

My initial work to try and make this work was that the SC should store a 
list of components that currently use it. It has
StaticComponent.updatesList #to keep track
StaticComponent.addComponentUpdate(routine, compName, fieldName) #new 
component using this static
StaticComponent.remComponentUpdate(routine, compName, fieldName) #remove 
component using this static

These should be used by the Routine view when it gets deleted to find 
all the routines that point to it and alter the updates setting for that 
`fieldName` in that `compName` of that `routine`. As you say the trick 
is to know what to do with it. Options:
     - Setting it to update 'each repeat' would be the most likely to 
just work after the SC has been deleted
     - the problem is that because it still appeared to work it might 
not be noticed that an image was now being updated at a time-critical 
point in the study. Usually I want catastrophic failure if something is 
going to go wrong, whereas this could have a damaging but unnoticed 
impact on timing.

Ideally I guess we'd take the user to the desired option and highlight 
that it needed fixing. Such a mechanism could also be used in other 
places, e.g. to take the user to a variable that had been set to be 
'constant', detected at compile time.

**Comment by jeremygray** [comment]
Agree. Fail loudly not quietly. And yes a good solution here would indeed be useful more broadly. I still get tripped up on variables being set to constant updating (and failing).

**Comment by kohlman** [comment]
Hi Jon,

Definitely in the ideas stage ;-) Good to know that there are already functions available. Maybe set back to 'each repeat' and at least log a warning, as Jeremy suggested, as a first step. And then probably you already had an idea how you wanted to do the highlighted. It probably has to be a dialog box not giving back control to users because one would have to step through all releveant components ...

**Comment by jeremygray** [comment]
See also #871. Might try to clean that up at the same time if possible.

**Comment by TEParsons** [comment]
Appears to be working in 2022.1.1!
