### ISSUE TITLE
win.multiFlip() misbehaving?

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#867]
Three issues:

1)

I get flickering when the display should be solid (as I interpret the intended behavior, based on the doc string description "Flips multiple times while maintaining display constant."):

    from psychopy import visual
    win = visual.Window()
    stim = visual.ImageStim(win)
    #stim.autoDraw = True
    stim.draw()
    win.multiFlip(15)

 The display of the stim is solid (no flicker) if autoDraw is True:

    from psychopy import visual
    win = visual.Window()
    stim = visual.ImageStim(win)
    stim.autoDraw = True
    #stim.draw()
    win.multiFlip(15)

2)

This line looks odd -- change to `or not int(flips) == flips`:

    if flips < 1 and int(flips) == flips:
        logging.error("flips argument for multiFlip should be a positive integer")

3)

multiFlip is not documented online

**Comment by hoechenberger** [comment]
If ``autoDraw`` is ``False``, the first flip in ``multiFlip()`` would actually draw the box; the second would blank the screen; the third would draw it again; etc. With ``autodraw = True``, the stimulus would be drawn before every flip. I don't know what's going on there, as my understanding of PsychoPy's drawing/OpenGL functions is very limited.

**Comment by peircej** [comment]
The problem with multiflip is that it uses the concept of flipping but not clearing the framebuffer (rather than flipping and redrawing all the objects). Flipping but not clearing is unpredictable - on some cards it literally swaps the back and front buffers (so your stimulus flashes on and off each frame) but on some cards it populates the back buffer with a copy of the (new) front buffer (so your stimulus will stay). The latter is the more useful behaviour for us but I don't know how to detect if that happened.

I'd personally recommend not using multiflip!

**Comment by hoechenberger** [comment]
Thanks for the clarification, Jon!
Should ``multiFlip`` better be removed from the codebase, then? Or we should at least add a big fat read warning in the code somehow..? :)

**Comment by peircej** [comment]
I think a warning is a good idea. This is the reason that multiflip is not documented online, but documenting and saying that behaviour is unpredictable seems a better plan.

**Comment by jacob-lee** [comment]
> Flipping but not clearing is unpredictable - on some cards it literally swaps the back and front buffers (so your stimulus flashes on and off each frame) but on some cards it populates the back buffer with a copy of the (new) front buffer (so your stimulus will stay). 

I'm not using multiflip but rediscovered this behavior writing something custom using psychopy, which I hadn't noticed doing something similar with just pygame. I've since changed my dev machine, so that might account for it, but I'd be grateful if you might elaborate on this card-specific behavior when the buffer is not refreshed, or point to where I might find out more? I have a variety of legacy tasks written in pygame that take this approach, and I'd be interested to know if it is potentially problematic.
