### ISSUE TITLE
visual.Circle API mentions colorSpace,

### ISSUE THREAD

**Issue by alexholcombe** [psychopy/psychopy#908]
but "colorSpace" is no longer an allowed keyword - throws an error.
http://www.psychopy.org/api/visual/circle.html#psychopy.visual.Circle
Same thing with Rect, I suspect.
Seems like the documentation is partway between the old PatchStim and the new ShapeStim.

**Comment by peircej** [comment]
Ah, yes, the problem is that 'color' and 'colorSpace' should not exist for shape-based stimuli because it's ambiguous with lineColor/Space and fillColor/Space. Actually, more recently, I feel like we could allow this and use it to set both lineColor and fillColor when it gets used.

**Comment by lindeloev** [comment]
@peircej, I think having ``color`` and ``colorSpace`` set both attributes is a good idea. It makes the API more consistent across stimuli. I would suggest that specifying ``color``/``colorSpace`` using this and line/fill color/colorSpace at stimulus initiation should throw an error rather than one taking precedence over the other. But after initiation, ``color``/``colorSpace`` just overwrites the existing value of fill/line color/colorSpace.

**Comment by peircej** [comment]
I agree with all of that :-)

**Comment by TEParsons** [comment]
This will be addressed when #3189 is ready to pull in :) colorSpace for all stimuli sets the color space for all attributes (foreColor, fillColor and borderColor) and for Shape stim, color sets fillColor and lineColor instead (actually I think the latter is already the case)
