### ISSUE TITLE
memory leak for MovieStim2

### ISSUE THREAD

**Issue by kijoshua** [psychopy/psychopy#910]
MovieStim2 objects never seem to get garbage collected, which is a huge problem for experiments that play a lot of movies.  In my tests, the experiment would run out of memory after just 27 short videos.

All the movies end up sitting in gc.garbage because the garbage collector can't figure out how to break the reference cycles (see https://docs.python.org/2/library/gc.html#gc.garbage for more information).  Simplest solution is to get rid of that \__del__ method and require explicit unloading of movie objects.  So for now, a workaround for users is to add a call to the _unload method of every MovieStim2 object when they are done with it.

I don't know if this problem shows up elsewhere, but it is a safer and simpler practice to explicitly close things than to assume that the \__del__ method will ever be called (and note that del obj doesn't call obj.\__del__(): https://docs.python.org/2/reference/datamodel.html#object.__del__).

**Comment by peircej** [comment]
Although it's true that __del__ methods can take some work to get right (to iron out any circular references) the alternative of requiring users to manually unload things is going to cause more errors in people's experiments than this. Remember that most users aren't trained-programmers.

So the solution is for us to find the circular references and remove them. We've clearly managed this with images already because we used to get complaints about that (before we had __del__ method the graphics card texture memory would fill up) and those have all stopped. I'm sure we can do the same for movies.

If you've made some progress into this maybe you can help locate the circulatiry and turn it into a weakref object?

cheers

**Comment by kijoshua** [comment]
Those using the builder wouldn't need to know, and those using the coder could reasonably be expected to skim the documentation/examples when they start running out of memory... but your point still stands.  

I've not made any progress, sorry.

**Comment by peircej** [comment]
I think this is fixed in a060d518a544
