### ISSUE TITLE
creating arrow stimuli

### ISSUE THREAD

**Issue by ronrosenberg** [psychopy/psychopy#934]
I saw the code in this link (below) that can draw arrows. I'm not the best with python, but is there any way to fill in the arrow stimulus with color (the square is filled in already, but applying the same code doesn't work entirely). Thanks

https://github.com/psychopy/psychopy/blob/master/psychopy/demos/coder/stimuli/shapes.py

~R

**Comment by peircej** [comment]
No, the problem is that to opengl it doesn't know what's "inside" and 
what's "outside" and make the guess that the inside is always the 
sharper side of the angle by default. As a result it works fine for 
squares but not for something with concavities in the shape.

I believe there's something in opengl to do with "winding rules" that 
allows you to specify the "inside" of a filled 
shapehttp://www.songho.ca/opengl/gl_tessellation.html but it seems too 
complicated to add in.

Of course, you could create a square and a triangle and make your arrow 
that way?

On 02/07/2015 20:50, cron3d wrote:
>
> I saw the code in this link (below) that can draw arrows. I'm not the 
> best with python, but is there any way to fill in the arrow stimulus 
> with color (the square is filled in already, but applying the same 
> code doesn't work entirely). Thanks
>
> https://github.com/psychopy/psychopy/blob/master/psychopy/demos/coder/stimuli/shapes.py
>
> ~R
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/psychopy/psychopy/issues/934>.
>

-- 
Jon Peirce
http://www.peirce.org.uk

**Comment by jeremygray** [comment]
This is now easy to achieve with ShapeStim2. (An arrow is one of the demo shapes.)
