### ISSUE TITLE
Extremely large .psydat files

### ISSUE THREAD

**Issue by achetverikov** [psychopy/psychopy#950]
Sometimes PsychoPy (v 1.82.01) generates extremely large psydat files. For 150kb csv I have pickled data with sizes over 100 Mb. Interestingly, 7zip manages to compress them to really small sizes effortlessly. Here is an example: https://copy.com/0QIVaCIgOVtTRDSh - 180 Mb psydat compressed to 355 Kb 7z.

This issue has been reported in association with condition loops here: https://groups.google.com/forum/#!searchin/psychopy-users/psydat/psychopy-users/TPudxceQ1ws/zEwIEqLv7mUJ

Not sure if it is the case for my own data. Although there are some conditional branches, I also experienced this issue (but not to such extent) when working with scripts written without builder that were pretty straightforward. Here is an example from such script: https://copy.com/zO1CNkHRUGxvhNbf 10 Mb psydat compressed to 1 Mb 7zip. But maybe in this case the size is more reasonable due to the large number of objects and trials.

**Comment by peircej** [comment]
OK, I can definitely see why this might happen in an experiment with lots of loops (e.g. nested loops). PsychoPy tries to store a copy of the entire experiment within the psydat file, but what's happening here is that it's also storing a copy with each individual loop. That means lots of copies of the experiment file. 

I'll need to work out a mechanism so that only the ExperimentHandler stores the file OR the TrialHandler stores it (if no experiment handler is created then we should try to store it with the loop as before).

**Comment by peircej** [comment]
My thoughts on this didn't pan out - having multiple "copies" of the experiment saved in the data file wasn't the issue because, actually, they're just pointers of a single object and they're saved correctly that way too.

So now I suspect that the issue is actually to do with the fact that we preallocate space for saving data when you create your loops. Maybe you have nested loops(?) and even if you don't "use" all the trials in each one by aborting them early the space is created for each.

**Comment by ralfer** [comment]
I do have nested loops, so this explanation is entirely possible. Is it possible to understand what's going on from the pickle files I uploaded? I could also upload the script somewhere if this would help.

**Comment by hoechenberger** [comment]
@ralfer Does this problem still exist with the latest release of PsychoPy? If yes, it would be very helpful if you could provide your experiment script. Thanks!

**Comment by hoechenberger** [comment]
@achetverikov Does this problem still exist with the latest release of PsychoPy? If yes, it would be very helpful if you could provide your script. Thanks!

**Comment by achetverikov** [comment]
@hoechenberger Sorry for a very slow reply. I think the problem is still here. Here are two example scripts: main_dynamics_set_size.py can be run automatically without any input from participant and creates ~36MB psydat file. The other one, change_blindness_exp does require input from participant and it generates ~100 MB psydat. I think it's because there are a lot of stimuli on each trial, and maybe the easiest solution would be to add some compression by default when experiment finishes.

[change_blindness_exp.zip](https://github.com/psychopy/psychopy/files/736938/change_blindness_exp.zip)
[dynamics_set_size.zip](https://github.com/psychopy/psychopy/files/736939/dynamics_set_size.zip)

**Comment by peircej** [comment]
I don't really know what the answer is. The csv file gets to be only 5mb (but doesn't contain as much info) so the psydat is only a few times bigger. Potentially we could investigate further by seeing I python sys.sizeof() to examine the attributes of the experiment object but I think it might simply be that these files contain lots of data.
Yes, as you say, simply compressing the file after running may be the solution (or simpifying your experiments! ;-) )

**Comment by achetverikov** [comment]
Thanks for looking into that! I totally understand that this is not a priority. Just a quick question: can I "close" the experiment before quitting the script with core.quit() to ensure that the pickle is saved before compressing it?
