### ISSUE TITLE
gui.DlgFromDict title name bug

### ISSUE THREAD

**Issue by Chippers255** [psychopy/psychopy#956]
When using the guy.DlgFromDict class if I set the title to a name with spaces and desire to use lists in my dictionary form then the information from the drop-down boxes is not saved.

This works:
```
answers = ['1', '2', '3', '4']
info = {'q1':answers, 'q2':answers, 'q3': answers, 'q4': answers}
infoDlg = gui.DlgFromDict(dictionary=info, title='questions')
if infoDlg.OK:
    print info
else: print 'User Cancelled'
```

This does not:
```
answers = ['1', '2', '3', '4']
info = {'q1':answers, 'q2':answers, 'q3': answers, 'q4': answers}
infoDlg = gui.DlgFromDict(dictionary=info, title='question form')
if infoDlg.OK:
    print info
else: print 'User Cancelled'
```

**Comment by jeremygray** [comment]
I am using wx version 3.0.0.0 on mac (which I believe will be part of the next release of PsychoPy 1.83.00). If I set the responses to 1, 2, 3, 4 in order, both versions work and return `{'q1': u'1', 'q3': u'3', 'q2': u'2', 'q4': u'4'}`. So, if you are using wx 2.x now, I expect that what you are seeing will be fixed in the next release of PsychoPy.
