### ISSUE TITLE
memory leak in visual.TextStim seems like a pyglet issue

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#973]
So I filed a bug report with them: https://bitbucket.org/pyglet/pyglet/issues/66

**Comment by jeremygray** [comment]
They appear to have implemented a fix for both Windows and Linux, and believe its not an actual leak for OS X. No idea when pyglet will be updated.

**Comment by hoechenberger** [comment]
This apparently was fixed
* [for Windows](https://bitbucket.org/pyglet/pyglet/commits/bb6d04bb81d841703b19ba7c9beab5214f4e740f?at=default),
* [for Linux] (https://bitbucket.org/pyglet/pyglet/commits/66aff04cb29fa01e9044c055c6f9d84b768b302a?at=default),
* and [for OS X](https://bitbucket.org/pyglet/pyglet/commits/930ec395c20c3aba89a7f40af053213c66e8d361?at=default)

These fixes (and many more) can be found in the [`pyglet-1.2-maintenance`](https://bitbucket.org/pyglet/pyglet/branch/pyglet-1.2-maintenance) branch. I don't know if any new releases including these changes have been prepared since the fixes were implemented.

**Comment by hoechenberger** [comment]
Maybe we should consider shipping the maintenance branch of Pyglet with PsychoPy standalone?

**Comment by peircej** [comment]
Ah, I thought it had been folded in and released so the last release I just updated pyglet but apparently not far enough?

**Comment by hoechenberger** [comment]
Yep, as far as I can tell, it apparently has not been integrated into the last pyglet release...

**Comment by peircej** [comment]
Standalone for OSX and win32 both use maintenance 1.2 of pyglet now
